// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ActivateInventoryHotbarHandler(ReducerEventContext ctx, byte slot, ulong expectedRevision, string operationId);
        public event ActivateInventoryHotbarHandler? OnActivateInventoryHotbar;

        public void ActivateInventoryHotbar(byte slot, ulong expectedRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.ActivateInventoryHotbar(slot, expectedRevision, operationId));
        }

        public bool InvokeActivateInventoryHotbar(ReducerEventContext ctx, Reducer.ActivateInventoryHotbar args)
        {
            if (OnActivateInventoryHotbar == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnActivateInventoryHotbar(
                ctx,
                args.Slot,
                args.ExpectedRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ActivateInventoryHotbar : Reducer, IReducerArgs
        {
            [DataMember(Name = "slot")]
            public byte Slot;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public ActivateInventoryHotbar(
                byte Slot,
                ulong ExpectedRevision,
                string OperationId
            )
            {
                this.Slot = Slot;
                this.ExpectedRevision = ExpectedRevision;
                this.OperationId = OperationId;
            }

            public ActivateInventoryHotbar()
            {
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "activate_inventory_hotbar";
        }
    }
}
