// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CancelConstructionTraversalHandler(ReducerEventContext ctx, string traversalId, string expectedVisitId, ulong expectedRevision, string operationId);
        public event CancelConstructionTraversalHandler? OnCancelConstructionTraversal;

        public void CancelConstructionTraversal(string traversalId, string expectedVisitId, ulong expectedRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.CancelConstructionTraversal(traversalId, expectedVisitId, expectedRevision, operationId));
        }

        public bool InvokeCancelConstructionTraversal(ReducerEventContext ctx, Reducer.CancelConstructionTraversal args)
        {
            if (OnCancelConstructionTraversal == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCancelConstructionTraversal(
                ctx,
                args.TraversalId,
                args.ExpectedVisitId,
                args.ExpectedRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CancelConstructionTraversal : Reducer, IReducerArgs
        {
            [DataMember(Name = "traversal_id")]
            public string TraversalId;
            [DataMember(Name = "expected_visit_id")]
            public string ExpectedVisitId;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public CancelConstructionTraversal(
                string TraversalId,
                string ExpectedVisitId,
                ulong ExpectedRevision,
                string OperationId
            )
            {
                this.TraversalId = TraversalId;
                this.ExpectedVisitId = ExpectedVisitId;
                this.ExpectedRevision = ExpectedRevision;
                this.OperationId = OperationId;
            }

            public CancelConstructionTraversal()
            {
                this.TraversalId = "";
                this.ExpectedVisitId = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "cancel_construction_traversal";
        }
    }
}
