// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ChangeShipFlightFittingHandler(ReducerEventContext ctx, string shipId, string fittingId, string action, ulong expectedRevision, ulong expectedFittingRevision, string operationId);
        public event ChangeShipFlightFittingHandler? OnChangeShipFlightFitting;

        public void ChangeShipFlightFitting(string shipId, string fittingId, string action, ulong expectedRevision, ulong expectedFittingRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.ChangeShipFlightFitting(shipId, fittingId, action, expectedRevision, expectedFittingRevision, operationId));
        }

        public bool InvokeChangeShipFlightFitting(ReducerEventContext ctx, Reducer.ChangeShipFlightFitting args)
        {
            if (OnChangeShipFlightFitting == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnChangeShipFlightFitting(
                ctx,
                args.ShipId,
                args.FittingId,
                args.Action,
                args.ExpectedRevision,
                args.ExpectedFittingRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ChangeShipFlightFitting : Reducer, IReducerArgs
        {
            [DataMember(Name = "ship_id")]
            public string ShipId;
            [DataMember(Name = "fitting_id")]
            public string FittingId;
            [DataMember(Name = "action")]
            public string Action;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "expected_fitting_revision")]
            public ulong ExpectedFittingRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public ChangeShipFlightFitting(
                string ShipId,
                string FittingId,
                string Action,
                ulong ExpectedRevision,
                ulong ExpectedFittingRevision,
                string OperationId
            )
            {
                this.ShipId = ShipId;
                this.FittingId = FittingId;
                this.Action = Action;
                this.ExpectedRevision = ExpectedRevision;
                this.ExpectedFittingRevision = ExpectedFittingRevision;
                this.OperationId = OperationId;
            }

            public ChangeShipFlightFitting()
            {
                this.ShipId = "";
                this.FittingId = "";
                this.Action = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "change_ship_flight_fitting";
        }
    }
}
