// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimInputControlHandler(ReducerEventContext ctx);
        public event ClaimInputControlHandler? OnClaimInputControl;

        public void ClaimInputControl()
        {
            conn.InternalCallReducer(new Reducer.ClaimInputControl());
        }

        public bool InvokeClaimInputControl(ReducerEventContext ctx, Reducer.ClaimInputControl args)
        {
            if (OnClaimInputControl == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimInputControl(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimInputControl : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "claim_input_control";
        }
    }
}
