// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DiscardDefinitionDraftHandler(ReducerEventContext ctx, string kind, string definitionId, ulong expectedRevision, string operationId);
        public event DiscardDefinitionDraftHandler? OnDiscardDefinitionDraft;

        public void DiscardDefinitionDraft(string kind, string definitionId, ulong expectedRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.DiscardDefinitionDraft(kind, definitionId, expectedRevision, operationId));
        }

        public bool InvokeDiscardDefinitionDraft(ReducerEventContext ctx, Reducer.DiscardDefinitionDraft args)
        {
            if (OnDiscardDefinitionDraft == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDiscardDefinitionDraft(
                ctx,
                args.Kind,
                args.DefinitionId,
                args.ExpectedRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DiscardDefinitionDraft : Reducer, IReducerArgs
        {
            [DataMember(Name = "kind")]
            public string Kind;
            [DataMember(Name = "definition_id")]
            public string DefinitionId;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public DiscardDefinitionDraft(
                string Kind,
                string DefinitionId,
                ulong ExpectedRevision,
                string OperationId
            )
            {
                this.Kind = Kind;
                this.DefinitionId = DefinitionId;
                this.ExpectedRevision = ExpectedRevision;
                this.OperationId = OperationId;
            }

            public DiscardDefinitionDraft()
            {
                this.Kind = "";
                this.DefinitionId = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "discard_definition_draft";
        }
    }
}
