// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EditShipFurnishingHandler(ReducerEventContext ctx, string instanceId, string sourceObjectId, string action, double dx, double dy, double yaw, bool snap, ulong expectedRevision, string operationId);
        public event EditShipFurnishingHandler? OnEditShipFurnishing;

        public void EditShipFurnishing(string instanceId, string sourceObjectId, string action, double dx, double dy, double yaw, bool snap, ulong expectedRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.EditShipFurnishing(instanceId, sourceObjectId, action, dx, dy, yaw, snap, expectedRevision, operationId));
        }

        public bool InvokeEditShipFurnishing(ReducerEventContext ctx, Reducer.EditShipFurnishing args)
        {
            if (OnEditShipFurnishing == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEditShipFurnishing(
                ctx,
                args.InstanceId,
                args.SourceObjectId,
                args.Action,
                args.Dx,
                args.Dy,
                args.Yaw,
                args.Snap,
                args.ExpectedRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EditShipFurnishing : Reducer, IReducerArgs
        {
            [DataMember(Name = "instance_id")]
            public string InstanceId;
            [DataMember(Name = "source_object_id")]
            public string SourceObjectId;
            [DataMember(Name = "action")]
            public string Action;
            [DataMember(Name = "dx")]
            public double Dx;
            [DataMember(Name = "dy")]
            public double Dy;
            [DataMember(Name = "yaw")]
            public double Yaw;
            [DataMember(Name = "snap")]
            public bool Snap;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public EditShipFurnishing(
                string InstanceId,
                string SourceObjectId,
                string Action,
                double Dx,
                double Dy,
                double Yaw,
                bool Snap,
                ulong ExpectedRevision,
                string OperationId
            )
            {
                this.InstanceId = InstanceId;
                this.SourceObjectId = SourceObjectId;
                this.Action = Action;
                this.Dx = Dx;
                this.Dy = Dy;
                this.Yaw = Yaw;
                this.Snap = Snap;
                this.ExpectedRevision = ExpectedRevision;
                this.OperationId = OperationId;
            }

            public EditShipFurnishing()
            {
                this.InstanceId = "";
                this.SourceObjectId = "";
                this.Action = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "edit_ship_furnishing";
        }
    }
}
