// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EnterConstructionReviewHandler(ReducerEventContext ctx, string instanceId, string expectedShipId, string operationId);
        public event EnterConstructionReviewHandler? OnEnterConstructionReview;

        public void EnterConstructionReview(string instanceId, string expectedShipId, string operationId)
        {
            conn.InternalCallReducer(new Reducer.EnterConstructionReview(instanceId, expectedShipId, operationId));
        }

        public bool InvokeEnterConstructionReview(ReducerEventContext ctx, Reducer.EnterConstructionReview args)
        {
            if (OnEnterConstructionReview == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEnterConstructionReview(
                ctx,
                args.InstanceId,
                args.ExpectedShipId,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EnterConstructionReview : Reducer, IReducerArgs
        {
            [DataMember(Name = "instance_id")]
            public string InstanceId;
            [DataMember(Name = "expected_ship_id")]
            public string ExpectedShipId;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public EnterConstructionReview(
                string InstanceId,
                string ExpectedShipId,
                string OperationId
            )
            {
                this.InstanceId = InstanceId;
                this.ExpectedShipId = ExpectedShipId;
                this.OperationId = OperationId;
            }

            public EnterConstructionReview()
            {
                this.InstanceId = "";
                this.ExpectedShipId = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "enter_construction_review";
        }
    }
}
