// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EnterLabHandler(ReducerEventContext ctx, string name);
        public event EnterLabHandler? OnEnterLab;

        public void EnterLab(string name)
        {
            conn.InternalCallReducer(new Reducer.EnterLab(name));
        }

        public bool InvokeEnterLab(ReducerEventContext ctx, Reducer.EnterLab args)
        {
            if (OnEnterLab == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEnterLab(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EnterLab : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public EnterLab(string Name)
            {
                this.Name = Name;
            }

            public EnterLab()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "enter_lab";
        }
    }
}
