// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EvaCycleAirlockHandler(ReducerEventContext ctx, string shipId, string airlockId);
        public event EvaCycleAirlockHandler? OnEvaCycleAirlock;

        public void EvaCycleAirlock(string shipId, string airlockId)
        {
            conn.InternalCallReducer(new Reducer.EvaCycleAirlock(shipId, airlockId));
        }

        public bool InvokeEvaCycleAirlock(ReducerEventContext ctx, Reducer.EvaCycleAirlock args)
        {
            if (OnEvaCycleAirlock == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEvaCycleAirlock(
                ctx,
                args.ShipId,
                args.AirlockId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EvaCycleAirlock : Reducer, IReducerArgs
        {
            [DataMember(Name = "ship_id")]
            public string ShipId;
            [DataMember(Name = "airlock_id")]
            public string AirlockId;

            public EvaCycleAirlock(
                string ShipId,
                string AirlockId
            )
            {
                this.ShipId = ShipId;
                this.AirlockId = AirlockId;
            }

            public EvaCycleAirlock()
            {
                this.ShipId = "";
                this.AirlockId = "";
            }

            string IReducerArgs.ReducerName => "eva_cycle_airlock";
        }
    }
}
