// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EvaSetSuitHandler(ReducerEventContext ctx, string mode, double facing, bool facingActive);
        public event EvaSetSuitHandler? OnEvaSetSuit;

        public void EvaSetSuit(string mode, double facing, bool facingActive)
        {
            conn.InternalCallReducer(new Reducer.EvaSetSuit(mode, facing, facingActive));
        }

        public bool InvokeEvaSetSuit(ReducerEventContext ctx, Reducer.EvaSetSuit args)
        {
            if (OnEvaSetSuit == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEvaSetSuit(
                ctx,
                args.Mode,
                args.Facing,
                args.FacingActive
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EvaSetSuit : Reducer, IReducerArgs
        {
            [DataMember(Name = "mode")]
            public string Mode;
            [DataMember(Name = "facing")]
            public double Facing;
            [DataMember(Name = "facing_active")]
            public bool FacingActive;

            public EvaSetSuit(
                string Mode,
                double Facing,
                bool FacingActive
            )
            {
                this.Mode = Mode;
                this.Facing = Facing;
                this.FacingActive = FacingActive;
            }

            public EvaSetSuit()
            {
                this.Mode = "";
            }

            string IReducerArgs.ReducerName => "eva_set_suit";
        }
    }
}
