// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void FireWeaponHandler(ReducerEventContext ctx, string itemId, ulong expectedRevision, string operationId);
        public event FireWeaponHandler? OnFireWeapon;

        public void FireWeapon(string itemId, ulong expectedRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.FireWeapon(itemId, expectedRevision, operationId));
        }

        public bool InvokeFireWeapon(ReducerEventContext ctx, Reducer.FireWeapon args)
        {
            if (OnFireWeapon == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnFireWeapon(
                ctx,
                args.ItemId,
                args.ExpectedRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class FireWeapon : Reducer, IReducerArgs
        {
            [DataMember(Name = "item_id")]
            public string ItemId;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public FireWeapon(
                string ItemId,
                ulong ExpectedRevision,
                string OperationId
            )
            {
                this.ItemId = ItemId;
                this.ExpectedRevision = ExpectedRevision;
                this.OperationId = OperationId;
            }

            public FireWeapon()
            {
                this.ItemId = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "fire_weapon";
        }
    }
}
