// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InstallCargoHandlingFixtureHandler(ReducerEventContext ctx, string instanceId, ulong expectedInstanceRevision, string operationId);
        public event InstallCargoHandlingFixtureHandler? OnInstallCargoHandlingFixture;

        public void InstallCargoHandlingFixture(string instanceId, ulong expectedInstanceRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.InstallCargoHandlingFixture(instanceId, expectedInstanceRevision, operationId));
        }

        public bool InvokeInstallCargoHandlingFixture(ReducerEventContext ctx, Reducer.InstallCargoHandlingFixture args)
        {
            if (OnInstallCargoHandlingFixture == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInstallCargoHandlingFixture(
                ctx,
                args.InstanceId,
                args.ExpectedInstanceRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InstallCargoHandlingFixture : Reducer, IReducerArgs
        {
            [DataMember(Name = "instance_id")]
            public string InstanceId;
            [DataMember(Name = "expected_instance_revision")]
            public ulong ExpectedInstanceRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public InstallCargoHandlingFixture(
                string InstanceId,
                ulong ExpectedInstanceRevision,
                string OperationId
            )
            {
                this.InstanceId = InstanceId;
                this.ExpectedInstanceRevision = ExpectedInstanceRevision;
                this.OperationId = OperationId;
            }

            public InstallCargoHandlingFixture()
            {
                this.InstanceId = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "install_cargo_handling_fixture";
        }
    }
}
