// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveInventoryItemHandler(ReducerEventContext ctx, string itemId, string containerId, int x, int y, bool rotated, ulong expectedRevision, string operationId);
        public event MoveInventoryItemHandler? OnMoveInventoryItem;

        public void MoveInventoryItem(string itemId, string containerId, int x, int y, bool rotated, ulong expectedRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.MoveInventoryItem(itemId, containerId, x, y, rotated, expectedRevision, operationId));
        }

        public bool InvokeMoveInventoryItem(ReducerEventContext ctx, Reducer.MoveInventoryItem args)
        {
            if (OnMoveInventoryItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMoveInventoryItem(
                ctx,
                args.ItemId,
                args.ContainerId,
                args.X,
                args.Y,
                args.Rotated,
                args.ExpectedRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveInventoryItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "item_id")]
            public string ItemId;
            [DataMember(Name = "container_id")]
            public string ContainerId;
            [DataMember(Name = "x")]
            public int X;
            [DataMember(Name = "y")]
            public int Y;
            [DataMember(Name = "rotated")]
            public bool Rotated;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public MoveInventoryItem(
                string ItemId,
                string ContainerId,
                int X,
                int Y,
                bool Rotated,
                ulong ExpectedRevision,
                string OperationId
            )
            {
                this.ItemId = ItemId;
                this.ContainerId = ContainerId;
                this.X = X;
                this.Y = Y;
                this.Rotated = Rotated;
                this.ExpectedRevision = ExpectedRevision;
                this.OperationId = OperationId;
            }

            public MoveInventoryItem()
            {
                this.ItemId = "";
                this.ContainerId = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "move_inventory_item";
        }
    }
}
