// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveCargoCarrierHandler(ReducerEventContext ctx, string gridId, ulong expectedGridRevision, string operationId, string containerId, ulong expectedPlacementRevision, ulong expectedInventoryRevision, int originX, int originY, int originZ, byte quarterTurns);
        public event MoveCargoCarrierHandler? OnMoveCargoCarrier;

        public void MoveCargoCarrier(string gridId, ulong expectedGridRevision, string operationId, string containerId, ulong expectedPlacementRevision, ulong expectedInventoryRevision, int originX, int originY, int originZ, byte quarterTurns)
        {
            conn.InternalCallReducer(new Reducer.MoveCargoCarrier(gridId, expectedGridRevision, operationId, containerId, expectedPlacementRevision, expectedInventoryRevision, originX, originY, originZ, quarterTurns));
        }

        public bool InvokeMoveCargoCarrier(ReducerEventContext ctx, Reducer.MoveCargoCarrier args)
        {
            if (OnMoveCargoCarrier == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMoveCargoCarrier(
                ctx,
                args.GridId,
                args.ExpectedGridRevision,
                args.OperationId,
                args.ContainerId,
                args.ExpectedPlacementRevision,
                args.ExpectedInventoryRevision,
                args.OriginX,
                args.OriginY,
                args.OriginZ,
                args.QuarterTurns
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveCargoCarrier : Reducer, IReducerArgs
        {
            [DataMember(Name = "grid_id")]
            public string GridId;
            [DataMember(Name = "expected_grid_revision")]
            public ulong ExpectedGridRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;
            [DataMember(Name = "container_id")]
            public string ContainerId;
            [DataMember(Name = "expected_placement_revision")]
            public ulong ExpectedPlacementRevision;
            [DataMember(Name = "expected_inventory_revision")]
            public ulong ExpectedInventoryRevision;
            [DataMember(Name = "origin_x")]
            public int OriginX;
            [DataMember(Name = "origin_y")]
            public int OriginY;
            [DataMember(Name = "origin_z")]
            public int OriginZ;
            [DataMember(Name = "quarter_turns")]
            public byte QuarterTurns;

            public MoveCargoCarrier(
                string GridId,
                ulong ExpectedGridRevision,
                string OperationId,
                string ContainerId,
                ulong ExpectedPlacementRevision,
                ulong ExpectedInventoryRevision,
                int OriginX,
                int OriginY,
                int OriginZ,
                byte QuarterTurns
            )
            {
                this.GridId = GridId;
                this.ExpectedGridRevision = ExpectedGridRevision;
                this.OperationId = OperationId;
                this.ContainerId = ContainerId;
                this.ExpectedPlacementRevision = ExpectedPlacementRevision;
                this.ExpectedInventoryRevision = ExpectedInventoryRevision;
                this.OriginX = OriginX;
                this.OriginY = OriginY;
                this.OriginZ = OriginZ;
                this.QuarterTurns = QuarterTurns;
            }

            public MoveCargoCarrier()
            {
                this.GridId = "";
                this.OperationId = "";
                this.ContainerId = "";
            }

            string IReducerArgs.ReducerName => "move_cargo_carrier";
        }
    }
}
