// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void OperatorWipePlayerShipsHandler(ReducerEventContext ctx, string operationId, bool dryRun, uint expectedShips, uint expectedInstances, uint expectedCharacters);
        public event OperatorWipePlayerShipsHandler? OnOperatorWipePlayerShips;

        public void OperatorWipePlayerShips(string operationId, bool dryRun, uint expectedShips, uint expectedInstances, uint expectedCharacters)
        {
            conn.InternalCallReducer(new Reducer.OperatorWipePlayerShips(operationId, dryRun, expectedShips, expectedInstances, expectedCharacters));
        }

        public bool InvokeOperatorWipePlayerShips(ReducerEventContext ctx, Reducer.OperatorWipePlayerShips args)
        {
            if (OnOperatorWipePlayerShips == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnOperatorWipePlayerShips(
                ctx,
                args.OperationId,
                args.DryRun,
                args.ExpectedShips,
                args.ExpectedInstances,
                args.ExpectedCharacters
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class OperatorWipePlayerShips : Reducer, IReducerArgs
        {
            [DataMember(Name = "operation_id")]
            public string OperationId;
            [DataMember(Name = "dry_run")]
            public bool DryRun;
            [DataMember(Name = "expected_ships")]
            public uint ExpectedShips;
            [DataMember(Name = "expected_instances")]
            public uint ExpectedInstances;
            [DataMember(Name = "expected_characters")]
            public uint ExpectedCharacters;

            public OperatorWipePlayerShips(
                string OperationId,
                bool DryRun,
                uint ExpectedShips,
                uint ExpectedInstances,
                uint ExpectedCharacters
            )
            {
                this.OperationId = OperationId;
                this.DryRun = DryRun;
                this.ExpectedShips = ExpectedShips;
                this.ExpectedInstances = ExpectedInstances;
                this.ExpectedCharacters = ExpectedCharacters;
            }

            public OperatorWipePlayerShips()
            {
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "operator_wipe_player_ships";
        }
    }
}
