// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void OperatorSetDefinitionGrantHandler(ReducerEventContext ctx, string operationId, string principal, string kind, string capability, ulong expiresMicros, bool revoked);
        public event OperatorSetDefinitionGrantHandler? OnOperatorSetDefinitionGrant;

        public void OperatorSetDefinitionGrant(string operationId, string principal, string kind, string capability, ulong expiresMicros, bool revoked)
        {
            conn.InternalCallReducer(new Reducer.OperatorSetDefinitionGrant(operationId, principal, kind, capability, expiresMicros, revoked));
        }

        public bool InvokeOperatorSetDefinitionGrant(ReducerEventContext ctx, Reducer.OperatorSetDefinitionGrant args)
        {
            if (OnOperatorSetDefinitionGrant == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnOperatorSetDefinitionGrant(
                ctx,
                args.OperationId,
                args.Principal,
                args.Kind,
                args.Capability,
                args.ExpiresMicros,
                args.Revoked
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class OperatorSetDefinitionGrant : Reducer, IReducerArgs
        {
            [DataMember(Name = "operation_id")]
            public string OperationId;
            [DataMember(Name = "principal")]
            public string Principal;
            [DataMember(Name = "kind")]
            public string Kind;
            [DataMember(Name = "capability")]
            public string Capability;
            [DataMember(Name = "expires_micros")]
            public ulong ExpiresMicros;
            [DataMember(Name = "revoked")]
            public bool Revoked;

            public OperatorSetDefinitionGrant(
                string OperationId,
                string Principal,
                string Kind,
                string Capability,
                ulong ExpiresMicros,
                bool Revoked
            )
            {
                this.OperationId = OperationId;
                this.Principal = Principal;
                this.Kind = Kind;
                this.Capability = Capability;
                this.ExpiresMicros = ExpiresMicros;
                this.Revoked = Revoked;
            }

            public OperatorSetDefinitionGrant()
            {
                this.OperationId = "";
                this.Principal = "";
                this.Kind = "";
                this.Capability = "";
            }

            string IReducerArgs.ReducerName => "operator_set_definition_grant";
        }
    }
}
