// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void OperatorStockShipCargoHandler(ReducerEventContext ctx, string operationId, bool dryRun, string characterId, string shipId, string socketKey, string containerName, string definitionIdsJson);
        public event OperatorStockShipCargoHandler? OnOperatorStockShipCargo;

        public void OperatorStockShipCargo(string operationId, bool dryRun, string characterId, string shipId, string socketKey, string containerName, string definitionIdsJson)
        {
            conn.InternalCallReducer(new Reducer.OperatorStockShipCargo(operationId, dryRun, characterId, shipId, socketKey, containerName, definitionIdsJson));
        }

        public bool InvokeOperatorStockShipCargo(ReducerEventContext ctx, Reducer.OperatorStockShipCargo args)
        {
            if (OnOperatorStockShipCargo == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnOperatorStockShipCargo(
                ctx,
                args.OperationId,
                args.DryRun,
                args.CharacterId,
                args.ShipId,
                args.SocketKey,
                args.ContainerName,
                args.DefinitionIdsJson
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class OperatorStockShipCargo : Reducer, IReducerArgs
        {
            [DataMember(Name = "operation_id")]
            public string OperationId;
            [DataMember(Name = "dry_run")]
            public bool DryRun;
            [DataMember(Name = "character_id")]
            public string CharacterId;
            [DataMember(Name = "ship_id")]
            public string ShipId;
            [DataMember(Name = "socket_key")]
            public string SocketKey;
            [DataMember(Name = "container_name")]
            public string ContainerName;
            [DataMember(Name = "definition_ids_json")]
            public string DefinitionIdsJson;

            public OperatorStockShipCargo(
                string OperationId,
                bool DryRun,
                string CharacterId,
                string ShipId,
                string SocketKey,
                string ContainerName,
                string DefinitionIdsJson
            )
            {
                this.OperationId = OperationId;
                this.DryRun = DryRun;
                this.CharacterId = CharacterId;
                this.ShipId = ShipId;
                this.SocketKey = SocketKey;
                this.ContainerName = ContainerName;
                this.DefinitionIdsJson = DefinitionIdsJson;
            }

            public OperatorStockShipCargo()
            {
                this.OperationId = "";
                this.CharacterId = "";
                this.ShipId = "";
                this.SocketKey = "";
                this.ContainerName = "";
                this.DefinitionIdsJson = "";
            }

            string IReducerArgs.ReducerName => "operator_stock_ship_cargo";
        }
    }
}
