// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void OperatorReplacePrefabShipHandler(ReducerEventContext ctx, string operationId, bool dryRun, string characterId, string shipId, string expectedSourceBlueprintSha256, ulong expectedInstanceRevision, string targetPrefabId, string expectedTargetCatalogRevision, string expectedTargetBlueprintSha256, bool discardShipStorage);
        public event OperatorReplacePrefabShipHandler? OnOperatorReplacePrefabShip;

        public void OperatorReplacePrefabShip(string operationId, bool dryRun, string characterId, string shipId, string expectedSourceBlueprintSha256, ulong expectedInstanceRevision, string targetPrefabId, string expectedTargetCatalogRevision, string expectedTargetBlueprintSha256, bool discardShipStorage)
        {
            conn.InternalCallReducer(new Reducer.OperatorReplacePrefabShip(operationId, dryRun, characterId, shipId, expectedSourceBlueprintSha256, expectedInstanceRevision, targetPrefabId, expectedTargetCatalogRevision, expectedTargetBlueprintSha256, discardShipStorage));
        }

        public bool InvokeOperatorReplacePrefabShip(ReducerEventContext ctx, Reducer.OperatorReplacePrefabShip args)
        {
            if (OnOperatorReplacePrefabShip == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnOperatorReplacePrefabShip(
                ctx,
                args.OperationId,
                args.DryRun,
                args.CharacterId,
                args.ShipId,
                args.ExpectedSourceBlueprintSha256,
                args.ExpectedInstanceRevision,
                args.TargetPrefabId,
                args.ExpectedTargetCatalogRevision,
                args.ExpectedTargetBlueprintSha256,
                args.DiscardShipStorage
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class OperatorReplacePrefabShip : Reducer, IReducerArgs
        {
            [DataMember(Name = "operation_id")]
            public string OperationId;
            [DataMember(Name = "dry_run")]
            public bool DryRun;
            [DataMember(Name = "character_id")]
            public string CharacterId;
            [DataMember(Name = "ship_id")]
            public string ShipId;
            [DataMember(Name = "expected_source_blueprint_sha_256")]
            public string ExpectedSourceBlueprintSha256;
            [DataMember(Name = "expected_instance_revision")]
            public ulong ExpectedInstanceRevision;
            [DataMember(Name = "target_prefab_id")]
            public string TargetPrefabId;
            [DataMember(Name = "expected_target_catalog_revision")]
            public string ExpectedTargetCatalogRevision;
            [DataMember(Name = "expected_target_blueprint_sha_256")]
            public string ExpectedTargetBlueprintSha256;
            [DataMember(Name = "discard_ship_storage")]
            public bool DiscardShipStorage;

            public OperatorReplacePrefabShip(
                string OperationId,
                bool DryRun,
                string CharacterId,
                string ShipId,
                string ExpectedSourceBlueprintSha256,
                ulong ExpectedInstanceRevision,
                string TargetPrefabId,
                string ExpectedTargetCatalogRevision,
                string ExpectedTargetBlueprintSha256,
                bool DiscardShipStorage
            )
            {
                this.OperationId = OperationId;
                this.DryRun = DryRun;
                this.CharacterId = CharacterId;
                this.ShipId = ShipId;
                this.ExpectedSourceBlueprintSha256 = ExpectedSourceBlueprintSha256;
                this.ExpectedInstanceRevision = ExpectedInstanceRevision;
                this.TargetPrefabId = TargetPrefabId;
                this.ExpectedTargetCatalogRevision = ExpectedTargetCatalogRevision;
                this.ExpectedTargetBlueprintSha256 = ExpectedTargetBlueprintSha256;
                this.DiscardShipStorage = DiscardShipStorage;
            }

            public OperatorReplacePrefabShip()
            {
                this.OperationId = "";
                this.CharacterId = "";
                this.ShipId = "";
                this.ExpectedSourceBlueprintSha256 = "";
                this.TargetPrefabId = "";
                this.ExpectedTargetCatalogRevision = "";
                this.ExpectedTargetBlueprintSha256 = "";
            }

            string IReducerArgs.ReducerName => "operator_replace_prefab_ship";
        }
    }
}
