// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void OperatorImportContentSeedHandler(ReducerEventContext ctx, string operationId, string kind, bool dryRun);
        public event OperatorImportContentSeedHandler? OnOperatorImportContentSeed;

        public void OperatorImportContentSeed(string operationId, string kind, bool dryRun)
        {
            conn.InternalCallReducer(new Reducer.OperatorImportContentSeed(operationId, kind, dryRun));
        }

        public bool InvokeOperatorImportContentSeed(ReducerEventContext ctx, Reducer.OperatorImportContentSeed args)
        {
            if (OnOperatorImportContentSeed == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnOperatorImportContentSeed(
                ctx,
                args.OperationId,
                args.Kind,
                args.DryRun
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class OperatorImportContentSeed : Reducer, IReducerArgs
        {
            [DataMember(Name = "operation_id")]
            public string OperationId;
            [DataMember(Name = "kind")]
            public string Kind;
            [DataMember(Name = "dry_run")]
            public bool DryRun;

            public OperatorImportContentSeed(
                string OperationId,
                string Kind,
                bool DryRun
            )
            {
                this.OperationId = OperationId;
                this.Kind = Kind;
                this.DryRun = DryRun;
            }

            public OperatorImportContentSeed()
            {
                this.OperationId = "";
                this.Kind = "";
            }

            string IReducerArgs.ReducerName => "operator_import_content_seed";
        }
    }
}
