// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void OperatorAssignPrefabShipHandler(ReducerEventContext ctx, string operationId, string characterId, string prefabId, string expectedCatalogRevision, string spawnPoseJson, string expectedCharacterShipId, bool allowLegacy);
        public event OperatorAssignPrefabShipHandler? OnOperatorAssignPrefabShip;

        public void OperatorAssignPrefabShip(string operationId, string characterId, string prefabId, string expectedCatalogRevision, string spawnPoseJson, string expectedCharacterShipId, bool allowLegacy)
        {
            conn.InternalCallReducer(new Reducer.OperatorAssignPrefabShip(operationId, characterId, prefabId, expectedCatalogRevision, spawnPoseJson, expectedCharacterShipId, allowLegacy));
        }

        public bool InvokeOperatorAssignPrefabShip(ReducerEventContext ctx, Reducer.OperatorAssignPrefabShip args)
        {
            if (OnOperatorAssignPrefabShip == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnOperatorAssignPrefabShip(
                ctx,
                args.OperationId,
                args.CharacterId,
                args.PrefabId,
                args.ExpectedCatalogRevision,
                args.SpawnPoseJson,
                args.ExpectedCharacterShipId,
                args.AllowLegacy
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class OperatorAssignPrefabShip : Reducer, IReducerArgs
        {
            [DataMember(Name = "operation_id")]
            public string OperationId;
            [DataMember(Name = "character_id")]
            public string CharacterId;
            [DataMember(Name = "prefab_id")]
            public string PrefabId;
            [DataMember(Name = "expected_catalog_revision")]
            public string ExpectedCatalogRevision;
            [DataMember(Name = "spawn_pose_json")]
            public string SpawnPoseJson;
            [DataMember(Name = "expected_character_ship_id")]
            public string ExpectedCharacterShipId;
            [DataMember(Name = "allow_legacy")]
            public bool AllowLegacy;

            public OperatorAssignPrefabShip(
                string OperationId,
                string CharacterId,
                string PrefabId,
                string ExpectedCatalogRevision,
                string SpawnPoseJson,
                string ExpectedCharacterShipId,
                bool AllowLegacy
            )
            {
                this.OperationId = OperationId;
                this.CharacterId = CharacterId;
                this.PrefabId = PrefabId;
                this.ExpectedCatalogRevision = ExpectedCatalogRevision;
                this.SpawnPoseJson = SpawnPoseJson;
                this.ExpectedCharacterShipId = ExpectedCharacterShipId;
                this.AllowLegacy = AllowLegacy;
            }

            public OperatorAssignPrefabShip()
            {
                this.OperationId = "";
                this.CharacterId = "";
                this.PrefabId = "";
                this.ExpectedCatalogRevision = "";
                this.SpawnPoseJson = "";
                this.ExpectedCharacterShipId = "";
            }

            string IReducerArgs.ReducerName => "operator_assign_prefab_ship";
        }
    }
}
