// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PublishConstructionBlueprintHandler(ReducerEventContext ctx, string workspaceId, string draftId, ulong expectedRevision, string operationId);
        public event PublishConstructionBlueprintHandler? OnPublishConstructionBlueprint;

        public void PublishConstructionBlueprint(string workspaceId, string draftId, ulong expectedRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.PublishConstructionBlueprint(workspaceId, draftId, expectedRevision, operationId));
        }

        public bool InvokePublishConstructionBlueprint(ReducerEventContext ctx, Reducer.PublishConstructionBlueprint args)
        {
            if (OnPublishConstructionBlueprint == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPublishConstructionBlueprint(
                ctx,
                args.WorkspaceId,
                args.DraftId,
                args.ExpectedRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PublishConstructionBlueprint : Reducer, IReducerArgs
        {
            [DataMember(Name = "workspace_id")]
            public string WorkspaceId;
            [DataMember(Name = "draft_id")]
            public string DraftId;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public PublishConstructionBlueprint(
                string WorkspaceId,
                string DraftId,
                ulong ExpectedRevision,
                string OperationId
            )
            {
                this.WorkspaceId = WorkspaceId;
                this.DraftId = DraftId;
                this.ExpectedRevision = ExpectedRevision;
                this.OperationId = OperationId;
            }

            public PublishConstructionBlueprint()
            {
                this.WorkspaceId = "";
                this.DraftId = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "publish_construction_blueprint";
        }
    }
}
