// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RefreshDefinitionUsageHandler(ReducerEventContext ctx, string kind);
        public event RefreshDefinitionUsageHandler? OnRefreshDefinitionUsage;

        public void RefreshDefinitionUsage(string kind)
        {
            conn.InternalCallReducer(new Reducer.RefreshDefinitionUsage(kind));
        }

        public bool InvokeRefreshDefinitionUsage(ReducerEventContext ctx, Reducer.RefreshDefinitionUsage args)
        {
            if (OnRefreshDefinitionUsage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRefreshDefinitionUsage(
                ctx,
                args.Kind
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RefreshDefinitionUsage : Reducer, IReducerArgs
        {
            [DataMember(Name = "kind")]
            public string Kind;

            public RefreshDefinitionUsage(string Kind)
            {
                this.Kind = Kind;
            }

            public RefreshDefinitionUsage()
            {
                this.Kind = "";
            }

            string IReducerArgs.ReducerName => "refresh_definition_usage";
        }
    }
}
