// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RenameShipHandler(ReducerEventContext ctx, string shipId, ulong expectedRevision, string operationId, string name);
        public event RenameShipHandler? OnRenameShip;

        public void RenameShip(string shipId, ulong expectedRevision, string operationId, string name)
        {
            conn.InternalCallReducer(new Reducer.RenameShip(shipId, expectedRevision, operationId, name));
        }

        public bool InvokeRenameShip(ReducerEventContext ctx, Reducer.RenameShip args)
        {
            if (OnRenameShip == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRenameShip(
                ctx,
                args.ShipId,
                args.ExpectedRevision,
                args.OperationId,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RenameShip : Reducer, IReducerArgs
        {
            [DataMember(Name = "ship_id")]
            public string ShipId;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;
            [DataMember(Name = "name")]
            public string Name;

            public RenameShip(
                string ShipId,
                ulong ExpectedRevision,
                string OperationId,
                string Name
            )
            {
                this.ShipId = ShipId;
                this.ExpectedRevision = ExpectedRevision;
                this.OperationId = OperationId;
                this.Name = Name;
            }

            public RenameShip()
            {
                this.ShipId = "";
                this.OperationId = "";
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "rename_ship";
        }
    }
}
