// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RetireDefinitionHandler(ReducerEventContext ctx, string kind, string definitionId, ulong revision, ulong expectedRevision, string operationId);
        public event RetireDefinitionHandler? OnRetireDefinition;

        public void RetireDefinition(string kind, string definitionId, ulong revision, ulong expectedRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.RetireDefinition(kind, definitionId, revision, expectedRevision, operationId));
        }

        public bool InvokeRetireDefinition(ReducerEventContext ctx, Reducer.RetireDefinition args)
        {
            if (OnRetireDefinition == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRetireDefinition(
                ctx,
                args.Kind,
                args.DefinitionId,
                args.Revision,
                args.ExpectedRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RetireDefinition : Reducer, IReducerArgs
        {
            [DataMember(Name = "kind")]
            public string Kind;
            [DataMember(Name = "definition_id")]
            public string DefinitionId;
            [DataMember(Name = "revision")]
            public ulong Revision;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public RetireDefinition(
                string Kind,
                string DefinitionId,
                ulong Revision,
                ulong ExpectedRevision,
                string OperationId
            )
            {
                this.Kind = Kind;
                this.DefinitionId = DefinitionId;
                this.Revision = Revision;
                this.ExpectedRevision = ExpectedRevision;
                this.OperationId = OperationId;
            }

            public RetireDefinition()
            {
                this.Kind = "";
                this.DefinitionId = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "retire_definition";
        }
    }
}
