// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReturnShipPassengerHandler(ReducerEventContext ctx, string expectedVisitId, ulong expectedRevision, string operationId);
        public event ReturnShipPassengerHandler? OnReturnShipPassenger;

        public void ReturnShipPassenger(string expectedVisitId, ulong expectedRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.ReturnShipPassenger(expectedVisitId, expectedRevision, operationId));
        }

        public bool InvokeReturnShipPassenger(ReducerEventContext ctx, Reducer.ReturnShipPassenger args)
        {
            if (OnReturnShipPassenger == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReturnShipPassenger(
                ctx,
                args.ExpectedVisitId,
                args.ExpectedRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReturnShipPassenger : Reducer, IReducerArgs
        {
            [DataMember(Name = "expected_visit_id")]
            public string ExpectedVisitId;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public ReturnShipPassenger(
                string ExpectedVisitId,
                ulong ExpectedRevision,
                string OperationId
            )
            {
                this.ExpectedVisitId = ExpectedVisitId;
                this.ExpectedRevision = ExpectedRevision;
                this.OperationId = OperationId;
            }

            public ReturnShipPassenger()
            {
                this.ExpectedVisitId = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "return_ship_passenger";
        }
    }
}
