// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SaveDefinitionDraftHandler(ReducerEventContext ctx, string kind, string definitionId, string payloadJson, ulong expectedRevision, string operationId);
        public event SaveDefinitionDraftHandler? OnSaveDefinitionDraft;

        public void SaveDefinitionDraft(string kind, string definitionId, string payloadJson, ulong expectedRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.SaveDefinitionDraft(kind, definitionId, payloadJson, expectedRevision, operationId));
        }

        public bool InvokeSaveDefinitionDraft(ReducerEventContext ctx, Reducer.SaveDefinitionDraft args)
        {
            if (OnSaveDefinitionDraft == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSaveDefinitionDraft(
                ctx,
                args.Kind,
                args.DefinitionId,
                args.PayloadJson,
                args.ExpectedRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SaveDefinitionDraft : Reducer, IReducerArgs
        {
            [DataMember(Name = "kind")]
            public string Kind;
            [DataMember(Name = "definition_id")]
            public string DefinitionId;
            [DataMember(Name = "payload_json")]
            public string PayloadJson;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public SaveDefinitionDraft(
                string Kind,
                string DefinitionId,
                string PayloadJson,
                ulong ExpectedRevision,
                string OperationId
            )
            {
                this.Kind = Kind;
                this.DefinitionId = DefinitionId;
                this.PayloadJson = PayloadJson;
                this.ExpectedRevision = ExpectedRevision;
                this.OperationId = OperationId;
            }

            public SaveDefinitionDraft()
            {
                this.Kind = "";
                this.DefinitionId = "";
                this.PayloadJson = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "save_definition_draft";
        }
    }
}
