// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SaveConstructionDraftHandler(ReducerEventContext ctx, string workspaceId, string draftId, string documentJson, ulong expectedRevision, string operationId);
        public event SaveConstructionDraftHandler? OnSaveConstructionDraft;

        public void SaveConstructionDraft(string workspaceId, string draftId, string documentJson, ulong expectedRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.SaveConstructionDraft(workspaceId, draftId, documentJson, expectedRevision, operationId));
        }

        public bool InvokeSaveConstructionDraft(ReducerEventContext ctx, Reducer.SaveConstructionDraft args)
        {
            if (OnSaveConstructionDraft == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSaveConstructionDraft(
                ctx,
                args.WorkspaceId,
                args.DraftId,
                args.DocumentJson,
                args.ExpectedRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SaveConstructionDraft : Reducer, IReducerArgs
        {
            [DataMember(Name = "workspace_id")]
            public string WorkspaceId;
            [DataMember(Name = "draft_id")]
            public string DraftId;
            [DataMember(Name = "document_json")]
            public string DocumentJson;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public SaveConstructionDraft(
                string WorkspaceId,
                string DraftId,
                string DocumentJson,
                ulong ExpectedRevision,
                string OperationId
            )
            {
                this.WorkspaceId = WorkspaceId;
                this.DraftId = DraftId;
                this.DocumentJson = DocumentJson;
                this.ExpectedRevision = ExpectedRevision;
                this.OperationId = OperationId;
            }

            public SaveConstructionDraft()
            {
                this.WorkspaceId = "";
                this.DraftId = "";
                this.DocumentJson = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "save_construction_draft";
        }
    }
}
