// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetCharacterAppearanceHandler(ReducerEventContext ctx, string appearanceJson, ulong expectedRevision, string operationId);
        public event SetCharacterAppearanceHandler? OnSetCharacterAppearance;

        public void SetCharacterAppearance(string appearanceJson, ulong expectedRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.SetCharacterAppearance(appearanceJson, expectedRevision, operationId));
        }

        public bool InvokeSetCharacterAppearance(ReducerEventContext ctx, Reducer.SetCharacterAppearance args)
        {
            if (OnSetCharacterAppearance == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetCharacterAppearance(
                ctx,
                args.AppearanceJson,
                args.ExpectedRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetCharacterAppearance : Reducer, IReducerArgs
        {
            [DataMember(Name = "appearance_json")]
            public string AppearanceJson;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public SetCharacterAppearance(
                string AppearanceJson,
                ulong ExpectedRevision,
                string OperationId
            )
            {
                this.AppearanceJson = AppearanceJson;
                this.ExpectedRevision = ExpectedRevision;
                this.OperationId = OperationId;
            }

            public SetCharacterAppearance()
            {
                this.AppearanceJson = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "set_character_appearance";
        }
    }
}
