// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TakeAllInventoryItemsHandler(ReducerEventContext ctx, string containerId, ulong expectedRevision, string operationId);
        public event TakeAllInventoryItemsHandler? OnTakeAllInventoryItems;

        public void TakeAllInventoryItems(string containerId, ulong expectedRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.TakeAllInventoryItems(containerId, expectedRevision, operationId));
        }

        public bool InvokeTakeAllInventoryItems(ReducerEventContext ctx, Reducer.TakeAllInventoryItems args)
        {
            if (OnTakeAllInventoryItems == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTakeAllInventoryItems(
                ctx,
                args.ContainerId,
                args.ExpectedRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TakeAllInventoryItems : Reducer, IReducerArgs
        {
            [DataMember(Name = "container_id")]
            public string ContainerId;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public TakeAllInventoryItems(
                string ContainerId,
                ulong ExpectedRevision,
                string OperationId
            )
            {
                this.ContainerId = ContainerId;
                this.ExpectedRevision = ExpectedRevision;
                this.OperationId = OperationId;
            }

            public TakeAllInventoryItems()
            {
                this.ContainerId = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "take_all_inventory_items";
        }
    }
}
