// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TransferInventoryItemHandler(ReducerEventContext ctx, string itemId, string containerId, ulong expectedRevision, string operationId);
        public event TransferInventoryItemHandler? OnTransferInventoryItem;

        public void TransferInventoryItem(string itemId, string containerId, ulong expectedRevision, string operationId)
        {
            conn.InternalCallReducer(new Reducer.TransferInventoryItem(itemId, containerId, expectedRevision, operationId));
        }

        public bool InvokeTransferInventoryItem(ReducerEventContext ctx, Reducer.TransferInventoryItem args)
        {
            if (OnTransferInventoryItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTransferInventoryItem(
                ctx,
                args.ItemId,
                args.ContainerId,
                args.ExpectedRevision,
                args.OperationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TransferInventoryItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "item_id")]
            public string ItemId;
            [DataMember(Name = "container_id")]
            public string ContainerId;
            [DataMember(Name = "expected_revision")]
            public ulong ExpectedRevision;
            [DataMember(Name = "operation_id")]
            public string OperationId;

            public TransferInventoryItem(
                string ItemId,
                string ContainerId,
                ulong ExpectedRevision,
                string OperationId
            )
            {
                this.ItemId = ItemId;
                this.ContainerId = ContainerId;
                this.ExpectedRevision = ExpectedRevision;
                this.OperationId = OperationId;
            }

            public TransferInventoryItem()
            {
                this.ItemId = "";
                this.ContainerId = "";
                this.OperationId = "";
            }

            string IReducerArgs.ReducerName => "transfer_inventory_item";
        }
    }
}
