// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ActuatorOutput
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "actuator_id")]
        public string ActuatorId;
        [DataMember(Name = "throttle")]
        public double Throttle;
        [DataMember(Name = "tick")]
        public ulong Tick;

        public ActuatorOutput(
            string Id,
            string ShipId,
            string ActuatorId,
            double Throttle,
            ulong Tick
        )
        {
            this.Id = Id;
            this.ShipId = ShipId;
            this.ActuatorId = ActuatorId;
            this.Throttle = Throttle;
            this.Tick = Tick;
        }

        public ActuatorOutput()
        {
            this.Id = "";
            this.ShipId = "";
            this.ActuatorId = "";
        }
    }
}
