// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AuthoredFlightActuator
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "placed_object_id")]
        public string PlacedObjectId;
        [DataMember(Name = "x")]
        public double X;
        [DataMember(Name = "y")]
        public double Y;
        [DataMember(Name = "nozzle_x")]
        public double NozzleX;
        [DataMember(Name = "nozzle_y")]
        public double NozzleY;
        [DataMember(Name = "height")]
        public double Height;
        [DataMember(Name = "exhaust_x")]
        public double ExhaustX;
        [DataMember(Name = "exhaust_y")]
        public double ExhaustY;
        [DataMember(Name = "throttle")]
        public double Throttle;

        public AuthoredFlightActuator(
            string Id,
            string ShipId,
            string PlacedObjectId,
            double X,
            double Y,
            double NozzleX,
            double NozzleY,
            double Height,
            double ExhaustX,
            double ExhaustY,
            double Throttle
        )
        {
            this.Id = Id;
            this.ShipId = ShipId;
            this.PlacedObjectId = PlacedObjectId;
            this.X = X;
            this.Y = Y;
            this.NozzleX = NozzleX;
            this.NozzleY = NozzleY;
            this.Height = Height;
            this.ExhaustX = ExhaustX;
            this.ExhaustY = ExhaustY;
            this.Throttle = Throttle;
        }

        public AuthoredFlightActuator()
        {
            this.Id = "";
            this.ShipId = "";
            this.PlacedObjectId = "";
        }
    }
}
