// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AuthSession
    {
        [DataMember(Name = "connection_id")]
        public string ConnectionId;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "game")]
        public bool Game;
        [DataMember(Name = "expires_micros")]
        public ulong ExpiresMicros;

        public AuthSession(
            string ConnectionId,
            SpacetimeDB.Identity Owner,
            string Kind,
            bool Game,
            ulong ExpiresMicros
        )
        {
            this.ConnectionId = ConnectionId;
            this.Owner = Owner;
            this.Kind = Kind;
            this.Game = Game;
            this.ExpiresMicros = ExpiresMicros;
        }

        public AuthSession()
        {
            this.ConnectionId = "";
            this.Kind = "";
        }
    }
}
