// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BeginConstructionTraversal
    {
        [DataMember(Name = "link_id")]
        public string LinkId;
        [DataMember(Name = "expected_visit_id")]
        public string ExpectedVisitId;
        [DataMember(Name = "expected_location_revision")]
        public ulong ExpectedLocationRevision;
        [DataMember(Name = "expected_instance_revision")]
        public ulong ExpectedInstanceRevision;
        [DataMember(Name = "expected_link_revision")]
        public ulong ExpectedLinkRevision;
        [DataMember(Name = "operation_id")]
        public string OperationId;

        public BeginConstructionTraversal(
            string LinkId,
            string ExpectedVisitId,
            ulong ExpectedLocationRevision,
            ulong ExpectedInstanceRevision,
            ulong ExpectedLinkRevision,
            string OperationId
        )
        {
            this.LinkId = LinkId;
            this.ExpectedVisitId = ExpectedVisitId;
            this.ExpectedLocationRevision = ExpectedLocationRevision;
            this.ExpectedInstanceRevision = ExpectedInstanceRevision;
            this.ExpectedLinkRevision = ExpectedLinkRevision;
            this.OperationId = OperationId;
        }

        public BeginConstructionTraversal()
        {
            this.LinkId = "";
            this.ExpectedVisitId = "";
            this.OperationId = "";
        }
    }
}
