// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BodyWorldMotion
    {
        [DataMember(Name = "body_id")]
        public string BodyId;
        [DataMember(Name = "system_id")]
        public string SystemId;
        [DataMember(Name = "x")]
        public double X;
        [DataMember(Name = "y")]
        public double Y;
        [DataMember(Name = "vx")]
        public double Vx;
        [DataMember(Name = "vy")]
        public double Vy;
        [DataMember(Name = "heading")]
        public double Heading;
        [DataMember(Name = "omega")]
        public double Omega;
        [DataMember(Name = "server_tick")]
        public ulong ServerTick;
        [DataMember(Name = "cell_x")]
        public long CellX;
        [DataMember(Name = "cell_y")]
        public long CellY;

        public BodyWorldMotion(
            string BodyId,
            string SystemId,
            double X,
            double Y,
            double Vx,
            double Vy,
            double Heading,
            double Omega,
            ulong ServerTick,
            long CellX,
            long CellY
        )
        {
            this.BodyId = BodyId;
            this.SystemId = SystemId;
            this.X = X;
            this.Y = Y;
            this.Vx = Vx;
            this.Vy = Vy;
            this.Heading = Heading;
            this.Omega = Omega;
            this.ServerTick = ServerTick;
            this.CellX = CellX;
            this.CellY = CellY;
        }

        public BodyWorldMotion()
        {
            this.BodyId = "";
            this.SystemId = "";
        }
    }
}
