// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CelestialMigrationReceipt
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "status")]
        public string Status;
        [DataMember(Name = "reason")]
        public string Reason;
        [DataMember(Name = "before_json")]
        public string BeforeJson;
        [DataMember(Name = "after_sha_256")]
        public string AfterSha256;
        [DataMember(Name = "created_micros")]
        public ulong CreatedMicros;

        public CelestialMigrationReceipt(
            string Id,
            string Status,
            string Reason,
            string BeforeJson,
            string AfterSha256,
            ulong CreatedMicros
        )
        {
            this.Id = Id;
            this.Status = Status;
            this.Reason = Reason;
            this.BeforeJson = BeforeJson;
            this.AfterSha256 = AfterSha256;
            this.CreatedMicros = CreatedMicros;
        }

        public CelestialMigrationReceipt()
        {
            this.Id = "";
            this.Status = "";
            this.Reason = "";
            this.BeforeJson = "";
            this.AfterSha256 = "";
        }
    }
}
