// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ChangeShipFlightFitting
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "fitting_id")]
        public string FittingId;
        [DataMember(Name = "action")]
        public string Action;
        [DataMember(Name = "expected_revision")]
        public ulong ExpectedRevision;
        [DataMember(Name = "expected_fitting_revision")]
        public ulong ExpectedFittingRevision;
        [DataMember(Name = "operation_id")]
        public string OperationId;

        public ChangeShipFlightFitting(
            string ShipId,
            string FittingId,
            string Action,
            ulong ExpectedRevision,
            ulong ExpectedFittingRevision,
            string OperationId
        )
        {
            this.ShipId = ShipId;
            this.FittingId = FittingId;
            this.Action = Action;
            this.ExpectedRevision = ExpectedRevision;
            this.ExpectedFittingRevision = ExpectedFittingRevision;
            this.OperationId = OperationId;
        }

        public ChangeShipFlightFitting()
        {
            this.ShipId = "";
            this.FittingId = "";
            this.Action = "";
            this.OperationId = "";
        }
    }
}
