// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CharacterVitalsStatus
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "health")]
        public double Health;
        [DataMember(Name = "max_health")]
        public double MaxHealth;
        [DataMember(Name = "state")]
        public string State;
        [DataMember(Name = "downed_until_micros")]
        public ulong DownedUntilMicros;
        [DataMember(Name = "hit_sequence")]
        public ulong HitSequence;
        [DataMember(Name = "last_hit_damage")]
        public double LastHitDamage;

        public CharacterVitalsStatus(
            string CharacterId,
            double Health,
            double MaxHealth,
            string State,
            ulong DownedUntilMicros,
            ulong HitSequence,
            double LastHitDamage
        )
        {
            this.CharacterId = CharacterId;
            this.Health = Health;
            this.MaxHealth = MaxHealth;
            this.State = State;
            this.DownedUntilMicros = DownedUntilMicros;
            this.HitSequence = HitSequence;
            this.LastHitDamage = LastHitDamage;
        }

        public CharacterVitalsStatus()
        {
            this.CharacterId = "";
            this.State = "";
        }
    }
}
