// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CharacterVitals
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "health")]
        public double Health;
        [DataMember(Name = "max_health")]
        public double MaxHealth;
        [DataMember(Name = "state")]
        public string State;
        [DataMember(Name = "last_damage_micros")]
        public ulong LastDamageMicros;
        [DataMember(Name = "downed_until_micros")]
        public ulong DownedUntilMicros;
        [DataMember(Name = "checkpoint_micros")]
        public ulong CheckpointMicros;
        [DataMember(Name = "hit_sequence")]
        public ulong HitSequence;
        [DataMember(Name = "last_hit_damage")]
        public double LastHitDamage;

        public CharacterVitals(
            string CharacterId,
            double Health,
            double MaxHealth,
            string State,
            ulong LastDamageMicros,
            ulong DownedUntilMicros,
            ulong CheckpointMicros,
            ulong HitSequence,
            double LastHitDamage
        )
        {
            this.CharacterId = CharacterId;
            this.Health = Health;
            this.MaxHealth = MaxHealth;
            this.State = State;
            this.LastDamageMicros = LastDamageMicros;
            this.DownedUntilMicros = DownedUntilMicros;
            this.CheckpointMicros = CheckpointMicros;
            this.HitSequence = HitSequence;
            this.LastHitDamage = LastHitDamage;
        }

        public CharacterVitals()
        {
            this.CharacterId = "";
            this.State = "";
        }
    }
}
