// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ClaimCharacterArmory
    {
        [DataMember(Name = "expected_revision")]
        public ulong ExpectedRevision;
        [DataMember(Name = "operation_id")]
        public string OperationId;

        public ClaimCharacterArmory(
            ulong ExpectedRevision,
            string OperationId
        )
        {
            this.ExpectedRevision = ExpectedRevision;
            this.OperationId = OperationId;
        }

        public ClaimCharacterArmory()
        {
            this.OperationId = "";
        }
    }
}
