// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CombatImpact
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "item_id")]
        public string ItemId;
        [DataMember(Name = "shot_sequence")]
        public ulong ShotSequence;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "x")]
        public double X;
        [DataMember(Name = "y")]
        public double Y;
        [DataMember(Name = "distance_m")]
        public double DistanceM;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "target_id")]
        public string TargetId;
        [DataMember(Name = "created_micros")]
        public ulong CreatedMicros;
        [DataMember(Name = "damage")]
        public double Damage;
        [DataMember(Name = "target_state")]
        public string TargetState;
        [DataMember(Name = "target_hp")]
        public double TargetHp;
        [DataMember(Name = "target_max_hp")]
        public double TargetMaxHp;

        public CombatImpact(
            string CharacterId,
            string ItemId,
            ulong ShotSequence,
            string ShipId,
            double X,
            double Y,
            double DistanceM,
            string Kind,
            string TargetId,
            ulong CreatedMicros,
            double Damage,
            string TargetState,
            double TargetHp,
            double TargetMaxHp
        )
        {
            this.CharacterId = CharacterId;
            this.ItemId = ItemId;
            this.ShotSequence = ShotSequence;
            this.ShipId = ShipId;
            this.X = X;
            this.Y = Y;
            this.DistanceM = DistanceM;
            this.Kind = Kind;
            this.TargetId = TargetId;
            this.CreatedMicros = CreatedMicros;
            this.Damage = Damage;
            this.TargetState = TargetState;
            this.TargetHp = TargetHp;
            this.TargetMaxHp = TargetMaxHp;
        }

        public CombatImpact()
        {
            this.CharacterId = "";
            this.ItemId = "";
            this.ShipId = "";
            this.Kind = "";
            this.TargetId = "";
            this.TargetState = "";
        }
    }
}
