// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CombatStatus
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "aim_active")]
        public bool AimActive;
        [DataMember(Name = "aim_angle")]
        public double AimAngle;
        [DataMember(Name = "weapon_item_id")]
        public string WeaponItemId;
        [DataMember(Name = "weapon_definition_id")]
        public string WeaponDefinitionId;
        [DataMember(Name = "energy")]
        public double Energy;
        [DataMember(Name = "capacity")]
        public double Capacity;
        [DataMember(Name = "shot_cost")]
        public double ShotCost;
        [DataMember(Name = "cooldown_ms")]
        public uint CooldownMs;
        [DataMember(Name = "range_meters")]
        public double RangeMeters;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "shot_sequence")]
        public ulong ShotSequence;
        [DataMember(Name = "last_shot_angle")]
        public double LastShotAngle;

        public CombatStatus(
            string CharacterId,
            bool AimActive,
            double AimAngle,
            string WeaponItemId,
            string WeaponDefinitionId,
            double Energy,
            double Capacity,
            double ShotCost,
            uint CooldownMs,
            double RangeMeters,
            ulong Revision,
            ulong ShotSequence,
            double LastShotAngle
        )
        {
            this.CharacterId = CharacterId;
            this.AimActive = AimActive;
            this.AimAngle = AimAngle;
            this.WeaponItemId = WeaponItemId;
            this.WeaponDefinitionId = WeaponDefinitionId;
            this.Energy = Energy;
            this.Capacity = Capacity;
            this.ShotCost = ShotCost;
            this.CooldownMs = CooldownMs;
            this.RangeMeters = RangeMeters;
            this.Revision = Revision;
            this.ShotSequence = ShotSequence;
            this.LastShotAngle = LastShotAngle;
        }

        public CombatStatus()
        {
            this.CharacterId = "";
            this.WeaponItemId = "";
            this.WeaponDefinitionId = "";
        }
    }
}
