// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConnectionPresence
    {
        [DataMember(Name = "connection_id")]
        public string ConnectionId;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;

        public ConnectionPresence(
            string ConnectionId,
            SpacetimeDB.Identity Owner
        )
        {
            this.ConnectionId = ConnectionId;
            this.Owner = Owner;
        }

        public ConnectionPresence()
        {
            this.ConnectionId = "";
        }
    }
}
