// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionAtmosphereClock
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "tick")]
        public ulong Tick;
        [DataMember(Name = "last_schedule_micros")]
        public ulong LastScheduleMicros;

        public ConstructionAtmosphereClock(
            string Id,
            ulong Tick,
            ulong LastScheduleMicros
        )
        {
            this.Id = Id;
            this.Tick = Tick;
            this.LastScheduleMicros = LastScheduleMicros;
        }

        public ConstructionAtmosphereClock()
        {
            this.Id = "";
        }
    }
}
