// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionNativePressureCompartment
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "volume_m_3")]
        public double VolumeM3;
        [DataMember(Name = "pressure_pa")]
        public double PressurePa;

        public ConstructionNativePressureCompartment(
            string Id,
            double VolumeM3,
            double PressurePa
        )
        {
            this.Id = Id;
            this.VolumeM3 = VolumeM3;
            this.PressurePa = PressurePa;
        }

        public ConstructionNativePressureCompartment()
        {
            this.Id = "";
        }
    }
}
