// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionTraversal
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "link_id")]
        public string LinkId;
        [DataMember(Name = "visit_id")]
        public string VisitId;
        [DataMember(Name = "source_deck_id")]
        public string SourceDeckId;
        [DataMember(Name = "destination_deck_id")]
        public string DestinationDeckId;
        [DataMember(Name = "instance_revision")]
        public ulong InstanceRevision;
        [DataMember(Name = "link_revision")]
        public ulong LinkRevision;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "location_revision")]
        public ulong LocationRevision;
        [DataMember(Name = "state_json")]
        public string StateJson;
        [DataMember(Name = "accepted_x")]
        public double AcceptedX;
        [DataMember(Name = "accepted_y")]
        public double AcceptedY;
        [DataMember(Name = "accepted_z")]
        public double AcceptedZ;
        [DataMember(Name = "phase")]
        public string Phase;
        [DataMember(Name = "interruption")]
        public string Interruption;
        [DataMember(Name = "last_tick")]
        public ulong LastTick;

        public ConstructionTraversal(
            string CharacterId,
            string Id,
            SpacetimeDB.Identity Owner,
            string InstanceId,
            string LinkId,
            string VisitId,
            string SourceDeckId,
            string DestinationDeckId,
            ulong InstanceRevision,
            ulong LinkRevision,
            ulong Revision,
            ulong LocationRevision,
            string StateJson,
            double AcceptedX,
            double AcceptedY,
            double AcceptedZ,
            string Phase,
            string Interruption,
            ulong LastTick
        )
        {
            this.CharacterId = CharacterId;
            this.Id = Id;
            this.Owner = Owner;
            this.InstanceId = InstanceId;
            this.LinkId = LinkId;
            this.VisitId = VisitId;
            this.SourceDeckId = SourceDeckId;
            this.DestinationDeckId = DestinationDeckId;
            this.InstanceRevision = InstanceRevision;
            this.LinkRevision = LinkRevision;
            this.Revision = Revision;
            this.LocationRevision = LocationRevision;
            this.StateJson = StateJson;
            this.AcceptedX = AcceptedX;
            this.AcceptedY = AcceptedY;
            this.AcceptedZ = AcceptedZ;
            this.Phase = Phase;
            this.Interruption = Interruption;
            this.LastTick = LastTick;
        }

        public ConstructionTraversal()
        {
            this.CharacterId = "";
            this.Id = "";
            this.InstanceId = "";
            this.LinkId = "";
            this.VisitId = "";
            this.SourceDeckId = "";
            this.DestinationDeckId = "";
            this.StateJson = "";
            this.Phase = "";
            this.Interruption = "";
        }
    }
}
