// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionStairEgressGeometry
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "stair_id")]
        public string StairId;
        [DataMember(Name = "visit_id")]
        public string VisitId;
        [DataMember(Name = "lower_deck_id")]
        public string LowerDeckId;
        [DataMember(Name = "upper_deck_id")]
        public string UpperDeckId;
        [DataMember(Name = "source_deck_id")]
        public string SourceDeckId;
        [DataMember(Name = "adapter_id")]
        public string AdapterId;
        [DataMember(Name = "adapter_revision")]
        public string AdapterRevision;
        [DataMember(Name = "audit_sha_256")]
        public string AuditSha256;
        [DataMember(Name = "proof_hash")]
        public string ProofHash;

        public ConstructionStairEgressGeometry(
            string CharacterId,
            string InstanceId,
            string StairId,
            string VisitId,
            string LowerDeckId,
            string UpperDeckId,
            string SourceDeckId,
            string AdapterId,
            string AdapterRevision,
            string AuditSha256,
            string ProofHash
        )
        {
            this.CharacterId = CharacterId;
            this.InstanceId = InstanceId;
            this.StairId = StairId;
            this.VisitId = VisitId;
            this.LowerDeckId = LowerDeckId;
            this.UpperDeckId = UpperDeckId;
            this.SourceDeckId = SourceDeckId;
            this.AdapterId = AdapterId;
            this.AdapterRevision = AdapterRevision;
            this.AuditSha256 = AuditSha256;
            this.ProofHash = ProofHash;
        }

        public ConstructionStairEgressGeometry()
        {
            this.CharacterId = "";
            this.InstanceId = "";
            this.StairId = "";
            this.VisitId = "";
            this.LowerDeckId = "";
            this.UpperDeckId = "";
            this.SourceDeckId = "";
            this.AdapterId = "";
            this.AdapterRevision = "";
            this.AuditSha256 = "";
            this.ProofHash = "";
        }
    }
}
