// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionStairAudit
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "stair_id")]
        public string StairId;
        [DataMember(Name = "visit_id")]
        public string VisitId;
        [DataMember(Name = "source_deck_id")]
        public string SourceDeckId;
        [DataMember(Name = "destination_deck_id")]
        public string DestinationDeckId;
        [DataMember(Name = "outcome")]
        public string Outcome;
        [DataMember(Name = "interruption")]
        public string Interruption;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "completed_micros")]
        public ulong CompletedMicros;

        public ConstructionStairAudit(
            string Id,
            SpacetimeDB.Identity Owner,
            string CharacterId,
            string InstanceId,
            string StairId,
            string VisitId,
            string SourceDeckId,
            string DestinationDeckId,
            string Outcome,
            string Interruption,
            ulong Revision,
            ulong CompletedMicros
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.CharacterId = CharacterId;
            this.InstanceId = InstanceId;
            this.StairId = StairId;
            this.VisitId = VisitId;
            this.SourceDeckId = SourceDeckId;
            this.DestinationDeckId = DestinationDeckId;
            this.Outcome = Outcome;
            this.Interruption = Interruption;
            this.Revision = Revision;
            this.CompletedMicros = CompletedMicros;
        }

        public ConstructionStairAudit()
        {
            this.Id = "";
            this.CharacterId = "";
            this.InstanceId = "";
            this.StairId = "";
            this.VisitId = "";
            this.SourceDeckId = "";
            this.DestinationDeckId = "";
            this.Outcome = "";
            this.Interruption = "";
        }
    }
}
