// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionCargoAssembly
    {
        [DataMember(Name = "container_id")]
        public string ContainerId;
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "carrier_id")]
        public string CarrierId;
        [DataMember(Name = "placed_object_id")]
        public string PlacedObjectId;
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "carrier_size")]
        public string CarrierSize;
        [DataMember(Name = "payload_asset_id")]
        public string PayloadAssetId;
        [DataMember(Name = "payload_glb_sha_256")]
        public string PayloadGlbSha256;
        [DataMember(Name = "interface_revision")]
        public string InterfaceRevision;
        [DataMember(Name = "retention_revision")]
        public string RetentionRevision;
        [DataMember(Name = "upper_frame_locked")]
        public bool UpperFrameLocked;
        [DataMember(Name = "lifecycle")]
        public string Lifecycle;
        [DataMember(Name = "revision")]
        public ulong Revision;

        public ConstructionCargoAssembly(
            string ContainerId,
            string Id,
            string CarrierId,
            string PlacedObjectId,
            string InstanceId,
            string DeckId,
            string CarrierSize,
            string PayloadAssetId,
            string PayloadGlbSha256,
            string InterfaceRevision,
            string RetentionRevision,
            bool UpperFrameLocked,
            string Lifecycle,
            ulong Revision
        )
        {
            this.ContainerId = ContainerId;
            this.Id = Id;
            this.CarrierId = CarrierId;
            this.PlacedObjectId = PlacedObjectId;
            this.InstanceId = InstanceId;
            this.DeckId = DeckId;
            this.CarrierSize = CarrierSize;
            this.PayloadAssetId = PayloadAssetId;
            this.PayloadGlbSha256 = PayloadGlbSha256;
            this.InterfaceRevision = InterfaceRevision;
            this.RetentionRevision = RetentionRevision;
            this.UpperFrameLocked = UpperFrameLocked;
            this.Lifecycle = Lifecycle;
            this.Revision = Revision;
        }

        public ConstructionCargoAssembly()
        {
            this.ContainerId = "";
            this.Id = "";
            this.CarrierId = "";
            this.PlacedObjectId = "";
            this.InstanceId = "";
            this.DeckId = "";
            this.CarrierSize = "";
            this.PayloadAssetId = "";
            this.PayloadGlbSha256 = "";
            this.InterfaceRevision = "";
            this.RetentionRevision = "";
            this.Lifecycle = "";
        }
    }
}
