// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionFlightDamageEvent
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "fitting_id")]
        public string FittingId;
        [DataMember(Name = "expected_fitting_revision")]
        public ulong ExpectedFittingRevision;
        [DataMember(Name = "loss_fraction")]
        public double LossFraction;
        [DataMember(Name = "source_event_id")]
        public string SourceEventId;
        [DataMember(Name = "created_micros")]
        public ulong CreatedMicros;

        public ConstructionFlightDamageEvent(
            string Id,
            string ShipId,
            string FittingId,
            ulong ExpectedFittingRevision,
            double LossFraction,
            string SourceEventId,
            ulong CreatedMicros
        )
        {
            this.Id = Id;
            this.ShipId = ShipId;
            this.FittingId = FittingId;
            this.ExpectedFittingRevision = ExpectedFittingRevision;
            this.LossFraction = LossFraction;
            this.SourceEventId = SourceEventId;
            this.CreatedMicros = CreatedMicros;
        }

        public ConstructionFlightDamageEvent()
        {
            this.Id = "";
            this.ShipId = "";
            this.FittingId = "";
            this.SourceEventId = "";
        }
    }
}
