// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionPassengerVisit
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "grant_id")]
        public string GrantId;
        [DataMember(Name = "grant_revision")]
        public ulong GrantRevision;
        [DataMember(Name = "visit_id")]
        public string VisitId;
        [DataMember(Name = "admission_revision")]
        public ulong AdmissionRevision;
        [DataMember(Name = "source_ship_id")]
        public string SourceShipId;
        [DataMember(Name = "source_deck_id")]
        public string SourceDeckId;
        [DataMember(Name = "source_visit_id")]
        public string SourceVisitId;
        [DataMember(Name = "source_location_revision")]
        public ulong SourceLocationRevision;
        [DataMember(Name = "source_instance_revision")]
        public ulong SourceInstanceRevision;
        [DataMember(Name = "source_sha_256")]
        public string SourceSha256;
        [DataMember(Name = "source_system_id")]
        public string SourceSystemId;
        [DataMember(Name = "source_x")]
        public double SourceX;
        [DataMember(Name = "source_y")]
        public double SourceY;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "recovery_reason")]
        public string RecoveryReason;
        [DataMember(Name = "retry_after_micros")]
        public ulong RetryAfterMicros;

        public ConstructionPassengerVisit(
            string CharacterId,
            SpacetimeDB.Identity Owner,
            string ShipId,
            string DeckId,
            string GrantId,
            ulong GrantRevision,
            string VisitId,
            ulong AdmissionRevision,
            string SourceShipId,
            string SourceDeckId,
            string SourceVisitId,
            ulong SourceLocationRevision,
            ulong SourceInstanceRevision,
            string SourceSha256,
            string SourceSystemId,
            double SourceX,
            double SourceY,
            ulong Revision,
            string RecoveryReason,
            ulong RetryAfterMicros
        )
        {
            this.CharacterId = CharacterId;
            this.Owner = Owner;
            this.ShipId = ShipId;
            this.DeckId = DeckId;
            this.GrantId = GrantId;
            this.GrantRevision = GrantRevision;
            this.VisitId = VisitId;
            this.AdmissionRevision = AdmissionRevision;
            this.SourceShipId = SourceShipId;
            this.SourceDeckId = SourceDeckId;
            this.SourceVisitId = SourceVisitId;
            this.SourceLocationRevision = SourceLocationRevision;
            this.SourceInstanceRevision = SourceInstanceRevision;
            this.SourceSha256 = SourceSha256;
            this.SourceSystemId = SourceSystemId;
            this.SourceX = SourceX;
            this.SourceY = SourceY;
            this.Revision = Revision;
            this.RecoveryReason = RecoveryReason;
            this.RetryAfterMicros = RetryAfterMicros;
        }

        public ConstructionPassengerVisit()
        {
            this.CharacterId = "";
            this.ShipId = "";
            this.DeckId = "";
            this.GrantId = "";
            this.VisitId = "";
            this.SourceShipId = "";
            this.SourceDeckId = "";
            this.SourceVisitId = "";
            this.SourceSha256 = "";
            this.SourceSystemId = "";
            this.RecoveryReason = "";
        }
    }
}
