// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionFlightReview
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "visit_id")]
        public string VisitId;
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "original_ship_id")]
        public string OriginalShipId;
        [DataMember(Name = "original_system_id")]
        public string OriginalSystemId;
        [DataMember(Name = "original_admission_revision")]
        public ulong OriginalAdmissionRevision;
        [DataMember(Name = "review_admission_revision")]
        public ulong ReviewAdmissionRevision;

        public ConstructionFlightReview(
            string CharacterId,
            SpacetimeDB.Identity Owner,
            string VisitId,
            string InstanceId,
            string DeckId,
            string OriginalShipId,
            string OriginalSystemId,
            ulong OriginalAdmissionRevision,
            ulong ReviewAdmissionRevision
        )
        {
            this.CharacterId = CharacterId;
            this.Owner = Owner;
            this.VisitId = VisitId;
            this.InstanceId = InstanceId;
            this.DeckId = DeckId;
            this.OriginalShipId = OriginalShipId;
            this.OriginalSystemId = OriginalSystemId;
            this.OriginalAdmissionRevision = OriginalAdmissionRevision;
            this.ReviewAdmissionRevision = ReviewAdmissionRevision;
        }

        public ConstructionFlightReview()
        {
            this.CharacterId = "";
            this.VisitId = "";
            this.InstanceId = "";
            this.DeckId = "";
            this.OriginalShipId = "";
            this.OriginalSystemId = "";
        }
    }
}
