// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionTraversalReservation
    {
        [DataMember(Name = "link_id")]
        public string LinkId;
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "traversal_id")]
        public string TraversalId;
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "source_deck_id")]
        public string SourceDeckId;
        [DataMember(Name = "destination_deck_id")]
        public string DestinationDeckId;
        [DataMember(Name = "reservation_json")]
        public string ReservationJson;

        public ConstructionTraversalReservation(
            string LinkId,
            string InstanceId,
            SpacetimeDB.Identity Owner,
            string TraversalId,
            string CharacterId,
            string SourceDeckId,
            string DestinationDeckId,
            string ReservationJson
        )
        {
            this.LinkId = LinkId;
            this.InstanceId = InstanceId;
            this.Owner = Owner;
            this.TraversalId = TraversalId;
            this.CharacterId = CharacterId;
            this.SourceDeckId = SourceDeckId;
            this.DestinationDeckId = DestinationDeckId;
            this.ReservationJson = ReservationJson;
        }

        public ConstructionTraversalReservation()
        {
            this.LinkId = "";
            this.InstanceId = "";
            this.TraversalId = "";
            this.CharacterId = "";
            this.SourceDeckId = "";
            this.DestinationDeckId = "";
            this.ReservationJson = "";
        }
    }
}
