// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionNativePressure
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "door_id")]
        public string DoorId;
        [DataMember(Name = "document_hash")]
        public string DocumentHash;
        [DataMember(Name = "installed_parts_json")]
        public string InstalledPartsJson;
        [DataMember(Name = "installation_fingerprint")]
        public string InstallationFingerprint;
        [DataMember(Name = "audit_sha_256")]
        public string AuditSha256;
        [DataMember(Name = "accepted_fraction")]
        public double AcceptedFraction;
        [DataMember(Name = "seal_retraction")]
        public double SealRetraction;
        [DataMember(Name = "revision")]
        public ulong Revision;

        public ConstructionNativePressure(
            string Id,
            SpacetimeDB.Identity Owner,
            string DeckId,
            string DoorId,
            string DocumentHash,
            string InstalledPartsJson,
            string InstallationFingerprint,
            string AuditSha256,
            double AcceptedFraction,
            double SealRetraction,
            ulong Revision
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.DeckId = DeckId;
            this.DoorId = DoorId;
            this.DocumentHash = DocumentHash;
            this.InstalledPartsJson = InstalledPartsJson;
            this.InstallationFingerprint = InstallationFingerprint;
            this.AuditSha256 = AuditSha256;
            this.AcceptedFraction = AcceptedFraction;
            this.SealRetraction = SealRetraction;
            this.Revision = Revision;
        }

        public ConstructionNativePressure()
        {
            this.Id = "";
            this.DeckId = "";
            this.DoorId = "";
            this.DocumentHash = "";
            this.InstalledPartsJson = "";
            this.InstallationFingerprint = "";
            this.AuditSha256 = "";
        }
    }
}
