// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionCargoOperation
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "principal")]
        public SpacetimeDB.Identity Principal;
        [DataMember(Name = "request_json")]
        public string RequestJson;
        [DataMember(Name = "result_json")]
        public string ResultJson;

        public ConstructionCargoOperation(
            string Id,
            SpacetimeDB.Identity Principal,
            string RequestJson,
            string ResultJson
        )
        {
            this.Id = Id;
            this.Principal = Principal;
            this.RequestJson = RequestJson;
            this.ResultJson = ResultJson;
        }

        public ConstructionCargoOperation()
        {
            this.Id = "";
            this.RequestJson = "";
            this.ResultJson = "";
        }
    }
}
