// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionFlightDirty
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "revision")]
        public ulong Revision;

        public ConstructionFlightDirty(
            string ShipId,
            ulong Revision
        )
        {
            this.ShipId = ShipId;
            this.Revision = Revision;
        }

        public ConstructionFlightDirty()
        {
            this.ShipId = "";
        }
    }
}
