// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionDeckStatus
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "source_deck_id")]
        public string SourceDeckId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "elevation")]
        public double Elevation;
        [DataMember(Name = "ceiling")]
        public double Ceiling;

        public ConstructionDeckStatus(
            string Id,
            string InstanceId,
            string SourceDeckId,
            string Name,
            double Elevation,
            double Ceiling
        )
        {
            this.Id = Id;
            this.InstanceId = InstanceId;
            this.SourceDeckId = SourceDeckId;
            this.Name = Name;
            this.Elevation = Elevation;
            this.Ceiling = Ceiling;
        }

        public ConstructionDeckStatus()
        {
            this.Id = "";
            this.InstanceId = "";
            this.SourceDeckId = "";
            this.Name = "";
        }
    }
}
