// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionAtmosphere
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "structure_json")]
        public string StructureJson;
        [DataMember(Name = "proof_hash")]
        public string ProofHash;
        [DataMember(Name = "initial_allocation_hash")]
        public string InitialAllocationHash;
        [DataMember(Name = "gas_json")]
        public string GasJson;
        [DataMember(Name = "source_moles")]
        public double SourceMoles;
        [DataMember(Name = "vented_moles")]
        public double VentedMoles;
        [DataMember(Name = "removed_moles")]
        public double RemovedMoles;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "last_tick")]
        public ulong LastTick;

        public ConstructionAtmosphere(
            string Id,
            SpacetimeDB.Identity Owner,
            string StructureJson,
            string ProofHash,
            string InitialAllocationHash,
            string GasJson,
            double SourceMoles,
            double VentedMoles,
            double RemovedMoles,
            ulong Revision,
            ulong LastTick
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.StructureJson = StructureJson;
            this.ProofHash = ProofHash;
            this.InitialAllocationHash = InitialAllocationHash;
            this.GasJson = GasJson;
            this.SourceMoles = SourceMoles;
            this.VentedMoles = VentedMoles;
            this.RemovedMoles = RemovedMoles;
            this.Revision = Revision;
            this.LastTick = LastTick;
        }

        public ConstructionAtmosphere()
        {
            this.Id = "";
            this.StructureJson = "";
            this.ProofHash = "";
            this.InitialAllocationHash = "";
            this.GasJson = "";
        }
    }
}
