// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionAirlock
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "inner_door_id")]
        public string InnerDoorId;
        [DataMember(Name = "outer_door_id")]
        public string OuterDoorId;
        [DataMember(Name = "document_hash")]
        public string DocumentHash;
        [DataMember(Name = "audit_sha_256")]
        public string AuditSha256;
        [DataMember(Name = "installation_fingerprint")]
        public string InstallationFingerprint;
        [DataMember(Name = "installed_parts_json")]
        public string InstalledPartsJson;
        [DataMember(Name = "inner_seal_retraction")]
        public double InnerSealRetraction;
        [DataMember(Name = "outer_seal_retraction")]
        public double OuterSealRetraction;
        [DataMember(Name = "inner_fraction")]
        public double InnerFraction;
        [DataMember(Name = "outer_fraction")]
        public double OuterFraction;
        [DataMember(Name = "driver_actor_id")]
        public string DriverActorId;
        [DataMember(Name = "driver_connection_id")]
        public string DriverConnectionId;
        [DataMember(Name = "drive_door_id")]
        public string DriveDoorId;
        [DataMember(Name = "drive_expires_micros")]
        public ulong DriveExpiresMicros;
        [DataMember(Name = "active")]
        public bool Active;
        [DataMember(Name = "tick")]
        public ulong Tick;
        [DataMember(Name = "last_schedule_micros")]
        public ulong LastScheduleMicros;
        [DataMember(Name = "revision")]
        public ulong Revision;

        public ConstructionAirlock(
            string Id,
            SpacetimeDB.Identity Owner,
            string DeckId,
            string InnerDoorId,
            string OuterDoorId,
            string DocumentHash,
            string AuditSha256,
            string InstallationFingerprint,
            string InstalledPartsJson,
            double InnerSealRetraction,
            double OuterSealRetraction,
            double InnerFraction,
            double OuterFraction,
            string DriverActorId,
            string DriverConnectionId,
            string DriveDoorId,
            ulong DriveExpiresMicros,
            bool Active,
            ulong Tick,
            ulong LastScheduleMicros,
            ulong Revision
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.DeckId = DeckId;
            this.InnerDoorId = InnerDoorId;
            this.OuterDoorId = OuterDoorId;
            this.DocumentHash = DocumentHash;
            this.AuditSha256 = AuditSha256;
            this.InstallationFingerprint = InstallationFingerprint;
            this.InstalledPartsJson = InstalledPartsJson;
            this.InnerSealRetraction = InnerSealRetraction;
            this.OuterSealRetraction = OuterSealRetraction;
            this.InnerFraction = InnerFraction;
            this.OuterFraction = OuterFraction;
            this.DriverActorId = DriverActorId;
            this.DriverConnectionId = DriverConnectionId;
            this.DriveDoorId = DriveDoorId;
            this.DriveExpiresMicros = DriveExpiresMicros;
            this.Active = Active;
            this.Tick = Tick;
            this.LastScheduleMicros = LastScheduleMicros;
            this.Revision = Revision;
        }

        public ConstructionAirlock()
        {
            this.Id = "";
            this.DeckId = "";
            this.InnerDoorId = "";
            this.OuterDoorId = "";
            this.DocumentHash = "";
            this.AuditSha256 = "";
            this.InstallationFingerprint = "";
            this.InstalledPartsJson = "";
            this.DriverActorId = "";
            this.DriverConnectionId = "";
            this.DriveDoorId = "";
        }
    }
}
