// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionNativePressureStatus
    {
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "door_id")]
        public string DoorId;
        [DataMember(Name = "fraction")]
        public double Fraction;
        [DataMember(Name = "seal_retraction")]
        public double SealRetraction;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "atmosphere_revision")]
        public ulong AtmosphereRevision;
        [DataMember(Name = "vented_moles")]
        public double VentedMoles;
        [DataMember(Name = "compartments")]
        public System.Collections.Generic.List<ConstructionNativePressureCompartment> Compartments;

        public ConstructionNativePressureStatus(
            string InstanceId,
            string DeckId,
            string DoorId,
            double Fraction,
            double SealRetraction,
            ulong Revision,
            ulong AtmosphereRevision,
            double VentedMoles,
            System.Collections.Generic.List<ConstructionNativePressureCompartment> Compartments
        )
        {
            this.InstanceId = InstanceId;
            this.DeckId = DeckId;
            this.DoorId = DoorId;
            this.Fraction = Fraction;
            this.SealRetraction = SealRetraction;
            this.Revision = Revision;
            this.AtmosphereRevision = AtmosphereRevision;
            this.VentedMoles = VentedMoles;
            this.Compartments = Compartments;
        }

        public ConstructionNativePressureStatus()
        {
            this.InstanceId = "";
            this.DeckId = "";
            this.DoorId = "";
            this.Compartments = new();
        }
    }
}
