// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionReviewOrigin
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "review_instance_id")]
        public string ReviewInstanceId;
        [DataMember(Name = "visit_id")]
        public string VisitId;
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "return_ship_id")]
        public string ReturnShipId;
        [DataMember(Name = "return_x")]
        public double ReturnX;
        [DataMember(Name = "return_y")]
        public double ReturnY;
        [DataMember(Name = "location_revision")]
        public ulong LocationRevision;
        [DataMember(Name = "x")]
        public double X;
        [DataMember(Name = "y")]
        public double Y;
        [DataMember(Name = "source_revision")]
        public ulong SourceRevision;
        [DataMember(Name = "source_sha_256")]
        public string SourceSha256;

        public ConstructionReviewOrigin(
            string CharacterId,
            SpacetimeDB.Identity Owner,
            string ReviewInstanceId,
            string VisitId,
            string InstanceId,
            string DeckId,
            string ReturnShipId,
            double ReturnX,
            double ReturnY,
            ulong LocationRevision,
            double X,
            double Y,
            ulong SourceRevision,
            string SourceSha256
        )
        {
            this.CharacterId = CharacterId;
            this.Owner = Owner;
            this.ReviewInstanceId = ReviewInstanceId;
            this.VisitId = VisitId;
            this.InstanceId = InstanceId;
            this.DeckId = DeckId;
            this.ReturnShipId = ReturnShipId;
            this.ReturnX = ReturnX;
            this.ReturnY = ReturnY;
            this.LocationRevision = LocationRevision;
            this.X = X;
            this.Y = Y;
            this.SourceRevision = SourceRevision;
            this.SourceSha256 = SourceSha256;
        }

        public ConstructionReviewOrigin()
        {
            this.CharacterId = "";
            this.ReviewInstanceId = "";
            this.VisitId = "";
            this.InstanceId = "";
            this.DeckId = "";
            this.ReturnShipId = "";
            this.SourceSha256 = "";
        }
    }
}
