// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionFlightFitting
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "placed_object_id")]
        public string PlacedObjectId;
        [DataMember(Name = "source_device_id")]
        public string SourceDeviceId;
        [DataMember(Name = "definition_id")]
        public string DefinitionId;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "installed")]
        public bool Installed;
        [DataMember(Name = "powered")]
        public bool Powered;
        [DataMember(Name = "availability")]
        public double Availability;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "definition_revision")]
        public uint DefinitionRevision;

        public ConstructionFlightFitting(
            string Id,
            string ShipId,
            string PlacedObjectId,
            string SourceDeviceId,
            string DefinitionId,
            string Kind,
            bool Installed,
            bool Powered,
            double Availability,
            ulong Revision,
            uint DefinitionRevision
        )
        {
            this.Id = Id;
            this.ShipId = ShipId;
            this.PlacedObjectId = PlacedObjectId;
            this.SourceDeviceId = SourceDeviceId;
            this.DefinitionId = DefinitionId;
            this.Kind = Kind;
            this.Installed = Installed;
            this.Powered = Powered;
            this.Availability = Availability;
            this.Revision = Revision;
            this.DefinitionRevision = DefinitionRevision;
        }

        public ConstructionFlightFitting()
        {
            this.Id = "";
            this.ShipId = "";
            this.PlacedObjectId = "";
            this.SourceDeviceId = "";
            this.DefinitionId = "";
            this.Kind = "";
        }
    }
}
