// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionCargoGrid
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "definition_sha_256")]
        public string DefinitionSha256;
        [DataMember(Name = "grid_json")]
        public string GridJson;
        [DataMember(Name = "revision")]
        public ulong Revision;

        public ConstructionCargoGrid(
            string Id,
            string InstanceId,
            string DeckId,
            string DefinitionSha256,
            string GridJson,
            ulong Revision
        )
        {
            this.Id = Id;
            this.InstanceId = InstanceId;
            this.DeckId = DeckId;
            this.DefinitionSha256 = DefinitionSha256;
            this.GridJson = GridJson;
            this.Revision = Revision;
        }

        public ConstructionCargoGrid()
        {
            this.Id = "";
            this.InstanceId = "";
            this.DeckId = "";
            this.DefinitionSha256 = "";
            this.GridJson = "";
        }
    }
}
