// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionInstanceStatus
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "workspace_id")]
        public string WorkspaceId;
        [DataMember(Name = "blueprint_id")]
        public string BlueprintId;
        [DataMember(Name = "blueprint_sha_256")]
        public string BlueprintSha256;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "document_json")]
        public string DocumentJson;
        [DataMember(Name = "spawn_deck_id")]
        public string SpawnDeckId;
        [DataMember(Name = "furnishing_revision")]
        public ulong FurnishingRevision;
        [DataMember(Name = "furnishings_json")]
        public string FurnishingsJson;

        public ConstructionInstanceStatus(
            string Id,
            string WorkspaceId,
            string BlueprintId,
            string BlueprintSha256,
            string Name,
            ulong Revision,
            string DocumentJson,
            string SpawnDeckId,
            ulong FurnishingRevision,
            string FurnishingsJson
        )
        {
            this.Id = Id;
            this.WorkspaceId = WorkspaceId;
            this.BlueprintId = BlueprintId;
            this.BlueprintSha256 = BlueprintSha256;
            this.Name = Name;
            this.Revision = Revision;
            this.DocumentJson = DocumentJson;
            this.SpawnDeckId = SpawnDeckId;
            this.FurnishingRevision = FurnishingRevision;
            this.FurnishingsJson = FurnishingsJson;
        }

        public ConstructionInstanceStatus()
        {
            this.Id = "";
            this.WorkspaceId = "";
            this.BlueprintId = "";
            this.BlueprintSha256 = "";
            this.Name = "";
            this.DocumentJson = "";
            this.SpawnDeckId = "";
            this.FurnishingsJson = "";
        }
    }
}
