// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionReceipt
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "principal")]
        public SpacetimeDB.Identity Principal;
        [DataMember(Name = "request")]
        public string Request;
        [DataMember(Name = "result_id")]
        public string ResultId;
        [DataMember(Name = "revision")]
        public ulong Revision;

        public ConstructionReceipt(
            string Id,
            SpacetimeDB.Identity Principal,
            string Request,
            string ResultId,
            ulong Revision
        )
        {
            this.Id = Id;
            this.Principal = Principal;
            this.Request = Request;
            this.ResultId = ResultId;
            this.Revision = Revision;
        }

        public ConstructionReceipt()
        {
            this.Id = "";
            this.Request = "";
            this.ResultId = "";
        }
    }
}
