// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionStairReservation
    {
        [DataMember(Name = "stair_id")]
        public string StairId;
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "walk_id")]
        public string WalkId;
        [DataMember(Name = "visit_id")]
        public string VisitId;
        [DataMember(Name = "proof_hash")]
        public string ProofHash;
        [DataMember(Name = "bounds_json")]
        public string BoundsJson;

        public ConstructionStairReservation(
            string StairId,
            string InstanceId,
            string CharacterId,
            string WalkId,
            string VisitId,
            string ProofHash,
            string BoundsJson
        )
        {
            this.StairId = StairId;
            this.InstanceId = InstanceId;
            this.CharacterId = CharacterId;
            this.WalkId = WalkId;
            this.VisitId = VisitId;
            this.ProofHash = ProofHash;
            this.BoundsJson = BoundsJson;
        }

        public ConstructionStairReservation()
        {
            this.StairId = "";
            this.InstanceId = "";
            this.CharacterId = "";
            this.WalkId = "";
            this.VisitId = "";
            this.ProofHash = "";
            this.BoundsJson = "";
        }
    }
}
