// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionTraversalLink
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "source_link_id")]
        public string SourceLinkId;
        [DataMember(Name = "lower_deck_id")]
        public string LowerDeckId;
        [DataMember(Name = "upper_deck_id")]
        public string UpperDeckId;
        [DataMember(Name = "instance_revision")]
        public ulong InstanceRevision;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "adapter_id")]
        public string AdapterId;
        [DataMember(Name = "adapter_revision")]
        public string AdapterRevision;
        [DataMember(Name = "audit_sha_256")]
        public string AuditSha256;
        [DataMember(Name = "installation_json")]
        public string InstallationJson;
        [DataMember(Name = "contract_json")]
        public string ContractJson;
        [DataMember(Name = "fingerprint")]
        public string Fingerprint;

        public ConstructionTraversalLink(
            string Id,
            SpacetimeDB.Identity Owner,
            string InstanceId,
            string SourceLinkId,
            string LowerDeckId,
            string UpperDeckId,
            ulong InstanceRevision,
            ulong Revision,
            string AdapterId,
            string AdapterRevision,
            string AuditSha256,
            string InstallationJson,
            string ContractJson,
            string Fingerprint
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.InstanceId = InstanceId;
            this.SourceLinkId = SourceLinkId;
            this.LowerDeckId = LowerDeckId;
            this.UpperDeckId = UpperDeckId;
            this.InstanceRevision = InstanceRevision;
            this.Revision = Revision;
            this.AdapterId = AdapterId;
            this.AdapterRevision = AdapterRevision;
            this.AuditSha256 = AuditSha256;
            this.InstallationJson = InstallationJson;
            this.ContractJson = ContractJson;
            this.Fingerprint = Fingerprint;
        }

        public ConstructionTraversalLink()
        {
            this.Id = "";
            this.InstanceId = "";
            this.SourceLinkId = "";
            this.LowerDeckId = "";
            this.UpperDeckId = "";
            this.AdapterId = "";
            this.AdapterRevision = "";
            this.AuditSha256 = "";
            this.InstallationJson = "";
            this.ContractJson = "";
            this.Fingerprint = "";
        }
    }
}
