// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstructionPilotSeat
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "station_id")]
        public string StationId;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "instance_revision")]
        public ulong InstanceRevision;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "recovery_requested")]
        public bool RecoveryRequested;
        [DataMember(Name = "recovery_reason")]
        public string RecoveryReason;

        public ConstructionPilotSeat(
            string CharacterId,
            SpacetimeDB.Identity Owner,
            string StationId,
            string ShipId,
            string DeckId,
            ulong InstanceRevision,
            ulong Revision,
            bool RecoveryRequested,
            string RecoveryReason
        )
        {
            this.CharacterId = CharacterId;
            this.Owner = Owner;
            this.StationId = StationId;
            this.ShipId = ShipId;
            this.DeckId = DeckId;
            this.InstanceRevision = InstanceRevision;
            this.Revision = Revision;
            this.RecoveryRequested = RecoveryRequested;
            this.RecoveryReason = RecoveryReason;
        }

        public ConstructionPilotSeat()
        {
            this.CharacterId = "";
            this.StationId = "";
            this.ShipId = "";
            this.DeckId = "";
            this.RecoveryReason = "";
        }
    }
}
