// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ContentDefinitionUsage
    {
        [DataMember(Name = "definition_key")]
        public string DefinitionKey;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "definition_id")]
        public string DefinitionId;
        [DataMember(Name = "instance_count")]
        public ulong InstanceCount;
        [DataMember(Name = "pins_json")]
        public string PinsJson;
        [DataMember(Name = "referenced_by_json")]
        public string ReferencedByJson;
        [DataMember(Name = "computed_micros")]
        public ulong ComputedMicros;

        public ContentDefinitionUsage(
            string DefinitionKey,
            string Kind,
            string DefinitionId,
            ulong InstanceCount,
            string PinsJson,
            string ReferencedByJson,
            ulong ComputedMicros
        )
        {
            this.DefinitionKey = DefinitionKey;
            this.Kind = Kind;
            this.DefinitionId = DefinitionId;
            this.InstanceCount = InstanceCount;
            this.PinsJson = PinsJson;
            this.ReferencedByJson = ReferencedByJson;
            this.ComputedMicros = ComputedMicros;
        }

        public ContentDefinitionUsage()
        {
            this.DefinitionKey = "";
            this.Kind = "";
            this.DefinitionId = "";
            this.PinsJson = "";
            this.ReferencedByJson = "";
        }
    }
}
