// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CouchSeat
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "object_id")]
        public string ObjectId;

        public CouchSeat(
            string CharacterId,
            string ObjectId
        )
        {
            this.CharacterId = CharacterId;
            this.ObjectId = ObjectId;
        }

        public CouchSeat()
        {
            this.CharacterId = "";
            this.ObjectId = "";
        }
    }
}
