// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CrewPresentation
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "appearance_json")]
        public string AppearanceJson;
        [DataMember(Name = "equipment_json")]
        public string EquipmentJson;
        [DataMember(Name = "dead")]
        public bool Dead;
        [DataMember(Name = "seated")]
        public bool Seated;
        [DataMember(Name = "aim_active")]
        public bool AimActive;
        [DataMember(Name = "aim_angle")]
        public double AimAngle;
        [DataMember(Name = "shot_sequence")]
        public ulong ShotSequence;
        [DataMember(Name = "shot_x")]
        public double ShotX;
        [DataMember(Name = "shot_y")]
        public double ShotY;
        [DataMember(Name = "shot_struck")]
        public bool ShotStruck;

        public CrewPresentation(
            string CharacterId,
            string ShipId,
            string DeckId,
            string AppearanceJson,
            string EquipmentJson,
            bool Dead,
            bool Seated,
            bool AimActive,
            double AimAngle,
            ulong ShotSequence,
            double ShotX,
            double ShotY,
            bool ShotStruck
        )
        {
            this.CharacterId = CharacterId;
            this.ShipId = ShipId;
            this.DeckId = DeckId;
            this.AppearanceJson = AppearanceJson;
            this.EquipmentJson = EquipmentJson;
            this.Dead = Dead;
            this.Seated = Seated;
            this.AimActive = AimActive;
            this.AimAngle = AimAngle;
            this.ShotSequence = ShotSequence;
            this.ShotX = ShotX;
            this.ShotY = ShotY;
            this.ShotStruck = ShotStruck;
        }

        public CrewPresentation()
        {
            this.CharacterId = "";
            this.ShipId = "";
            this.DeckId = "";
            this.AppearanceJson = "";
            this.EquipmentJson = "";
        }
    }
}
