// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EditReceipt
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "created_micros")]
        public ulong CreatedMicros;

        public EditReceipt(
            string Id,
            SpacetimeDB.Identity Owner,
            string ShipId,
            ulong Revision,
            string Name,
            ulong CreatedMicros
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.ShipId = ShipId;
            this.Revision = Revision;
            this.Name = Name;
            this.CreatedMicros = CreatedMicros;
        }

        public EditReceipt()
        {
            this.Id = "";
            this.ShipId = "";
            this.Name = "";
        }
    }
}
