// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EvaBodyStatus
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "system_id")]
        public string SystemId;
        [DataMember(Name = "phase")]
        public string Phase;
        [DataMember(Name = "x")]
        public double X;
        [DataMember(Name = "y")]
        public double Y;
        [DataMember(Name = "vx")]
        public double Vx;
        [DataMember(Name = "vy")]
        public double Vy;
        [DataMember(Name = "heading")]
        public double Heading;
        [DataMember(Name = "anchor_ship_id")]
        public string AnchorShipId;
        [DataMember(Name = "local_x")]
        public double LocalX;
        [DataMember(Name = "local_y")]
        public double LocalY;
        [DataMember(Name = "local_heading")]
        public double LocalHeading;
        [DataMember(Name = "ref_ship_id")]
        public string RefShipId;
        [DataMember(Name = "forward")]
        public double Forward;
        [DataMember(Name = "strafe")]
        public double Strafe;
        [DataMember(Name = "turn")]
        public double Turn;
        [DataMember(Name = "walking")]
        public bool Walking;
        [DataMember(Name = "exit_ship_id")]
        public string ExitShipId;
        [DataMember(Name = "visit_id")]
        public string VisitId;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "return_ends_micros")]
        public ulong ReturnEndsMicros;
        [DataMember(Name = "stranded")]
        public bool Stranded;
        [DataMember(Name = "server_tick")]
        public ulong ServerTick;
        [DataMember(Name = "revision")]
        public ulong Revision;

        public EvaBodyStatus(
            string CharacterId,
            string SystemId,
            string Phase,
            double X,
            double Y,
            double Vx,
            double Vy,
            double Heading,
            string AnchorShipId,
            double LocalX,
            double LocalY,
            double LocalHeading,
            string RefShipId,
            double Forward,
            double Strafe,
            double Turn,
            bool Walking,
            string ExitShipId,
            string VisitId,
            string DeckId,
            ulong ReturnEndsMicros,
            bool Stranded,
            ulong ServerTick,
            ulong Revision
        )
        {
            this.CharacterId = CharacterId;
            this.SystemId = SystemId;
            this.Phase = Phase;
            this.X = X;
            this.Y = Y;
            this.Vx = Vx;
            this.Vy = Vy;
            this.Heading = Heading;
            this.AnchorShipId = AnchorShipId;
            this.LocalX = LocalX;
            this.LocalY = LocalY;
            this.LocalHeading = LocalHeading;
            this.RefShipId = RefShipId;
            this.Forward = Forward;
            this.Strafe = Strafe;
            this.Turn = Turn;
            this.Walking = Walking;
            this.ExitShipId = ExitShipId;
            this.VisitId = VisitId;
            this.DeckId = DeckId;
            this.ReturnEndsMicros = ReturnEndsMicros;
            this.Stranded = Stranded;
            this.ServerTick = ServerTick;
            this.Revision = Revision;
        }

        public EvaBodyStatus()
        {
            this.CharacterId = "";
            this.SystemId = "";
            this.Phase = "";
            this.AnchorShipId = "";
            this.RefShipId = "";
            this.ExitShipId = "";
            this.VisitId = "";
            this.DeckId = "";
        }
    }
}
