// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EvaCycleAirlock
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "airlock_id")]
        public string AirlockId;

        public EvaCycleAirlock(
            string ShipId,
            string AirlockId
        )
        {
            this.ShipId = ShipId;
            this.AirlockId = AirlockId;
        }

        public EvaCycleAirlock()
        {
            this.ShipId = "";
            this.AirlockId = "";
        }
    }
}
