// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameShipAccessStatus
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "template_sha_256")]
        public string TemplateSha256;

        public GameShipAccessStatus(
            string ShipId,
            string CharacterId,
            string InstanceId,
            string DeckId,
            ulong Revision,
            string TemplateSha256
        )
        {
            this.ShipId = ShipId;
            this.CharacterId = CharacterId;
            this.InstanceId = InstanceId;
            this.DeckId = DeckId;
            this.Revision = Revision;
            this.TemplateSha256 = TemplateSha256;
        }

        public GameShipAccessStatus()
        {
            this.ShipId = "";
            this.CharacterId = "";
            this.InstanceId = "";
            this.DeckId = "";
            this.TemplateSha256 = "";
        }
    }
}
