// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GrantShipPassenger
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "grantee_id")]
        public string GranteeId;
        [DataMember(Name = "expected_instance_revision")]
        public ulong ExpectedInstanceRevision;
        [DataMember(Name = "expected_flight_revision")]
        public ulong ExpectedFlightRevision;
        [DataMember(Name = "duration_seconds")]
        public uint DurationSeconds;
        [DataMember(Name = "operation_id")]
        public string OperationId;

        public GrantShipPassenger(
            string ShipId,
            string GranteeId,
            ulong ExpectedInstanceRevision,
            ulong ExpectedFlightRevision,
            uint DurationSeconds,
            string OperationId
        )
        {
            this.ShipId = ShipId;
            this.GranteeId = GranteeId;
            this.ExpectedInstanceRevision = ExpectedInstanceRevision;
            this.ExpectedFlightRevision = ExpectedFlightRevision;
            this.DurationSeconds = DurationSeconds;
            this.OperationId = OperationId;
        }

        public GrantShipPassenger()
        {
            this.ShipId = "";
            this.GranteeId = "";
            this.OperationId = "";
        }
    }
}
