// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InstallCargoHandlingFixture
    {
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "expected_instance_revision")]
        public ulong ExpectedInstanceRevision;
        [DataMember(Name = "operation_id")]
        public string OperationId;

        public InstallCargoHandlingFixture(
            string InstanceId,
            ulong ExpectedInstanceRevision,
            string OperationId
        )
        {
            this.InstanceId = InstanceId;
            this.ExpectedInstanceRevision = ExpectedInstanceRevision;
            this.OperationId = OperationId;
        }

        public InstallCargoHandlingFixture()
        {
            this.InstanceId = "";
            this.OperationId = "";
        }
    }
}
