// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InteractionReceipt
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "operation_id")]
        public string OperationId;
        [DataMember(Name = "request")]
        public string Request;
        [DataMember(Name = "created_micros")]
        public ulong CreatedMicros;

        public InteractionReceipt(
            string Id,
            string CharacterId,
            string OperationId,
            string Request,
            ulong CreatedMicros
        )
        {
            this.Id = Id;
            this.CharacterId = CharacterId;
            this.OperationId = OperationId;
            this.Request = Request;
            this.CreatedMicros = CreatedMicros;
        }

        public InteractionReceipt()
        {
            this.Id = "";
            this.CharacterId = "";
            this.OperationId = "";
            this.Request = "";
        }
    }
}
