// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InventoryContainer
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "parent_item_id")]
        public string ParentItemId;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "width")]
        public uint Width;
        [DataMember(Name = "height")]
        public uint Height;
        [DataMember(Name = "max_mass_kg")]
        public double MaxMassKg;
        [DataMember(Name = "capacity_litres")]
        public double CapacityLitres;
        [DataMember(Name = "amount_litres")]
        public double AmountLitres;
        [DataMember(Name = "liquid_type")]
        public string LiquidType;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "local_x")]
        public double LocalX;
        [DataMember(Name = "local_y")]
        public double LocalY;
        [DataMember(Name = "carried")]
        public bool Carried;

        public InventoryContainer(
            string Id,
            string CharacterId,
            string ParentItemId,
            string Kind,
            string Name,
            uint Width,
            uint Height,
            double MaxMassKg,
            double CapacityLitres,
            double AmountLitres,
            string LiquidType,
            string ShipId,
            double LocalX,
            double LocalY,
            bool Carried
        )
        {
            this.Id = Id;
            this.CharacterId = CharacterId;
            this.ParentItemId = ParentItemId;
            this.Kind = Kind;
            this.Name = Name;
            this.Width = Width;
            this.Height = Height;
            this.MaxMassKg = MaxMassKg;
            this.CapacityLitres = CapacityLitres;
            this.AmountLitres = AmountLitres;
            this.LiquidType = LiquidType;
            this.ShipId = ShipId;
            this.LocalX = LocalX;
            this.LocalY = LocalY;
            this.Carried = Carried;
        }

        public InventoryContainer()
        {
            this.Id = "";
            this.CharacterId = "";
            this.ParentItemId = "";
            this.Kind = "";
            this.Name = "";
            this.LiquidType = "";
            this.ShipId = "";
        }
    }
}
