// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InventoryItemMembership
    {
        [DataMember(Name = "item_id")]
        public string ItemId;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "container_id")]
        public string ContainerId;
        [DataMember(Name = "root_container_id")]
        public string RootContainerId;
        [DataMember(Name = "root_character_id")]
        public string RootCharacterId;

        public InventoryItemMembership(
            string ItemId,
            ulong Revision,
            string ContainerId,
            string RootContainerId,
            string RootCharacterId
        )
        {
            this.ItemId = ItemId;
            this.Revision = Revision;
            this.ContainerId = ContainerId;
            this.RootContainerId = RootContainerId;
            this.RootCharacterId = RootCharacterId;
        }

        public InventoryItemMembership()
        {
            this.ItemId = "";
            this.ContainerId = "";
            this.RootContainerId = "";
            this.RootCharacterId = "";
        }
    }
}
