// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class JoinSharedSystem
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "expected_ship_revision")]
        public ulong ExpectedShipRevision;
        [DataMember(Name = "expected_admission_revision")]
        public ulong ExpectedAdmissionRevision;
        [DataMember(Name = "operation_id")]
        public string OperationId;

        public JoinSharedSystem(
            string CharacterId,
            string ShipId,
            ulong ExpectedShipRevision,
            ulong ExpectedAdmissionRevision,
            string OperationId
        )
        {
            this.CharacterId = CharacterId;
            this.ShipId = ShipId;
            this.ExpectedShipRevision = ExpectedShipRevision;
            this.ExpectedAdmissionRevision = ExpectedAdmissionRevision;
            this.OperationId = OperationId;
        }

        public JoinSharedSystem()
        {
            this.CharacterId = "";
            this.ShipId = "";
            this.OperationId = "";
        }
    }
}
