// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LegacyBodyAlias
    {
        [DataMember(Name = "legacy_body_id")]
        public string LegacyBodyId;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "canonical_body_id")]
        public string CanonicalBodyId;
        [DataMember(Name = "system_id")]
        public string SystemId;
        [DataMember(Name = "legacy_snapshot_json")]
        public string LegacySnapshotJson;

        public LegacyBodyAlias(
            string LegacyBodyId,
            SpacetimeDB.Identity Owner,
            string ShipId,
            string CanonicalBodyId,
            string SystemId,
            string LegacySnapshotJson
        )
        {
            this.LegacyBodyId = LegacyBodyId;
            this.Owner = Owner;
            this.ShipId = ShipId;
            this.CanonicalBodyId = CanonicalBodyId;
            this.SystemId = SystemId;
            this.LegacySnapshotJson = LegacySnapshotJson;
        }

        public LegacyBodyAlias()
        {
            this.LegacyBodyId = "";
            this.ShipId = "";
            this.CanonicalBodyId = "";
            this.SystemId = "";
            this.LegacySnapshotJson = "";
        }
    }
}
