// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LifecycleOutbox
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "next_event_id")]
        public ulong NextEventId;
        [DataMember(Name = "oldest_event_id")]
        public ulong OldestEventId;
        [DataMember(Name = "pruned_events")]
        public ulong PrunedEvents;
        [DataMember(Name = "rejected_events")]
        public ulong RejectedEvents;
        [DataMember(Name = "updated_micros")]
        public ulong UpdatedMicros;

        public LifecycleOutbox(
            uint Id,
            ulong NextEventId,
            ulong OldestEventId,
            ulong PrunedEvents,
            ulong RejectedEvents,
            ulong UpdatedMicros
        )
        {
            this.Id = Id;
            this.NextEventId = NextEventId;
            this.OldestEventId = OldestEventId;
            this.PrunedEvents = PrunedEvents;
            this.RejectedEvents = RejectedEvents;
            this.UpdatedMicros = UpdatedMicros;
        }

        public LifecycleOutbox()
        {
        }
    }
}
