// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LifecycleCursor
    {
        [DataMember(Name = "consumer_id")]
        public string ConsumerId;
        [DataMember(Name = "last_event_id")]
        public ulong LastEventId;
        [DataMember(Name = "missed_events")]
        public ulong MissedEvents;
        [DataMember(Name = "updated_micros")]
        public ulong UpdatedMicros;

        public LifecycleCursor(
            string ConsumerId,
            ulong LastEventId,
            ulong MissedEvents,
            ulong UpdatedMicros
        )
        {
            this.ConsumerId = ConsumerId;
            this.LastEventId = LastEventId;
            this.MissedEvents = MissedEvents;
            this.UpdatedMicros = UpdatedMicros;
        }

        public LifecycleCursor()
        {
            this.ConsumerId = "";
        }
    }
}
