// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MapShipProjection
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "system_id")]
        public string SystemId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "x")]
        public double X;
        [DataMember(Name = "y")]
        public double Y;
        [DataMember(Name = "heading")]
        public double Heading;
        [DataMember(Name = "server_tick")]
        public ulong ServerTick;

        public MapShipProjection(
            string ShipId,
            string SystemId,
            string Name,
            double X,
            double Y,
            double Heading,
            ulong ServerTick
        )
        {
            this.ShipId = ShipId;
            this.SystemId = SystemId;
            this.Name = Name;
            this.X = X;
            this.Y = Y;
            this.Heading = Heading;
            this.ServerTick = ServerTick;
        }

        public MapShipProjection()
        {
            this.ShipId = "";
            this.SystemId = "";
            this.Name = "";
        }
    }
}
