// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MoveInventoryItem
    {
        [DataMember(Name = "item_id")]
        public string ItemId;
        [DataMember(Name = "container_id")]
        public string ContainerId;
        [DataMember(Name = "x")]
        public int X;
        [DataMember(Name = "y")]
        public int Y;
        [DataMember(Name = "rotated")]
        public bool Rotated;
        [DataMember(Name = "expected_revision")]
        public ulong ExpectedRevision;
        [DataMember(Name = "operation_id")]
        public string OperationId;

        public MoveInventoryItem(
            string ItemId,
            string ContainerId,
            int X,
            int Y,
            bool Rotated,
            ulong ExpectedRevision,
            string OperationId
        )
        {
            this.ItemId = ItemId;
            this.ContainerId = ContainerId;
            this.X = X;
            this.Y = Y;
            this.Rotated = Rotated;
            this.ExpectedRevision = ExpectedRevision;
            this.OperationId = OperationId;
        }

        public MoveInventoryItem()
        {
            this.ItemId = "";
            this.ContainerId = "";
            this.OperationId = "";
        }
    }
}
