// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MoveCargoCarrier
    {
        [DataMember(Name = "grid_id")]
        public string GridId;
        [DataMember(Name = "expected_grid_revision")]
        public ulong ExpectedGridRevision;
        [DataMember(Name = "operation_id")]
        public string OperationId;
        [DataMember(Name = "container_id")]
        public string ContainerId;
        [DataMember(Name = "expected_placement_revision")]
        public ulong ExpectedPlacementRevision;
        [DataMember(Name = "expected_inventory_revision")]
        public ulong ExpectedInventoryRevision;
        [DataMember(Name = "origin_x")]
        public int OriginX;
        [DataMember(Name = "origin_y")]
        public int OriginY;
        [DataMember(Name = "origin_z")]
        public int OriginZ;
        [DataMember(Name = "quarter_turns")]
        public byte QuarterTurns;

        public MoveCargoCarrier(
            string GridId,
            ulong ExpectedGridRevision,
            string OperationId,
            string ContainerId,
            ulong ExpectedPlacementRevision,
            ulong ExpectedInventoryRevision,
            int OriginX,
            int OriginY,
            int OriginZ,
            byte QuarterTurns
        )
        {
            this.GridId = GridId;
            this.ExpectedGridRevision = ExpectedGridRevision;
            this.OperationId = OperationId;
            this.ContainerId = ContainerId;
            this.ExpectedPlacementRevision = ExpectedPlacementRevision;
            this.ExpectedInventoryRevision = ExpectedInventoryRevision;
            this.OriginX = OriginX;
            this.OriginY = OriginY;
            this.OriginZ = OriginZ;
            this.QuarterTurns = QuarterTurns;
        }

        public MoveCargoCarrier()
        {
            this.GridId = "";
            this.OperationId = "";
            this.ContainerId = "";
        }
    }
}
