// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NativeAirlockStatus
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "inner_door_id")]
        public string InnerDoorId;
        [DataMember(Name = "outer_door_id")]
        public string OuterDoorId;
        [DataMember(Name = "inner_fraction")]
        public double InnerFraction;
        [DataMember(Name = "outer_fraction")]
        public double OuterFraction;
        [DataMember(Name = "inner_seal_retraction")]
        public double InnerSealRetraction;
        [DataMember(Name = "outer_seal_retraction")]
        public double OuterSealRetraction;
        [DataMember(Name = "interior_pressure_pa")]
        public double InteriorPressurePa;
        [DataMember(Name = "chamber_pressure_pa")]
        public double ChamberPressurePa;
        [DataMember(Name = "outer_pressure_pa")]
        public double OuterPressurePa;
        [DataMember(Name = "manual_service_active")]
        public bool ManualServiceActive;
        [DataMember(Name = "inner_can_service")]
        public bool InnerCanService;
        [DataMember(Name = "outer_can_service")]
        public bool OuterCanService;
        [DataMember(Name = "revision")]
        public ulong Revision;

        public NativeAirlockStatus(
            string Id,
            string DeckId,
            string InnerDoorId,
            string OuterDoorId,
            double InnerFraction,
            double OuterFraction,
            double InnerSealRetraction,
            double OuterSealRetraction,
            double InteriorPressurePa,
            double ChamberPressurePa,
            double OuterPressurePa,
            bool ManualServiceActive,
            bool InnerCanService,
            bool OuterCanService,
            ulong Revision
        )
        {
            this.Id = Id;
            this.DeckId = DeckId;
            this.InnerDoorId = InnerDoorId;
            this.OuterDoorId = OuterDoorId;
            this.InnerFraction = InnerFraction;
            this.OuterFraction = OuterFraction;
            this.InnerSealRetraction = InnerSealRetraction;
            this.OuterSealRetraction = OuterSealRetraction;
            this.InteriorPressurePa = InteriorPressurePa;
            this.ChamberPressurePa = ChamberPressurePa;
            this.OuterPressurePa = OuterPressurePa;
            this.ManualServiceActive = ManualServiceActive;
            this.InnerCanService = InnerCanService;
            this.OuterCanService = OuterCanService;
            this.Revision = Revision;
        }

        public NativeAirlockStatus()
        {
            this.Id = "";
            this.DeckId = "";
            this.InnerDoorId = "";
            this.OuterDoorId = "";
        }
    }
}
