// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NearbyFieldAsteroid
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "system_id")]
        public string SystemId;
        [DataMember(Name = "x")]
        public double X;
        [DataMember(Name = "y")]
        public double Y;
        [DataMember(Name = "height")]
        public double Height;
        [DataMember(Name = "radius")]
        public double Radius;
        [DataMember(Name = "seed")]
        public uint Seed;

        public NearbyFieldAsteroid(
            string Id,
            string SystemId,
            double X,
            double Y,
            double Height,
            double Radius,
            uint Seed
        )
        {
            this.Id = Id;
            this.SystemId = SystemId;
            this.X = X;
            this.Y = Y;
            this.Height = Height;
            this.Radius = Radius;
            this.Seed = Seed;
        }

        public NearbyFieldAsteroid()
        {
            this.Id = "";
            this.SystemId = "";
        }
    }
}
