// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OperatorStockShipCargo
    {
        [DataMember(Name = "operation_id")]
        public string OperationId;
        [DataMember(Name = "dry_run")]
        public bool DryRun;
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "socket_key")]
        public string SocketKey;
        [DataMember(Name = "container_name")]
        public string ContainerName;
        [DataMember(Name = "definition_ids_json")]
        public string DefinitionIdsJson;

        public OperatorStockShipCargo(
            string OperationId,
            bool DryRun,
            string CharacterId,
            string ShipId,
            string SocketKey,
            string ContainerName,
            string DefinitionIdsJson
        )
        {
            this.OperationId = OperationId;
            this.DryRun = DryRun;
            this.CharacterId = CharacterId;
            this.ShipId = ShipId;
            this.SocketKey = SocketKey;
            this.ContainerName = ContainerName;
            this.DefinitionIdsJson = DefinitionIdsJson;
        }

        public OperatorStockShipCargo()
        {
            this.OperationId = "";
            this.CharacterId = "";
            this.ShipId = "";
            this.SocketKey = "";
            this.ContainerName = "";
            this.DefinitionIdsJson = "";
        }
    }
}
