// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OperatorImportContentSeed
    {
        [DataMember(Name = "operation_id")]
        public string OperationId;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "dry_run")]
        public bool DryRun;

        public OperatorImportContentSeed(
            string OperationId,
            string Kind,
            bool DryRun
        )
        {
            this.OperationId = OperationId;
            this.Kind = Kind;
            this.DryRun = DryRun;
        }

        public OperatorImportContentSeed()
        {
            this.OperationId = "";
            this.Kind = "";
        }
    }
}
