// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OperatorResyncItemDefinitions
    {
        [DataMember(Name = "operation_id")]
        public string OperationId;
        [DataMember(Name = "definition_id")]
        public string DefinitionId;
        [DataMember(Name = "item_revision")]
        public ulong ItemRevision;
        [DataMember(Name = "weapon_revision")]
        public ulong WeaponRevision;
        [DataMember(Name = "item_ids_json")]
        public string ItemIdsJson;
        [DataMember(Name = "dry_run")]
        public bool DryRun;

        public OperatorResyncItemDefinitions(
            string OperationId,
            string DefinitionId,
            ulong ItemRevision,
            ulong WeaponRevision,
            string ItemIdsJson,
            bool DryRun
        )
        {
            this.OperationId = OperationId;
            this.DefinitionId = DefinitionId;
            this.ItemRevision = ItemRevision;
            this.WeaponRevision = WeaponRevision;
            this.ItemIdsJson = ItemIdsJson;
            this.DryRun = DryRun;
        }

        public OperatorResyncItemDefinitions()
        {
            this.OperationId = "";
            this.DefinitionId = "";
            this.ItemIdsJson = "";
        }
    }
}
