// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OwnConstructionSeatStatus
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "object_id")]
        public string ObjectId;
        [DataMember(Name = "local_x")]
        public double LocalX;
        [DataMember(Name = "local_y")]
        public double LocalY;
        [DataMember(Name = "standing_elevation_m")]
        public double StandingElevationM;
        [DataMember(Name = "release_pending")]
        public bool ReleasePending;

        public OwnConstructionSeatStatus(
            string CharacterId,
            string InstanceId,
            string DeckId,
            string ObjectId,
            double LocalX,
            double LocalY,
            double StandingElevationM,
            bool ReleasePending
        )
        {
            this.CharacterId = CharacterId;
            this.InstanceId = InstanceId;
            this.DeckId = DeckId;
            this.ObjectId = ObjectId;
            this.LocalX = LocalX;
            this.LocalY = LocalY;
            this.StandingElevationM = StandingElevationM;
            this.ReleasePending = ReleasePending;
        }

        public OwnConstructionSeatStatus()
        {
            this.CharacterId = "";
            this.InstanceId = "";
            this.DeckId = "";
            this.ObjectId = "";
        }
    }
}
