// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PassengerVisitStatus
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "visit_id")]
        public string VisitId;
        [DataMember(Name = "grant_id")]
        public string GrantId;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "admitted")]
        public bool Admitted;
        [DataMember(Name = "recovery_reason")]
        public string RecoveryReason;

        public PassengerVisitStatus(
            string CharacterId,
            string ShipId,
            string DeckId,
            string VisitId,
            string GrantId,
            ulong Revision,
            bool Admitted,
            string RecoveryReason
        )
        {
            this.CharacterId = CharacterId;
            this.ShipId = ShipId;
            this.DeckId = DeckId;
            this.VisitId = VisitId;
            this.GrantId = GrantId;
            this.Revision = Revision;
            this.Admitted = Admitted;
            this.RecoveryReason = RecoveryReason;
        }

        public PassengerVisitStatus()
        {
            this.CharacterId = "";
            this.ShipId = "";
            this.DeckId = "";
            this.VisitId = "";
            this.GrantId = "";
            this.RecoveryReason = "";
        }
    }
}
