// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PassengerAdmission
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "grantee_id")]
        public string GranteeId;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "instance_revision")]
        public ulong InstanceRevision;
        [DataMember(Name = "expires_micros")]
        public ulong ExpiresMicros;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "issued_by_you")]
        public bool IssuedByYou;

        public PassengerAdmission(
            string Id,
            string ShipId,
            string GranteeId,
            string DeckId,
            ulong InstanceRevision,
            ulong ExpiresMicros,
            ulong Revision,
            bool IssuedByYou
        )
        {
            this.Id = Id;
            this.ShipId = ShipId;
            this.GranteeId = GranteeId;
            this.DeckId = DeckId;
            this.InstanceRevision = InstanceRevision;
            this.ExpiresMicros = ExpiresMicros;
            this.Revision = Revision;
            this.IssuedByYou = IssuedByYou;
        }

        public PassengerAdmission()
        {
            this.Id = "";
            this.ShipId = "";
            this.GranteeId = "";
            this.DeckId = "";
        }
    }
}
