// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PublishedItemDefinition
    {
        [DataMember(Name = "definition_ref")]
        public string DefinitionRef;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "definition_id")]
        public string DefinitionId;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "status")]
        public string Status;
        [DataMember(Name = "payload_json")]
        public string PayloadJson;
        [DataMember(Name = "sha_256")]
        public string Sha256;

        public PublishedItemDefinition(
            string DefinitionRef,
            string Kind,
            string DefinitionId,
            ulong Revision,
            string Status,
            string PayloadJson,
            string Sha256
        )
        {
            this.DefinitionRef = DefinitionRef;
            this.Kind = Kind;
            this.DefinitionId = DefinitionId;
            this.Revision = Revision;
            this.Status = Status;
            this.PayloadJson = PayloadJson;
            this.Sha256 = Sha256;
        }

        public PublishedItemDefinition()
        {
            this.DefinitionRef = "";
            this.Kind = "";
            this.DefinitionId = "";
            this.Status = "";
            this.PayloadJson = "";
            this.Sha256 = "";
        }
    }
}
