// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RefreshDefinitionUsage
    {
        [DataMember(Name = "kind")]
        public string Kind;

        public RefreshDefinitionUsage(string Kind)
        {
            this.Kind = Kind;
        }

        public RefreshDefinitionUsage()
        {
            this.Kind = "";
        }
    }
}
