// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ReloadWeapon
    {
        [DataMember(Name = "item_id")]
        public string ItemId;
        [DataMember(Name = "expected_revision")]
        public ulong ExpectedRevision;
        [DataMember(Name = "operation_id")]
        public string OperationId;

        public ReloadWeapon(
            string ItemId,
            ulong ExpectedRevision,
            string OperationId
        )
        {
            this.ItemId = ItemId;
            this.ExpectedRevision = ExpectedRevision;
            this.OperationId = OperationId;
        }

        public ReloadWeapon()
        {
            this.ItemId = "";
            this.OperationId = "";
        }
    }
}
