// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RenameShip
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "expected_revision")]
        public ulong ExpectedRevision;
        [DataMember(Name = "operation_id")]
        public string OperationId;
        [DataMember(Name = "name")]
        public string Name;

        public RenameShip(
            string ShipId,
            ulong ExpectedRevision,
            string OperationId,
            string Name
        )
        {
            this.ShipId = ShipId;
            this.ExpectedRevision = ExpectedRevision;
            this.OperationId = OperationId;
            this.Name = Name;
        }

        public RenameShip()
        {
            this.ShipId = "";
            this.OperationId = "";
            this.Name = "";
        }
    }
}
