// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ReturnAuthoredFlightReview
    {
        [DataMember(Name = "expected_visit_id")]
        public string ExpectedVisitId;
        [DataMember(Name = "expected_visit_revision")]
        public ulong ExpectedVisitRevision;
        [DataMember(Name = "expected_admission_revision")]
        public ulong ExpectedAdmissionRevision;
        [DataMember(Name = "operation_id")]
        public string OperationId;

        public ReturnAuthoredFlightReview(
            string ExpectedVisitId,
            ulong ExpectedVisitRevision,
            ulong ExpectedAdmissionRevision,
            string OperationId
        )
        {
            this.ExpectedVisitId = ExpectedVisitId;
            this.ExpectedVisitRevision = ExpectedVisitRevision;
            this.ExpectedAdmissionRevision = ExpectedAdmissionRevision;
            this.OperationId = OperationId;
        }

        public ReturnAuthoredFlightReview()
        {
            this.ExpectedVisitId = "";
            this.OperationId = "";
        }
    }
}
