// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SaveConstructionDraft
    {
        [DataMember(Name = "workspace_id")]
        public string WorkspaceId;
        [DataMember(Name = "draft_id")]
        public string DraftId;
        [DataMember(Name = "document_json")]
        public string DocumentJson;
        [DataMember(Name = "expected_revision")]
        public ulong ExpectedRevision;
        [DataMember(Name = "operation_id")]
        public string OperationId;

        public SaveConstructionDraft(
            string WorkspaceId,
            string DraftId,
            string DocumentJson,
            ulong ExpectedRevision,
            string OperationId
        )
        {
            this.WorkspaceId = WorkspaceId;
            this.DraftId = DraftId;
            this.DocumentJson = DocumentJson;
            this.ExpectedRevision = ExpectedRevision;
            this.OperationId = OperationId;
        }

        public SaveConstructionDraft()
        {
            this.WorkspaceId = "";
            this.DraftId = "";
            this.DocumentJson = "";
            this.OperationId = "";
        }
    }
}
