// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SaveDefinitionDraft
    {
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "definition_id")]
        public string DefinitionId;
        [DataMember(Name = "payload_json")]
        public string PayloadJson;
        [DataMember(Name = "expected_revision")]
        public ulong ExpectedRevision;
        [DataMember(Name = "operation_id")]
        public string OperationId;

        public SaveDefinitionDraft(
            string Kind,
            string DefinitionId,
            string PayloadJson,
            ulong ExpectedRevision,
            string OperationId
        )
        {
            this.Kind = Kind;
            this.DefinitionId = DefinitionId;
            this.PayloadJson = PayloadJson;
            this.ExpectedRevision = ExpectedRevision;
            this.OperationId = OperationId;
        }

        public SaveDefinitionDraft()
        {
            this.Kind = "";
            this.DefinitionId = "";
            this.PayloadJson = "";
            this.OperationId = "";
        }
    }
}
