// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ScopedCargoItemStatus
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "definition_id")]
        public string DefinitionId;
        [DataMember(Name = "container_id")]
        public string ContainerId;
        [DataMember(Name = "x")]
        public int X;
        [DataMember(Name = "y")]
        public int Y;
        [DataMember(Name = "rotated")]
        public bool Rotated;
        [DataMember(Name = "revision")]
        public ulong Revision;

        public ScopedCargoItemStatus(
            string Id,
            string DefinitionId,
            string ContainerId,
            int X,
            int Y,
            bool Rotated,
            ulong Revision
        )
        {
            this.Id = Id;
            this.DefinitionId = DefinitionId;
            this.ContainerId = ContainerId;
            this.X = X;
            this.Y = Y;
            this.Rotated = Rotated;
            this.Revision = Revision;
        }

        public ScopedCargoItemStatus()
        {
            this.Id = "";
            this.DefinitionId = "";
            this.ContainerId = "";
        }
    }
}
