// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ScopedCarriedInventoryRevision
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "revision")]
        public ulong Revision;

        public ScopedCarriedInventoryRevision(
            string Id,
            string Kind,
            ulong Revision
        )
        {
            this.Id = Id;
            this.Kind = Kind;
            this.Revision = Revision;
        }

        public ScopedCarriedInventoryRevision()
        {
            this.Id = "";
            this.Kind = "";
        }
    }
}
