// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SetConstructionEnginePower
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "engine_placed_object_id")]
        public string EnginePlacedObjectId;
        [DataMember(Name = "connected")]
        public bool Connected;
        [DataMember(Name = "expected_revision")]
        public ulong ExpectedRevision;
        [DataMember(Name = "operation_id")]
        public string OperationId;

        public SetConstructionEnginePower(
            string ShipId,
            string EnginePlacedObjectId,
            bool Connected,
            ulong ExpectedRevision,
            string OperationId
        )
        {
            this.ShipId = ShipId;
            this.EnginePlacedObjectId = EnginePlacedObjectId;
            this.Connected = Connected;
            this.ExpectedRevision = ExpectedRevision;
            this.OperationId = OperationId;
        }

        public SetConstructionEnginePower()
        {
            this.ShipId = "";
            this.EnginePlacedObjectId = "";
            this.OperationId = "";
        }
    }
}
