// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SetIntent
    {
        [DataMember(Name = "sequence")]
        public ulong Sequence;
        [DataMember(Name = "throttle")]
        public double Throttle;
        [DataMember(Name = "turn")]
        public double Turn;
        [DataMember(Name = "dx")]
        public double Dx;
        [DataMember(Name = "dy")]
        public double Dy;
        [DataMember(Name = "sprint")]
        public bool Sprint;

        public SetIntent(
            ulong Sequence,
            double Throttle,
            double Turn,
            double Dx,
            double Dy,
            bool Sprint
        )
        {
            this.Sequence = Sequence;
            this.Throttle = Throttle;
            this.Turn = Turn;
            this.Dx = Dx;
            this.Dy = Dy;
            this.Sprint = Sprint;
        }

        public SetIntent()
        {
        }
    }
}
