// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SharedShipDescriptionProjection
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "published_exterior_asset_id")]
        public string PublishedExteriorAssetId;
        [DataMember(Name = "appearance_revision")]
        public ulong AppearanceRevision;
        [DataMember(Name = "display_name")]
        public string DisplayName;

        public SharedShipDescriptionProjection(
            string ShipId,
            string PublishedExteriorAssetId,
            ulong AppearanceRevision,
            string DisplayName
        )
        {
            this.ShipId = ShipId;
            this.PublishedExteriorAssetId = PublishedExteriorAssetId;
            this.AppearanceRevision = AppearanceRevision;
            this.DisplayName = DisplayName;
        }

        public SharedShipDescriptionProjection()
        {
            this.ShipId = "";
            this.PublishedExteriorAssetId = "";
            this.DisplayName = "";
        }
    }
}
