// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SharedBodyDescriptionProjection
    {
        [DataMember(Name = "body_id")]
        public string BodyId;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "appearance")]
        public string Appearance;
        [DataMember(Name = "seed")]
        public uint Seed;
        [DataMember(Name = "radius")]
        public double Radius;
        [DataMember(Name = "height")]
        public double Height;

        public SharedBodyDescriptionProjection(
            string BodyId,
            string Kind,
            string Appearance,
            uint Seed,
            double Radius,
            double Height
        )
        {
            this.BodyId = BodyId;
            this.Kind = Kind;
            this.Appearance = Appearance;
            this.Seed = Seed;
            this.Radius = Radius;
            this.Height = Height;
        }

        public SharedBodyDescriptionProjection()
        {
            this.BodyId = "";
            this.Kind = "";
            this.Appearance = "";
        }
    }
}
