// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SharedAdmissionProjection
    {
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "system_id")]
        public string SystemId;
        [DataMember(Name = "revision")]
        public ulong Revision;

        public SharedAdmissionProjection(
            string CharacterId,
            string ShipId,
            string SystemId,
            ulong Revision
        )
        {
            this.CharacterId = CharacterId;
            this.ShipId = ShipId;
            this.SystemId = SystemId;
            this.Revision = Revision;
        }

        public SharedAdmissionProjection()
        {
            this.CharacterId = "";
            this.ShipId = "";
            this.SystemId = "";
        }
    }
}
