// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShipPowerState
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "instance_revision")]
        public ulong InstanceRevision;
        [DataMember(Name = "input_hash")]
        public string InputHash;
        [DataMember(Name = "tick")]
        public ulong Tick;
        [DataMember(Name = "solved_micros")]
        public ulong SolvedMicros;
        [DataMember(Name = "energy_j")]
        public double EnergyJ;
        [DataMember(Name = "generation_w")]
        public double GenerationW;
        [DataMember(Name = "demand_w")]
        public double DemandW;
        [DataMember(Name = "brownout")]
        public bool Brownout;
        [DataMember(Name = "core_powered")]
        public bool CorePowered;
        [DataMember(Name = "supply_json")]
        public string SupplyJson;
        [DataMember(Name = "networks_json")]
        public string NetworksJson;

        public ShipPowerState(
            string ShipId,
            ulong InstanceRevision,
            string InputHash,
            ulong Tick,
            ulong SolvedMicros,
            double EnergyJ,
            double GenerationW,
            double DemandW,
            bool Brownout,
            bool CorePowered,
            string SupplyJson,
            string NetworksJson
        )
        {
            this.ShipId = ShipId;
            this.InstanceRevision = InstanceRevision;
            this.InputHash = InputHash;
            this.Tick = Tick;
            this.SolvedMicros = SolvedMicros;
            this.EnergyJ = EnergyJ;
            this.GenerationW = GenerationW;
            this.DemandW = DemandW;
            this.Brownout = Brownout;
            this.CorePowered = CorePowered;
            this.SupplyJson = SupplyJson;
            this.NetworksJson = NetworksJson;
        }

        public ShipPowerState()
        {
            this.ShipId = "";
            this.InputHash = "";
            this.SupplyJson = "";
            this.NetworksJson = "";
        }
    }
}
