// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Ship
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "x")]
        public double X;
        [DataMember(Name = "y")]
        public double Y;
        [DataMember(Name = "vx")]
        public double Vx;
        [DataMember(Name = "vy")]
        public double Vy;
        [DataMember(Name = "heading")]
        public double Heading;
        [DataMember(Name = "omega")]
        public double Omega;
        [DataMember(Name = "mass_kg")]
        public double MassKg;
        [DataMember(Name = "thrust_n")]
        public double ThrustN;
        [DataMember(Name = "turn_acceleration")]
        public double TurnAcceleration;
        [DataMember(Name = "tick")]
        public ulong Tick;

        public Ship(
            string Id,
            SpacetimeDB.Identity Owner,
            string Name,
            ulong Revision,
            double X,
            double Y,
            double Vx,
            double Vy,
            double Heading,
            double Omega,
            double MassKg,
            double ThrustN,
            double TurnAcceleration,
            ulong Tick
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.Name = Name;
            this.Revision = Revision;
            this.X = X;
            this.Y = Y;
            this.Vx = Vx;
            this.Vy = Vy;
            this.Heading = Heading;
            this.Omega = Omega;
            this.MassKg = MassKg;
            this.ThrustN = ThrustN;
            this.TurnAcceleration = TurnAcceleration;
            this.Tick = Tick;
        }

        public Ship()
        {
            this.Id = "";
            this.Name = "";
        }
    }
}
