// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShipLogicState
    {
        [DataMember(Name = "key")]
        public string Key;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "device_id")]
        public string DeviceId;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "instance_revision")]
        public ulong InstanceRevision;
        [DataMember(Name = "state_json")]
        public string StateJson;
        [DataMember(Name = "updated_micros")]
        public ulong UpdatedMicros;

        public ShipLogicState(
            string Key,
            string ShipId,
            string DeviceId,
            string Kind,
            ulong InstanceRevision,
            string StateJson,
            ulong UpdatedMicros
        )
        {
            this.Key = Key;
            this.ShipId = ShipId;
            this.DeviceId = DeviceId;
            this.Kind = Kind;
            this.InstanceRevision = InstanceRevision;
            this.StateJson = StateJson;
            this.UpdatedMicros = UpdatedMicros;
        }

        public ShipLogicState()
        {
            this.Key = "";
            this.ShipId = "";
            this.DeviceId = "";
            this.Kind = "";
            this.StateJson = "";
        }
    }
}
