// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShipSystemsState
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "instance_revision")]
        public ulong InstanceRevision;
        [DataMember(Name = "catalog")]
        public string Catalog;
        [DataMember(Name = "prefab_id")]
        public string PrefabId;
        [DataMember(Name = "prefab_revision")]
        public uint PrefabRevision;
        [DataMember(Name = "input_hash")]
        public string InputHash;
        [DataMember(Name = "compile_revision")]
        public ulong CompileRevision;
        [DataMember(Name = "status")]
        public string Status;
        [DataMember(Name = "errors")]
        public uint Errors;
        [DataMember(Name = "warnings")]
        public uint Warnings;
        [DataMember(Name = "mass_kg")]
        public double MassKg;
        [DataMember(Name = "generation_kw")]
        public double GenerationKw;
        [DataMember(Name = "storage_kwh")]
        public double StorageKwh;
        [DataMember(Name = "cruise_demand_kw")]
        public double CruiseDemandKw;
        [DataMember(Name = "cruise_balance_kw")]
        public double CruiseBalanceKw;
        [DataMember(Name = "cruise_brownout")]
        public bool CruiseBrownout;
        [DataMember(Name = "combat_demand_kw")]
        public double CombatDemandKw;
        [DataMember(Name = "combat_balance_kw")]
        public double CombatBalanceKw;
        [DataMember(Name = "combat_brownout")]
        public bool CombatBrownout;
        [DataMember(Name = "combat_battery_endurance_s")]
        public double? CombatBatteryEnduranceS;
        [DataMember(Name = "cruise_heat_balance_kw")]
        public double CruiseHeatBalanceKw;
        [DataMember(Name = "combat_heat_balance_kw")]
        public double CombatHeatBalanceKw;
        [DataMember(Name = "combat_overheat_s")]
        public double? CombatOverheatS;
        [DataMember(Name = "coolant_supply_lps")]
        public double CoolantSupplyLps;
        [DataMember(Name = "coolant_demand_lps")]
        public double CoolantDemandLps;
        [DataMember(Name = "fuel_capacity_l")]
        public double FuelCapacityL;
        [DataMember(Name = "fuel_loaded_l")]
        public double FuelLoadedL;
        [DataMember(Name = "cruise_fuel_endurance_s")]
        public double? CruiseFuelEnduranceS;
        [DataMember(Name = "data_supply_kbps")]
        public double DataSupplyKbps;
        [DataMember(Name = "data_demand_kbps")]
        public double DataDemandKbps;
        [DataMember(Name = "control_slots")]
        public uint ControlSlots;
        [DataMember(Name = "control_slots_used")]
        public uint ControlSlotsUsed;
        [DataMember(Name = "minimum_crew")]
        public uint MinimumCrew;
        [DataMember(Name = "life_support_crew")]
        public double LifeSupportCrew;
        [DataMember(Name = "oxygen_reserve_hours")]
        public double? OxygenReserveHours;
        [DataMember(Name = "forward_kn")]
        public double ForwardKn;
        [DataMember(Name = "forward_accel")]
        public double ForwardAccel;
        [DataMember(Name = "damaged_components")]
        public uint DamagedComponents;
        [DataMember(Name = "destroyed_components")]
        public uint DestroyedComponents;
        [DataMember(Name = "report_json")]
        public string ReportJson;
        [DataMember(Name = "compiled_micros")]
        public ulong CompiledMicros;

        public ShipSystemsState(
            string ShipId,
            ulong InstanceRevision,
            string Catalog,
            string PrefabId,
            uint PrefabRevision,
            string InputHash,
            ulong CompileRevision,
            string Status,
            uint Errors,
            uint Warnings,
            double MassKg,
            double GenerationKw,
            double StorageKwh,
            double CruiseDemandKw,
            double CruiseBalanceKw,
            bool CruiseBrownout,
            double CombatDemandKw,
            double CombatBalanceKw,
            bool CombatBrownout,
            double? CombatBatteryEnduranceS,
            double CruiseHeatBalanceKw,
            double CombatHeatBalanceKw,
            double? CombatOverheatS,
            double CoolantSupplyLps,
            double CoolantDemandLps,
            double FuelCapacityL,
            double FuelLoadedL,
            double? CruiseFuelEnduranceS,
            double DataSupplyKbps,
            double DataDemandKbps,
            uint ControlSlots,
            uint ControlSlotsUsed,
            uint MinimumCrew,
            double LifeSupportCrew,
            double? OxygenReserveHours,
            double ForwardKn,
            double ForwardAccel,
            uint DamagedComponents,
            uint DestroyedComponents,
            string ReportJson,
            ulong CompiledMicros
        )
        {
            this.ShipId = ShipId;
            this.InstanceRevision = InstanceRevision;
            this.Catalog = Catalog;
            this.PrefabId = PrefabId;
            this.PrefabRevision = PrefabRevision;
            this.InputHash = InputHash;
            this.CompileRevision = CompileRevision;
            this.Status = Status;
            this.Errors = Errors;
            this.Warnings = Warnings;
            this.MassKg = MassKg;
            this.GenerationKw = GenerationKw;
            this.StorageKwh = StorageKwh;
            this.CruiseDemandKw = CruiseDemandKw;
            this.CruiseBalanceKw = CruiseBalanceKw;
            this.CruiseBrownout = CruiseBrownout;
            this.CombatDemandKw = CombatDemandKw;
            this.CombatBalanceKw = CombatBalanceKw;
            this.CombatBrownout = CombatBrownout;
            this.CombatBatteryEnduranceS = CombatBatteryEnduranceS;
            this.CruiseHeatBalanceKw = CruiseHeatBalanceKw;
            this.CombatHeatBalanceKw = CombatHeatBalanceKw;
            this.CombatOverheatS = CombatOverheatS;
            this.CoolantSupplyLps = CoolantSupplyLps;
            this.CoolantDemandLps = CoolantDemandLps;
            this.FuelCapacityL = FuelCapacityL;
            this.FuelLoadedL = FuelLoadedL;
            this.CruiseFuelEnduranceS = CruiseFuelEnduranceS;
            this.DataSupplyKbps = DataSupplyKbps;
            this.DataDemandKbps = DataDemandKbps;
            this.ControlSlots = ControlSlots;
            this.ControlSlotsUsed = ControlSlotsUsed;
            this.MinimumCrew = MinimumCrew;
            this.LifeSupportCrew = LifeSupportCrew;
            this.OxygenReserveHours = OxygenReserveHours;
            this.ForwardKn = ForwardKn;
            this.ForwardAccel = ForwardAccel;
            this.DamagedComponents = DamagedComponents;
            this.DestroyedComponents = DestroyedComponents;
            this.ReportJson = ReportJson;
            this.CompiledMicros = CompiledMicros;
        }

        public ShipSystemsState()
        {
            this.ShipId = "";
            this.Catalog = "";
            this.PrefabId = "";
            this.InputHash = "";
            this.Status = "";
            this.ReportJson = "";
        }
    }
}
