// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShipLogicTimer
    {
        [DataMember(Name = "key")]
        public string Key;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "device_id")]
        public string DeviceId;
        [DataMember(Name = "instance_revision")]
        public ulong InstanceRevision;
        [DataMember(Name = "due_micros")]
        public ulong DueMicros;

        public ShipLogicTimer(
            string Key,
            string ShipId,
            string DeviceId,
            ulong InstanceRevision,
            ulong DueMicros
        )
        {
            this.Key = Key;
            this.ShipId = ShipId;
            this.DeviceId = DeviceId;
            this.InstanceRevision = InstanceRevision;
            this.DueMicros = DueMicros;
        }

        public ShipLogicTimer()
        {
            this.Key = "";
            this.ShipId = "";
            this.DeviceId = "";
        }
    }
}
