// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShipSystemEffects
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "power")]
        public string Power;

        public ShipSystemEffects(
            string ShipId,
            string Power
        )
        {
            this.ShipId = ShipId;
            this.Power = Power;
        }

        public ShipSystemEffects()
        {
            this.ShipId = "";
            this.Power = "";
        }
    }
}
