// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShipSystemsDirty
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "reason")]
        public string Reason;

        public ShipSystemsDirty(
            string ShipId,
            ulong Revision,
            string Reason
        )
        {
            this.ShipId = ShipId;
            this.Revision = Revision;
            this.Reason = Reason;
        }

        public ShipSystemsDirty()
        {
            this.ShipId = "";
            this.Reason = "";
        }
    }
}
