// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShipOperatorOperation
    {
        [DataMember(Name = "operation_id")]
        public string OperationId;
        [DataMember(Name = "principal")]
        public SpacetimeDB.Identity Principal;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "request")]
        public string Request;
        [DataMember(Name = "summary_json")]
        public string SummaryJson;
        [DataMember(Name = "created_micros")]
        public ulong CreatedMicros;

        public ShipOperatorOperation(
            string OperationId,
            SpacetimeDB.Identity Principal,
            string Kind,
            string Request,
            string SummaryJson,
            ulong CreatedMicros
        )
        {
            this.OperationId = OperationId;
            this.Principal = Principal;
            this.Kind = Kind;
            this.Request = Request;
            this.SummaryJson = SummaryJson;
            this.CreatedMicros = CreatedMicros;
        }

        public ShipOperatorOperation()
        {
            this.OperationId = "";
            this.Kind = "";
            this.Request = "";
            this.SummaryJson = "";
        }
    }
}
