// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShipZoneProjection
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "system_id")]
        public string SystemId;
        [DataMember(Name = "map_revision")]
        public ulong MapRevision;
        [DataMember(Name = "state_revision")]
        public ulong StateRevision;
        [DataMember(Name = "sequence")]
        public ulong Sequence;
        [DataMember(Name = "earliest_sequence")]
        public ulong EarliestSequence;
        [DataMember(Name = "active_json")]
        public string ActiveJson;
        [DataMember(Name = "transitions_json")]
        public string TransitionsJson;

        public ShipZoneProjection(
            string ShipId,
            string SystemId,
            ulong MapRevision,
            ulong StateRevision,
            ulong Sequence,
            ulong EarliestSequence,
            string ActiveJson,
            string TransitionsJson
        )
        {
            this.ShipId = ShipId;
            this.SystemId = SystemId;
            this.MapRevision = MapRevision;
            this.StateRevision = StateRevision;
            this.Sequence = Sequence;
            this.EarliestSequence = EarliestSequence;
            this.ActiveJson = ActiveJson;
            this.TransitionsJson = TransitionsJson;
        }

        public ShipZoneProjection()
        {
            this.ShipId = "";
            this.SystemId = "";
            this.ActiveJson = "";
            this.TransitionsJson = "";
        }
    }
}
