// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShipPowerInstallation
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "initialized_micros")]
        public ulong InitializedMicros;
        [DataMember(Name = "policy")]
        public string Policy;
        [DataMember(Name = "last_solved_tick")]
        public ulong LastSolvedTick;

        public ShipPowerInstallation(
            string ShipId,
            ulong InitializedMicros,
            string Policy,
            ulong LastSolvedTick
        )
        {
            this.ShipId = ShipId;
            this.InitializedMicros = InitializedMicros;
            this.Policy = Policy;
            this.LastSolvedTick = LastSolvedTick;
        }

        public ShipPowerInstallation()
        {
            this.ShipId = "";
            this.Policy = "";
        }
    }
}
