// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShipComponentDamage
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "object_id")]
        public string ObjectId;
        [DataMember(Name = "component_id")]
        public string ComponentId;
        [DataMember(Name = "catalog")]
        public string Catalog;
        [DataMember(Name = "hp")]
        public double Hp;
        [DataMember(Name = "max_hp")]
        public double MaxHp;
        [DataMember(Name = "state")]
        public string State;
        [DataMember(Name = "performance")]
        public double Performance;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "updated_micros")]
        public ulong UpdatedMicros;

        public ShipComponentDamage(
            string Id,
            string ShipId,
            string ObjectId,
            string ComponentId,
            string Catalog,
            double Hp,
            double MaxHp,
            string State,
            double Performance,
            ulong Revision,
            ulong UpdatedMicros
        )
        {
            this.Id = Id;
            this.ShipId = ShipId;
            this.ObjectId = ObjectId;
            this.ComponentId = ComponentId;
            this.Catalog = Catalog;
            this.Hp = Hp;
            this.MaxHp = MaxHp;
            this.State = State;
            this.Performance = Performance;
            this.Revision = Revision;
            this.UpdatedMicros = UpdatedMicros;
        }

        public ShipComponentDamage()
        {
            this.Id = "";
            this.ShipId = "";
            this.ObjectId = "";
            this.ComponentId = "";
            this.Catalog = "";
            this.State = "";
        }
    }
}
