// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShipPolicy
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "starter_prefab_id")]
        public string StarterPrefabId;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "operation_id")]
        public string OperationId;
        [DataMember(Name = "updated_micros")]
        public ulong UpdatedMicros;

        public ShipPolicy(
            string Id,
            string StarterPrefabId,
            ulong Revision,
            string OperationId,
            ulong UpdatedMicros
        )
        {
            this.Id = Id;
            this.StarterPrefabId = StarterPrefabId;
            this.Revision = Revision;
            this.OperationId = OperationId;
            this.UpdatedMicros = UpdatedMicros;
        }

        public ShipPolicy()
        {
            this.Id = "";
            this.StarterPrefabId = "";
            this.OperationId = "";
        }
    }
}
