// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SpawnConstructionBlueprint
    {
        [DataMember(Name = "blueprint_id")]
        public string BlueprintId;
        [DataMember(Name = "expected_sha_256")]
        public string ExpectedSha256;
        [DataMember(Name = "source_deck_id")]
        public string SourceDeckId;
        [DataMember(Name = "operation_id")]
        public string OperationId;

        public SpawnConstructionBlueprint(
            string BlueprintId,
            string ExpectedSha256,
            string SourceDeckId,
            string OperationId
        )
        {
            this.BlueprintId = BlueprintId;
            this.ExpectedSha256 = ExpectedSha256;
            this.SourceDeckId = SourceDeckId;
            this.OperationId = OperationId;
        }

        public SpawnConstructionBlueprint()
        {
            this.BlueprintId = "";
            this.ExpectedSha256 = "";
            this.SourceDeckId = "";
            this.OperationId = "";
        }
    }
}
