// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SwitchConstructionReview
    {
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "expected_instance_revision")]
        public ulong ExpectedInstanceRevision;
        [DataMember(Name = "expected_visit_id")]
        public string ExpectedVisitId;
        [DataMember(Name = "expected_revision")]
        public ulong ExpectedRevision;
        [DataMember(Name = "operation_id")]
        public string OperationId;

        public SwitchConstructionReview(
            string InstanceId,
            ulong ExpectedInstanceRevision,
            string ExpectedVisitId,
            ulong ExpectedRevision,
            string OperationId
        )
        {
            this.InstanceId = InstanceId;
            this.ExpectedInstanceRevision = ExpectedInstanceRevision;
            this.ExpectedVisitId = ExpectedVisitId;
            this.ExpectedRevision = ExpectedRevision;
            this.OperationId = OperationId;
        }

        public SwitchConstructionReview()
        {
            this.InstanceId = "";
            this.ExpectedVisitId = "";
            this.OperationId = "";
        }
    }
}
