// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SystemZone
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "system_id")]
        public string SystemId;
        [DataMember(Name = "zone_id")]
        public string ZoneId;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "definition_json")]
        public string DefinitionJson;

        public SystemZone(
            string Id,
            string SystemId,
            string ZoneId,
            ulong Revision,
            string DefinitionJson
        )
        {
            this.Id = Id;
            this.SystemId = SystemId;
            this.ZoneId = ZoneId;
            this.Revision = Revision;
            this.DefinitionJson = DefinitionJson;
        }

        public SystemZone()
        {
            this.Id = "";
            this.SystemId = "";
            this.ZoneId = "";
            this.DefinitionJson = "";
        }
    }
}
