// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SystemMapEdit
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "system_id")]
        public string SystemId;
        [DataMember(Name = "principal")]
        public SpacetimeDB.Identity Principal;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "before_json")]
        public string BeforeJson;
        [DataMember(Name = "after_json")]
        public string AfterJson;
        [DataMember(Name = "created_micros")]
        public ulong CreatedMicros;

        public SystemMapEdit(
            string Id,
            string SystemId,
            SpacetimeDB.Identity Principal,
            ulong Revision,
            string BeforeJson,
            string AfterJson,
            ulong CreatedMicros
        )
        {
            this.Id = Id;
            this.SystemId = SystemId;
            this.Principal = Principal;
            this.Revision = Revision;
            this.BeforeJson = BeforeJson;
            this.AfterJson = AfterJson;
            this.CreatedMicros = CreatedMicros;
        }

        public SystemMapEdit()
        {
            this.Id = "";
            this.SystemId = "";
            this.BeforeJson = "";
            this.AfterJson = "";
        }
    }
}
