// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TransferScopedCargoItem
    {
        [DataMember(Name = "operation_id")]
        public string OperationId;
        [DataMember(Name = "item_id")]
        public string ItemId;
        [DataMember(Name = "expected_item_revision")]
        public ulong ExpectedItemRevision;
        [DataMember(Name = "source_container_id")]
        public string SourceContainerId;
        [DataMember(Name = "expected_source_revision")]
        public ulong ExpectedSourceRevision;
        [DataMember(Name = "destination_container_id")]
        public string DestinationContainerId;
        [DataMember(Name = "expected_destination_revision")]
        public ulong ExpectedDestinationRevision;
        [DataMember(Name = "expected_character_revision")]
        public ulong ExpectedCharacterRevision;
        [DataMember(Name = "x")]
        public int X;
        [DataMember(Name = "y")]
        public int Y;
        [DataMember(Name = "rotated")]
        public bool Rotated;

        public TransferScopedCargoItem(
            string OperationId,
            string ItemId,
            ulong ExpectedItemRevision,
            string SourceContainerId,
            ulong ExpectedSourceRevision,
            string DestinationContainerId,
            ulong ExpectedDestinationRevision,
            ulong ExpectedCharacterRevision,
            int X,
            int Y,
            bool Rotated
        )
        {
            this.OperationId = OperationId;
            this.ItemId = ItemId;
            this.ExpectedItemRevision = ExpectedItemRevision;
            this.SourceContainerId = SourceContainerId;
            this.ExpectedSourceRevision = ExpectedSourceRevision;
            this.DestinationContainerId = DestinationContainerId;
            this.ExpectedDestinationRevision = ExpectedDestinationRevision;
            this.ExpectedCharacterRevision = ExpectedCharacterRevision;
            this.X = X;
            this.Y = Y;
            this.Rotated = Rotated;
        }

        public TransferScopedCargoItem()
        {
            this.OperationId = "";
            this.ItemId = "";
            this.SourceContainerId = "";
            this.DestinationContainerId = "";
        }
    }
}
