// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VisibleInventoryContainer
    {
        [DataMember(Name = "placement_id")]
        public string PlacementId;
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "parent_item_id")]
        public string ParentItemId;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "width")]
        public uint Width;
        [DataMember(Name = "height")]
        public uint Height;
        [DataMember(Name = "max_mass_kg")]
        public double MaxMassKg;
        [DataMember(Name = "capacity_litres")]
        public double CapacityLitres;
        [DataMember(Name = "amount_litres")]
        public double AmountLitres;
        [DataMember(Name = "liquid_type")]
        public string LiquidType;
        [DataMember(Name = "carried")]
        public bool Carried;

        public VisibleInventoryContainer(
            string PlacementId,
            string Id,
            string ParentItemId,
            string Kind,
            string Name,
            uint Width,
            uint Height,
            double MaxMassKg,
            double CapacityLitres,
            double AmountLitres,
            string LiquidType,
            bool Carried
        )
        {
            this.PlacementId = PlacementId;
            this.Id = Id;
            this.ParentItemId = ParentItemId;
            this.Kind = Kind;
            this.Name = Name;
            this.Width = Width;
            this.Height = Height;
            this.MaxMassKg = MaxMassKg;
            this.CapacityLitres = CapacityLitres;
            this.AmountLitres = AmountLitres;
            this.LiquidType = LiquidType;
            this.Carried = Carried;
        }

        public VisibleInventoryContainer()
        {
            this.PlacementId = "";
            this.Id = "";
            this.ParentItemId = "";
            this.Kind = "";
            this.Name = "";
            this.LiquidType = "";
        }
    }
}
