// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VisibleIdentityLink
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "character_name")]
        public string CharacterName;
        [DataMember(Name = "source_identity")]
        public string SourceIdentity;
        [DataMember(Name = "target_identity")]
        public string TargetIdentity;
        [DataMember(Name = "expires_micros")]
        public ulong ExpiresMicros;
        [DataMember(Name = "status")]
        public string Status;
        [DataMember(Name = "side")]
        public string Side;

        public VisibleIdentityLink(
            string Id,
            string CharacterId,
            string CharacterName,
            string SourceIdentity,
            string TargetIdentity,
            ulong ExpiresMicros,
            string Status,
            string Side
        )
        {
            this.Id = Id;
            this.CharacterId = CharacterId;
            this.CharacterName = CharacterName;
            this.SourceIdentity = SourceIdentity;
            this.TargetIdentity = TargetIdentity;
            this.ExpiresMicros = ExpiresMicros;
            this.Status = Status;
            this.Side = Side;
        }

        public VisibleIdentityLink()
        {
            this.Id = "";
            this.CharacterId = "";
            this.CharacterName = "";
            this.SourceIdentity = "";
            this.TargetIdentity = "";
            this.Status = "";
            this.Side = "";
        }
    }
}
