// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VisibleGroundItem
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "definition_id")]
        public string DefinitionId;
        [DataMember(Name = "local_x")]
        public double LocalX;
        [DataMember(Name = "local_y")]
        public double LocalY;
        [DataMember(Name = "reachable")]
        public bool Reachable;
        [DataMember(Name = "instance_id")]
        public string InstanceId;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "elevation_m")]
        public double ElevationM;

        public VisibleGroundItem(
            string Id,
            string DefinitionId,
            double LocalX,
            double LocalY,
            bool Reachable,
            string InstanceId,
            string DeckId,
            double ElevationM
        )
        {
            this.Id = Id;
            this.DefinitionId = DefinitionId;
            this.LocalX = LocalX;
            this.LocalY = LocalY;
            this.Reachable = Reachable;
            this.InstanceId = InstanceId;
            this.DeckId = DeckId;
            this.ElevationM = ElevationM;
        }

        public VisibleGroundItem()
        {
            this.Id = "";
            this.DefinitionId = "";
            this.InstanceId = "";
            this.DeckId = "";
        }
    }
}
