// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VisibleInteraction
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "placement_id")]
        public string PlacementId;
        [DataMember(Name = "asset_id")]
        public string AssetId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "local_x")]
        public double LocalX;
        [DataMember(Name = "local_y")]
        public double LocalY;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "enabled")]
        public bool Enabled;
        [DataMember(Name = "occupied")]
        public bool Occupied;
        [DataMember(Name = "seated_by_you")]
        public bool SeatedByYou;
        [DataMember(Name = "reachable")]
        public bool Reachable;

        public VisibleInteraction(
            string Id,
            string PlacementId,
            string AssetId,
            string Name,
            string Kind,
            double LocalX,
            double LocalY,
            ulong Revision,
            bool Enabled,
            bool Occupied,
            bool SeatedByYou,
            bool Reachable
        )
        {
            this.Id = Id;
            this.PlacementId = PlacementId;
            this.AssetId = AssetId;
            this.Name = Name;
            this.Kind = Kind;
            this.LocalX = LocalX;
            this.LocalY = LocalY;
            this.Revision = Revision;
            this.Enabled = Enabled;
            this.Occupied = Occupied;
            this.SeatedByYou = SeatedByYou;
            this.Reachable = Reachable;
        }

        public VisibleInteraction()
        {
            this.Id = "";
            this.PlacementId = "";
            this.AssetId = "";
            this.Name = "";
            this.Kind = "";
        }
    }
}
