// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VisibleItemDefinitionPin
    {
        [DataMember(Name = "item_id")]
        public string ItemId;
        [DataMember(Name = "definition_id")]
        public string DefinitionId;
        [DataMember(Name = "item_revision")]
        public ulong ItemRevision;
        [DataMember(Name = "weapon_revision")]
        public ulong WeaponRevision;

        public VisibleItemDefinitionPin(
            string ItemId,
            string DefinitionId,
            ulong ItemRevision,
            ulong WeaponRevision
        )
        {
            this.ItemId = ItemId;
            this.DefinitionId = DefinitionId;
            this.ItemRevision = ItemRevision;
            this.WeaponRevision = WeaponRevision;
        }

        public VisibleItemDefinitionPin()
        {
            this.ItemId = "";
            this.DefinitionId = "";
        }
    }
}
