// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VisibleComponentCatalogSnapshot
    {
        [DataMember(Name = "pin")]
        public string Pin;
        [DataMember(Name = "base_revision")]
        public uint BaseRevision;
        [DataMember(Name = "snapshot_json")]
        public string SnapshotJson;
        [DataMember(Name = "sha_256")]
        public string Sha256;

        public VisibleComponentCatalogSnapshot(
            string Pin,
            uint BaseRevision,
            string SnapshotJson,
            string Sha256
        )
        {
            this.Pin = Pin;
            this.BaseRevision = BaseRevision;
            this.SnapshotJson = SnapshotJson;
            this.Sha256 = Sha256;
        }

        public VisibleComponentCatalogSnapshot()
        {
            this.Pin = "";
            this.SnapshotJson = "";
            this.Sha256 = "";
        }
    }
}
