// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VisibleInventoryHotbar
    {
        [DataMember(Name = "slot")]
        public byte Slot;
        [DataMember(Name = "item_id")]
        public string ItemId;

        public VisibleInventoryHotbar(
            byte Slot,
            string ItemId
        )
        {
            this.Slot = Slot;
            this.ItemId = ItemId;
        }

        public VisibleInventoryHotbar()
        {
            this.ItemId = "";
        }
    }
}
