// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WayfarerRefitReceipt
    {
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "operation_id")]
        public string OperationId;
        [DataMember(Name = "request")]
        public string Request;
        [DataMember(Name = "deck_id")]
        public string DeckId;
        [DataMember(Name = "template_sha_256")]
        public string TemplateSha256;
        [DataMember(Name = "completed_micros")]
        public ulong CompletedMicros;

        public WayfarerRefitReceipt(
            string ShipId,
            SpacetimeDB.Identity Owner,
            string CharacterId,
            string OperationId,
            string Request,
            string DeckId,
            string TemplateSha256,
            ulong CompletedMicros
        )
        {
            this.ShipId = ShipId;
            this.Owner = Owner;
            this.CharacterId = CharacterId;
            this.OperationId = OperationId;
            this.Request = Request;
            this.DeckId = DeckId;
            this.TemplateSha256 = TemplateSha256;
            this.CompletedMicros = CompletedMicros;
        }

        public WayfarerRefitReceipt()
        {
            this.ShipId = "";
            this.CharacterId = "";
            this.OperationId = "";
            this.Request = "";
            this.DeckId = "";
            this.TemplateSha256 = "";
        }
    }
}
