// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WeaponEnergy
    {
        [DataMember(Name = "item_id")]
        public string ItemId;
        [DataMember(Name = "energy")]
        public double Energy;
        [DataMember(Name = "checkpoint_micros")]
        public ulong CheckpointMicros;
        [DataMember(Name = "last_shot_micros")]
        public ulong LastShotMicros;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "shot_sequence")]
        public ulong ShotSequence;
        [DataMember(Name = "last_shot_angle")]
        public double LastShotAngle;

        public WeaponEnergy(
            string ItemId,
            double Energy,
            ulong CheckpointMicros,
            ulong LastShotMicros,
            ulong Revision,
            ulong ShotSequence,
            double LastShotAngle
        )
        {
            this.ItemId = ItemId;
            this.Energy = Energy;
            this.CheckpointMicros = CheckpointMicros;
            this.LastShotMicros = LastShotMicros;
            this.Revision = Revision;
            this.ShotSequence = ShotSequence;
            this.LastShotAngle = LastShotAngle;
        }

        public WeaponEnergy()
        {
            this.ItemId = "";
        }
    }
}
