// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldJoinReceipt
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "character_id")]
        public string CharacterId;
        [DataMember(Name = "ship_id")]
        public string ShipId;
        [DataMember(Name = "system_id")]
        public string SystemId;
        [DataMember(Name = "request_json")]
        public string RequestJson;
        [DataMember(Name = "revision")]
        public ulong Revision;
        [DataMember(Name = "old_motion_json")]
        public string OldMotionJson;
        [DataMember(Name = "new_motion_json")]
        public string NewMotionJson;
        [DataMember(Name = "created_micros")]
        public ulong CreatedMicros;

        public WorldJoinReceipt(
            string Id,
            SpacetimeDB.Identity Owner,
            string CharacterId,
            string ShipId,
            string SystemId,
            string RequestJson,
            ulong Revision,
            string OldMotionJson,
            string NewMotionJson,
            ulong CreatedMicros
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.CharacterId = CharacterId;
            this.ShipId = ShipId;
            this.SystemId = SystemId;
            this.RequestJson = RequestJson;
            this.Revision = Revision;
            this.OldMotionJson = OldMotionJson;
            this.NewMotionJson = NewMotionJson;
            this.CreatedMicros = CreatedMicros;
        }

        public WorldJoinReceipt()
        {
            this.Id = "";
            this.CharacterId = "";
            this.ShipId = "";
            this.SystemId = "";
            this.RequestJson = "";
            this.OldMotionJson = "";
            this.NewMotionJson = "";
        }
    }
}
