// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldSystem
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "seed_revision")]
        public ulong SeedRevision;
        [DataMember(Name = "seed_sha_256")]
        public string SeedSha256;
        [DataMember(Name = "migration_revision")]
        public ulong MigrationRevision;
        [DataMember(Name = "last_simulation_tick")]
        public ulong LastSimulationTick;

        public WorldSystem(
            string Id,
            ulong SeedRevision,
            string SeedSha256,
            ulong MigrationRevision,
            ulong LastSimulationTick
        )
        {
            this.Id = Id;
            this.SeedRevision = SeedRevision;
            this.SeedSha256 = SeedSha256;
            this.MigrationRevision = MigrationRevision;
            this.LastSimulationTick = LastSimulationTick;
        }

        public WorldSystem()
        {
            this.Id = "";
            this.SeedSha256 = "";
        }
    }
}
