// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class AdminContentDefinitionHeadsHandle : RemoteTableHandle<EventContext, ContentDefinitionHead>
        {
            public override string RemoteTableName => "admin_content_definition_heads";

            public sealed class DefinitionKeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ContentDefinitionHead row) => row.DefinitionKey;

                public DefinitionKeyUniqueIndex(AdminContentDefinitionHeadsHandle table) : base(table) { }
            }

            public readonly DefinitionKeyUniqueIndex DefinitionKey;

            internal AdminContentDefinitionHeadsHandle(DbConnection conn) : base(conn)
            {
                DefinitionKey = new(this);
            }

            protected override object GetPrimaryKey(ContentDefinitionHead row) => row.DefinitionKey;
        }

        public readonly AdminContentDefinitionHeadsHandle AdminContentDefinitionHeads;
    }

    public sealed class AdminContentDefinitionHeadsCols
    {
        public global::SpacetimeDB.Col<ContentDefinitionHead, string> DefinitionKey { get; }
        public global::SpacetimeDB.Col<ContentDefinitionHead, string> Kind { get; }
        public global::SpacetimeDB.Col<ContentDefinitionHead, string> DefinitionId { get; }
        public global::SpacetimeDB.Col<ContentDefinitionHead, ulong> Revision { get; }
        public global::SpacetimeDB.Col<ContentDefinitionHead, string> DraftJson { get; }
        public global::SpacetimeDB.Col<ContentDefinitionHead, string> DraftSha256 { get; }
        public global::SpacetimeDB.Col<ContentDefinitionHead, ulong> DraftBaseRevision { get; }
        public global::SpacetimeDB.Col<ContentDefinitionHead, ulong> LatestRevision { get; }
        public global::SpacetimeDB.Col<ContentDefinitionHead, ulong> CurrentRevision { get; }
        public global::SpacetimeDB.Col<ContentDefinitionHead, SpacetimeDB.Identity> UpdatedBy { get; }
        public global::SpacetimeDB.Col<ContentDefinitionHead, ulong> UpdatedMicros { get; }

        public AdminContentDefinitionHeadsCols(string tableName)
        {
            DefinitionKey = new global::SpacetimeDB.Col<ContentDefinitionHead, string>(tableName, "definition_key");
            Kind = new global::SpacetimeDB.Col<ContentDefinitionHead, string>(tableName, "kind");
            DefinitionId = new global::SpacetimeDB.Col<ContentDefinitionHead, string>(tableName, "definition_id");
            Revision = new global::SpacetimeDB.Col<ContentDefinitionHead, ulong>(tableName, "revision");
            DraftJson = new global::SpacetimeDB.Col<ContentDefinitionHead, string>(tableName, "draft_json");
            DraftSha256 = new global::SpacetimeDB.Col<ContentDefinitionHead, string>(tableName, "draft_sha_256");
            DraftBaseRevision = new global::SpacetimeDB.Col<ContentDefinitionHead, ulong>(tableName, "draft_base_revision");
            LatestRevision = new global::SpacetimeDB.Col<ContentDefinitionHead, ulong>(tableName, "latest_revision");
            CurrentRevision = new global::SpacetimeDB.Col<ContentDefinitionHead, ulong>(tableName, "current_revision");
            UpdatedBy = new global::SpacetimeDB.Col<ContentDefinitionHead, SpacetimeDB.Identity>(tableName, "updated_by");
            UpdatedMicros = new global::SpacetimeDB.Col<ContentDefinitionHead, ulong>(tableName, "updated_micros");
        }
    }

    public sealed class AdminContentDefinitionHeadsIxCols
    {
        public global::SpacetimeDB.IxCol<ContentDefinitionHead, string> DefinitionKey { get; }

        public AdminContentDefinitionHeadsIxCols(string tableName)
        {
            DefinitionKey = new global::SpacetimeDB.IxCol<ContentDefinitionHead, string>(tableName, "definition_key");
        }
    }
}
