// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class ComponentCatalogSnapshotsHandle : RemoteTableHandle<EventContext, VisibleComponentCatalogSnapshot>
        {
            public override string RemoteTableName => "component_catalog_snapshots";

            public sealed class PinUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(VisibleComponentCatalogSnapshot row) => row.Pin;

                public PinUniqueIndex(ComponentCatalogSnapshotsHandle table) : base(table) { }
            }

            public readonly PinUniqueIndex Pin;

            internal ComponentCatalogSnapshotsHandle(DbConnection conn) : base(conn)
            {
                Pin = new(this);
            }

            protected override object GetPrimaryKey(VisibleComponentCatalogSnapshot row) => row.Pin;
        }

        public readonly ComponentCatalogSnapshotsHandle ComponentCatalogSnapshots;
    }

    public sealed class ComponentCatalogSnapshotsCols
    {
        public global::SpacetimeDB.Col<VisibleComponentCatalogSnapshot, string> Pin { get; }
        public global::SpacetimeDB.Col<VisibleComponentCatalogSnapshot, uint> BaseRevision { get; }
        public global::SpacetimeDB.Col<VisibleComponentCatalogSnapshot, string> SnapshotJson { get; }
        public global::SpacetimeDB.Col<VisibleComponentCatalogSnapshot, string> Sha256 { get; }

        public ComponentCatalogSnapshotsCols(string tableName)
        {
            Pin = new global::SpacetimeDB.Col<VisibleComponentCatalogSnapshot, string>(tableName, "pin");
            BaseRevision = new global::SpacetimeDB.Col<VisibleComponentCatalogSnapshot, uint>(tableName, "base_revision");
            SnapshotJson = new global::SpacetimeDB.Col<VisibleComponentCatalogSnapshot, string>(tableName, "snapshot_json");
            Sha256 = new global::SpacetimeDB.Col<VisibleComponentCatalogSnapshot, string>(tableName, "sha_256");
        }
    }

    public sealed class ComponentCatalogSnapshotsIxCols
    {
        public global::SpacetimeDB.IxCol<VisibleComponentCatalogSnapshot, string> Pin { get; }

        public ComponentCatalogSnapshotsIxCols(string tableName)
        {
            Pin = new global::SpacetimeDB.IxCol<VisibleComponentCatalogSnapshot, string>(tableName, "pin");
        }
    }
}
