// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class CurrentInteriorCrewHandle : RemoteTableHandle<EventContext, InteriorCrew>
        {
            public override string RemoteTableName => "current_interior_crew";

            public sealed class CharacterIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(InteriorCrew row) => row.CharacterId;

                public CharacterIdUniqueIndex(CurrentInteriorCrewHandle table) : base(table) { }
            }

            public readonly CharacterIdUniqueIndex CharacterId;

            internal CurrentInteriorCrewHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
            }

            protected override object GetPrimaryKey(InteriorCrew row) => row.CharacterId;
        }

        public readonly CurrentInteriorCrewHandle CurrentInteriorCrew;
    }

    public sealed class CurrentInteriorCrewCols
    {
        public global::SpacetimeDB.Col<InteriorCrew, string> CharacterId { get; }
        public global::SpacetimeDB.Col<InteriorCrew, string> Name { get; }
        public global::SpacetimeDB.Col<InteriorCrew, string> ShipId { get; }
        public global::SpacetimeDB.Col<InteriorCrew, string> DeckId { get; }
        public global::SpacetimeDB.Col<InteriorCrew, double> LocalX { get; }
        public global::SpacetimeDB.Col<InteriorCrew, double> LocalY { get; }
        public global::SpacetimeDB.Col<InteriorCrew, double> StandingElevationM { get; }
        public global::SpacetimeDB.Col<InteriorCrew, bool> Connected { get; }
        public global::SpacetimeDB.Col<InteriorCrew, bool> Sprinting { get; }

        public CurrentInteriorCrewCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.Col<InteriorCrew, string>(tableName, "character_id");
            Name = new global::SpacetimeDB.Col<InteriorCrew, string>(tableName, "name");
            ShipId = new global::SpacetimeDB.Col<InteriorCrew, string>(tableName, "ship_id");
            DeckId = new global::SpacetimeDB.Col<InteriorCrew, string>(tableName, "deck_id");
            LocalX = new global::SpacetimeDB.Col<InteriorCrew, double>(tableName, "local_x");
            LocalY = new global::SpacetimeDB.Col<InteriorCrew, double>(tableName, "local_y");
            StandingElevationM = new global::SpacetimeDB.Col<InteriorCrew, double>(tableName, "standing_elevation_m");
            Connected = new global::SpacetimeDB.Col<InteriorCrew, bool>(tableName, "connected");
            Sprinting = new global::SpacetimeDB.Col<InteriorCrew, bool>(tableName, "sprinting");
        }
    }

    public sealed class CurrentInteriorCrewIxCols
    {
        public global::SpacetimeDB.IxCol<InteriorCrew, string> CharacterId { get; }

        public CurrentInteriorCrewIxCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.IxCol<InteriorCrew, string>(tableName, "character_id");
        }
    }
}
