// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnAuthoredFlightFittingsHandle : RemoteTableHandle<EventContext, AuthoredFlightFitting>
        {
            public override string RemoteTableName => "own_authored_flight_fittings";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(AuthoredFlightFitting row) => row.Id;

                public IdUniqueIndex(OwnAuthoredFlightFittingsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OwnAuthoredFlightFittingsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(AuthoredFlightFitting row) => row.Id;
        }

        public readonly OwnAuthoredFlightFittingsHandle OwnAuthoredFlightFittings;
    }

    public sealed class OwnAuthoredFlightFittingsCols
    {
        public global::SpacetimeDB.Col<AuthoredFlightFitting, string> Id { get; }
        public global::SpacetimeDB.Col<AuthoredFlightFitting, string> ShipId { get; }
        public global::SpacetimeDB.Col<AuthoredFlightFitting, string> PlacedObjectId { get; }
        public global::SpacetimeDB.Col<AuthoredFlightFitting, string> SourceDeviceId { get; }
        public global::SpacetimeDB.Col<AuthoredFlightFitting, string> Kind { get; }

        public OwnAuthoredFlightFittingsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<AuthoredFlightFitting, string>(tableName, "id");
            ShipId = new global::SpacetimeDB.Col<AuthoredFlightFitting, string>(tableName, "ship_id");
            PlacedObjectId = new global::SpacetimeDB.Col<AuthoredFlightFitting, string>(tableName, "placed_object_id");
            SourceDeviceId = new global::SpacetimeDB.Col<AuthoredFlightFitting, string>(tableName, "source_device_id");
            Kind = new global::SpacetimeDB.Col<AuthoredFlightFitting, string>(tableName, "kind");
        }
    }

    public sealed class OwnAuthoredFlightFittingsIxCols
    {
        public global::SpacetimeDB.IxCol<AuthoredFlightFitting, string> Id { get; }

        public OwnAuthoredFlightFittingsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<AuthoredFlightFitting, string>(tableName, "id");
        }
    }
}
