// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnAuthoredFlightActuatorsHandle : RemoteTableHandle<EventContext, AuthoredFlightActuator>
        {
            public override string RemoteTableName => "own_authored_flight_actuators";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(AuthoredFlightActuator row) => row.Id;

                public IdUniqueIndex(OwnAuthoredFlightActuatorsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OwnAuthoredFlightActuatorsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(AuthoredFlightActuator row) => row.Id;
        }

        public readonly OwnAuthoredFlightActuatorsHandle OwnAuthoredFlightActuators;
    }

    public sealed class OwnAuthoredFlightActuatorsCols
    {
        public global::SpacetimeDB.Col<AuthoredFlightActuator, string> Id { get; }
        public global::SpacetimeDB.Col<AuthoredFlightActuator, string> ShipId { get; }
        public global::SpacetimeDB.Col<AuthoredFlightActuator, string> PlacedObjectId { get; }
        public global::SpacetimeDB.Col<AuthoredFlightActuator, double> X { get; }
        public global::SpacetimeDB.Col<AuthoredFlightActuator, double> Y { get; }
        public global::SpacetimeDB.Col<AuthoredFlightActuator, double> NozzleX { get; }
        public global::SpacetimeDB.Col<AuthoredFlightActuator, double> NozzleY { get; }
        public global::SpacetimeDB.Col<AuthoredFlightActuator, double> Height { get; }
        public global::SpacetimeDB.Col<AuthoredFlightActuator, double> ExhaustX { get; }
        public global::SpacetimeDB.Col<AuthoredFlightActuator, double> ExhaustY { get; }
        public global::SpacetimeDB.Col<AuthoredFlightActuator, double> Throttle { get; }

        public OwnAuthoredFlightActuatorsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<AuthoredFlightActuator, string>(tableName, "id");
            ShipId = new global::SpacetimeDB.Col<AuthoredFlightActuator, string>(tableName, "ship_id");
            PlacedObjectId = new global::SpacetimeDB.Col<AuthoredFlightActuator, string>(tableName, "placed_object_id");
            X = new global::SpacetimeDB.Col<AuthoredFlightActuator, double>(tableName, "x");
            Y = new global::SpacetimeDB.Col<AuthoredFlightActuator, double>(tableName, "y");
            NozzleX = new global::SpacetimeDB.Col<AuthoredFlightActuator, double>(tableName, "nozzle_x");
            NozzleY = new global::SpacetimeDB.Col<AuthoredFlightActuator, double>(tableName, "nozzle_y");
            Height = new global::SpacetimeDB.Col<AuthoredFlightActuator, double>(tableName, "height");
            ExhaustX = new global::SpacetimeDB.Col<AuthoredFlightActuator, double>(tableName, "exhaust_x");
            ExhaustY = new global::SpacetimeDB.Col<AuthoredFlightActuator, double>(tableName, "exhaust_y");
            Throttle = new global::SpacetimeDB.Col<AuthoredFlightActuator, double>(tableName, "throttle");
        }
    }

    public sealed class OwnAuthoredFlightActuatorsIxCols
    {
        public global::SpacetimeDB.IxCol<AuthoredFlightActuator, string> Id { get; }

        public OwnAuthoredFlightActuatorsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<AuthoredFlightActuator, string>(tableName, "id");
        }
    }
}
