// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnAuthoredFlightPhysicsHandle : RemoteTableHandle<EventContext, AuthoredFlightPhysics>
        {
            public override string RemoteTableName => "own_authored_flight_physics";

            public sealed class ShipIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(AuthoredFlightPhysics row) => row.ShipId;

                public ShipIdUniqueIndex(OwnAuthoredFlightPhysicsHandle table) : base(table) { }
            }

            public readonly ShipIdUniqueIndex ShipId;

            internal OwnAuthoredFlightPhysicsHandle(DbConnection conn) : base(conn)
            {
                ShipId = new(this);
            }

            protected override object GetPrimaryKey(AuthoredFlightPhysics row) => row.ShipId;
        }

        public readonly OwnAuthoredFlightPhysicsHandle OwnAuthoredFlightPhysics;
    }

    public sealed class OwnAuthoredFlightPhysicsCols
    {
        public global::SpacetimeDB.Col<AuthoredFlightPhysics, string> ShipId { get; }
        public global::SpacetimeDB.Col<AuthoredFlightPhysics, ulong> Revision { get; }
        public global::SpacetimeDB.Col<AuthoredFlightPhysics, string> Status { get; }
        public global::SpacetimeDB.Col<AuthoredFlightPhysics, string> Reason { get; }
        public global::SpacetimeDB.Col<AuthoredFlightPhysics, double> MassKg { get; }
        public global::SpacetimeDB.Col<AuthoredFlightPhysics, double> CenterX { get; }
        public global::SpacetimeDB.Col<AuthoredFlightPhysics, double> CenterY { get; }
        public global::SpacetimeDB.Col<AuthoredFlightPhysics, double> InertiaKgM2 { get; }
        public global::SpacetimeDB.Col<AuthoredFlightPhysics, string> EnvelopeJson { get; }
        public global::SpacetimeDB.Col<AuthoredFlightPhysics, string> DefinitionHash { get; }

        public OwnAuthoredFlightPhysicsCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.Col<AuthoredFlightPhysics, string>(tableName, "ship_id");
            Revision = new global::SpacetimeDB.Col<AuthoredFlightPhysics, ulong>(tableName, "revision");
            Status = new global::SpacetimeDB.Col<AuthoredFlightPhysics, string>(tableName, "status");
            Reason = new global::SpacetimeDB.Col<AuthoredFlightPhysics, string>(tableName, "reason");
            MassKg = new global::SpacetimeDB.Col<AuthoredFlightPhysics, double>(tableName, "mass_kg");
            CenterX = new global::SpacetimeDB.Col<AuthoredFlightPhysics, double>(tableName, "center_x");
            CenterY = new global::SpacetimeDB.Col<AuthoredFlightPhysics, double>(tableName, "center_y");
            InertiaKgM2 = new global::SpacetimeDB.Col<AuthoredFlightPhysics, double>(tableName, "inertia_kg_m_2");
            EnvelopeJson = new global::SpacetimeDB.Col<AuthoredFlightPhysics, string>(tableName, "envelope_json");
            DefinitionHash = new global::SpacetimeDB.Col<AuthoredFlightPhysics, string>(tableName, "definition_hash");
        }
    }

    public sealed class OwnAuthoredFlightPhysicsIxCols
    {
        public global::SpacetimeDB.IxCol<AuthoredFlightPhysics, string> ShipId { get; }

        public OwnAuthoredFlightPhysicsIxCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.IxCol<AuthoredFlightPhysics, string>(tableName, "ship_id");
        }
    }
}
