// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnAuthoredFlightsHandle : RemoteTableHandle<EventContext, AuthoredFlightStatus>
        {
            public override string RemoteTableName => "own_authored_flights";

            public sealed class ShipIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(AuthoredFlightStatus row) => row.ShipId;

                public ShipIdUniqueIndex(OwnAuthoredFlightsHandle table) : base(table) { }
            }

            public readonly ShipIdUniqueIndex ShipId;

            internal OwnAuthoredFlightsHandle(DbConnection conn) : base(conn)
            {
                ShipId = new(this);
            }

            protected override object GetPrimaryKey(AuthoredFlightStatus row) => row.ShipId;
        }

        public readonly OwnAuthoredFlightsHandle OwnAuthoredFlights;
    }

    public sealed class OwnAuthoredFlightsCols
    {
        public global::SpacetimeDB.Col<AuthoredFlightStatus, string> ShipId { get; }
        public global::SpacetimeDB.Col<AuthoredFlightStatus, string> StationId { get; }
        public global::SpacetimeDB.Col<AuthoredFlightStatus, ulong> StationRevision { get; }
        public global::SpacetimeDB.Col<AuthoredFlightStatus, string> DeckId { get; }
        public global::SpacetimeDB.Col<AuthoredFlightStatus, string> Lifecycle { get; }
        public global::SpacetimeDB.Col<AuthoredFlightStatus, ulong> Revision { get; }
        public global::SpacetimeDB.Col<AuthoredFlightStatus, bool> Active { get; }
        public global::SpacetimeDB.Col<AuthoredFlightStatus, bool> FlightAdmitted { get; }
        public global::SpacetimeDB.Col<AuthoredFlightStatus, string> VisitId { get; }
        public global::SpacetimeDB.Col<AuthoredFlightStatus, ulong> VisitRevision { get; }
        public global::SpacetimeDB.Col<AuthoredFlightStatus, ulong> AdmissionRevision { get; }
        public global::SpacetimeDB.Col<AuthoredFlightStatus, string> SeatState { get; }
        public global::SpacetimeDB.Col<AuthoredFlightStatus, ulong> SeatRevision { get; }

        public OwnAuthoredFlightsCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.Col<AuthoredFlightStatus, string>(tableName, "ship_id");
            StationId = new global::SpacetimeDB.Col<AuthoredFlightStatus, string>(tableName, "station_id");
            StationRevision = new global::SpacetimeDB.Col<AuthoredFlightStatus, ulong>(tableName, "station_revision");
            DeckId = new global::SpacetimeDB.Col<AuthoredFlightStatus, string>(tableName, "deck_id");
            Lifecycle = new global::SpacetimeDB.Col<AuthoredFlightStatus, string>(tableName, "lifecycle");
            Revision = new global::SpacetimeDB.Col<AuthoredFlightStatus, ulong>(tableName, "revision");
            Active = new global::SpacetimeDB.Col<AuthoredFlightStatus, bool>(tableName, "active");
            FlightAdmitted = new global::SpacetimeDB.Col<AuthoredFlightStatus, bool>(tableName, "flight_admitted");
            VisitId = new global::SpacetimeDB.Col<AuthoredFlightStatus, string>(tableName, "visit_id");
            VisitRevision = new global::SpacetimeDB.Col<AuthoredFlightStatus, ulong>(tableName, "visit_revision");
            AdmissionRevision = new global::SpacetimeDB.Col<AuthoredFlightStatus, ulong>(tableName, "admission_revision");
            SeatState = new global::SpacetimeDB.Col<AuthoredFlightStatus, string>(tableName, "seat_state");
            SeatRevision = new global::SpacetimeDB.Col<AuthoredFlightStatus, ulong>(tableName, "seat_revision");
        }
    }

    public sealed class OwnAuthoredFlightsIxCols
    {
        public global::SpacetimeDB.IxCol<AuthoredFlightStatus, string> ShipId { get; }

        public OwnAuthoredFlightsIxCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.IxCol<AuthoredFlightStatus, string>(tableName, "ship_id");
        }
    }
}
