// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnConstructionDoorsHandle : RemoteTableHandle<EventContext, ConstructionDoorStatus>
        {
            public override string RemoteTableName => "own_construction_doors";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ConstructionDoorStatus row) => row.Id;

                public IdUniqueIndex(OwnConstructionDoorsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OwnConstructionDoorsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ConstructionDoorStatus row) => row.Id;
        }

        public readonly OwnConstructionDoorsHandle OwnConstructionDoors;
    }

    public sealed class OwnConstructionDoorsCols
    {
        public global::SpacetimeDB.Col<ConstructionDoorStatus, string> Id { get; }
        public global::SpacetimeDB.Col<ConstructionDoorStatus, string> InstanceId { get; }
        public global::SpacetimeDB.Col<ConstructionDoorStatus, string> DeckId { get; }
        public global::SpacetimeDB.Col<ConstructionDoorStatus, double> Fraction { get; }
        public global::SpacetimeDB.Col<ConstructionDoorStatus, bool> TargetOpen { get; }
        public global::SpacetimeDB.Col<ConstructionDoorStatus, bool> Blocked { get; }
        public global::SpacetimeDB.Col<ConstructionDoorStatus, bool> Moving { get; }
        public global::SpacetimeDB.Col<ConstructionDoorStatus, ulong> Revision { get; }

        public OwnConstructionDoorsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ConstructionDoorStatus, string>(tableName, "id");
            InstanceId = new global::SpacetimeDB.Col<ConstructionDoorStatus, string>(tableName, "instance_id");
            DeckId = new global::SpacetimeDB.Col<ConstructionDoorStatus, string>(tableName, "deck_id");
            Fraction = new global::SpacetimeDB.Col<ConstructionDoorStatus, double>(tableName, "fraction");
            TargetOpen = new global::SpacetimeDB.Col<ConstructionDoorStatus, bool>(tableName, "target_open");
            Blocked = new global::SpacetimeDB.Col<ConstructionDoorStatus, bool>(tableName, "blocked");
            Moving = new global::SpacetimeDB.Col<ConstructionDoorStatus, bool>(tableName, "moving");
            Revision = new global::SpacetimeDB.Col<ConstructionDoorStatus, ulong>(tableName, "revision");
        }
    }

    public sealed class OwnConstructionDoorsIxCols
    {
        public global::SpacetimeDB.IxCol<ConstructionDoorStatus, string> Id { get; }

        public OwnConstructionDoorsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ConstructionDoorStatus, string>(tableName, "id");
        }
    }
}
