// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnConstructionDecksHandle : RemoteTableHandle<EventContext, ConstructionDeckStatus>
        {
            public override string RemoteTableName => "own_construction_decks";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ConstructionDeckStatus row) => row.Id;

                public IdUniqueIndex(OwnConstructionDecksHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OwnConstructionDecksHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ConstructionDeckStatus row) => row.Id;
        }

        public readonly OwnConstructionDecksHandle OwnConstructionDecks;
    }

    public sealed class OwnConstructionDecksCols
    {
        public global::SpacetimeDB.Col<ConstructionDeckStatus, string> Id { get; }
        public global::SpacetimeDB.Col<ConstructionDeckStatus, string> InstanceId { get; }
        public global::SpacetimeDB.Col<ConstructionDeckStatus, string> SourceDeckId { get; }
        public global::SpacetimeDB.Col<ConstructionDeckStatus, string> Name { get; }
        public global::SpacetimeDB.Col<ConstructionDeckStatus, double> Elevation { get; }
        public global::SpacetimeDB.Col<ConstructionDeckStatus, double> Ceiling { get; }

        public OwnConstructionDecksCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ConstructionDeckStatus, string>(tableName, "id");
            InstanceId = new global::SpacetimeDB.Col<ConstructionDeckStatus, string>(tableName, "instance_id");
            SourceDeckId = new global::SpacetimeDB.Col<ConstructionDeckStatus, string>(tableName, "source_deck_id");
            Name = new global::SpacetimeDB.Col<ConstructionDeckStatus, string>(tableName, "name");
            Elevation = new global::SpacetimeDB.Col<ConstructionDeckStatus, double>(tableName, "elevation");
            Ceiling = new global::SpacetimeDB.Col<ConstructionDeckStatus, double>(tableName, "ceiling");
        }
    }

    public sealed class OwnConstructionDecksIxCols
    {
        public global::SpacetimeDB.IxCol<ConstructionDeckStatus, string> Id { get; }

        public OwnConstructionDecksIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ConstructionDeckStatus, string>(tableName, "id");
        }
    }
}
