// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnCharacterVitalsHandle : RemoteTableHandle<EventContext, CharacterVitalsStatus>
        {
            public override string RemoteTableName => "own_character_vitals";

            public sealed class CharacterIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(CharacterVitalsStatus row) => row.CharacterId;

                public CharacterIdUniqueIndex(OwnCharacterVitalsHandle table) : base(table) { }
            }

            public readonly CharacterIdUniqueIndex CharacterId;

            internal OwnCharacterVitalsHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
            }

            protected override object GetPrimaryKey(CharacterVitalsStatus row) => row.CharacterId;
        }

        public readonly OwnCharacterVitalsHandle OwnCharacterVitals;
    }

    public sealed class OwnCharacterVitalsCols
    {
        public global::SpacetimeDB.Col<CharacterVitalsStatus, string> CharacterId { get; }
        public global::SpacetimeDB.Col<CharacterVitalsStatus, double> Health { get; }
        public global::SpacetimeDB.Col<CharacterVitalsStatus, double> MaxHealth { get; }
        public global::SpacetimeDB.Col<CharacterVitalsStatus, string> State { get; }
        public global::SpacetimeDB.Col<CharacterVitalsStatus, ulong> DownedUntilMicros { get; }
        public global::SpacetimeDB.Col<CharacterVitalsStatus, ulong> HitSequence { get; }
        public global::SpacetimeDB.Col<CharacterVitalsStatus, double> LastHitDamage { get; }

        public OwnCharacterVitalsCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.Col<CharacterVitalsStatus, string>(tableName, "character_id");
            Health = new global::SpacetimeDB.Col<CharacterVitalsStatus, double>(tableName, "health");
            MaxHealth = new global::SpacetimeDB.Col<CharacterVitalsStatus, double>(tableName, "max_health");
            State = new global::SpacetimeDB.Col<CharacterVitalsStatus, string>(tableName, "state");
            DownedUntilMicros = new global::SpacetimeDB.Col<CharacterVitalsStatus, ulong>(tableName, "downed_until_micros");
            HitSequence = new global::SpacetimeDB.Col<CharacterVitalsStatus, ulong>(tableName, "hit_sequence");
            LastHitDamage = new global::SpacetimeDB.Col<CharacterVitalsStatus, double>(tableName, "last_hit_damage");
        }
    }

    public sealed class OwnCharacterVitalsIxCols
    {
        public global::SpacetimeDB.IxCol<CharacterVitalsStatus, string> CharacterId { get; }

        public OwnCharacterVitalsIxCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.IxCol<CharacterVitalsStatus, string>(tableName, "character_id");
        }
    }
}
