// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnConstructionBlueprintsHandle : RemoteTableHandle<EventContext, ConstructionBlueprintStatus>
        {
            public override string RemoteTableName => "own_construction_blueprints";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ConstructionBlueprintStatus row) => row.Id;

                public IdUniqueIndex(OwnConstructionBlueprintsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OwnConstructionBlueprintsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ConstructionBlueprintStatus row) => row.Id;
        }

        public readonly OwnConstructionBlueprintsHandle OwnConstructionBlueprints;
    }

    public sealed class OwnConstructionBlueprintsCols
    {
        public global::SpacetimeDB.Col<ConstructionBlueprintStatus, string> Id { get; }
        public global::SpacetimeDB.Col<ConstructionBlueprintStatus, string> WorkspaceId { get; }
        public global::SpacetimeDB.Col<ConstructionBlueprintStatus, string> DraftId { get; }
        public global::SpacetimeDB.Col<ConstructionBlueprintStatus, ulong> SourceRevision { get; }
        public global::SpacetimeDB.Col<ConstructionBlueprintStatus, string> Canonical { get; }
        public global::SpacetimeDB.Col<ConstructionBlueprintStatus, string> Sha256 { get; }
        public global::SpacetimeDB.Col<ConstructionBlueprintStatus, string> ReadinessJson { get; }

        public OwnConstructionBlueprintsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ConstructionBlueprintStatus, string>(tableName, "id");
            WorkspaceId = new global::SpacetimeDB.Col<ConstructionBlueprintStatus, string>(tableName, "workspace_id");
            DraftId = new global::SpacetimeDB.Col<ConstructionBlueprintStatus, string>(tableName, "draft_id");
            SourceRevision = new global::SpacetimeDB.Col<ConstructionBlueprintStatus, ulong>(tableName, "source_revision");
            Canonical = new global::SpacetimeDB.Col<ConstructionBlueprintStatus, string>(tableName, "canonical");
            Sha256 = new global::SpacetimeDB.Col<ConstructionBlueprintStatus, string>(tableName, "sha_256");
            ReadinessJson = new global::SpacetimeDB.Col<ConstructionBlueprintStatus, string>(tableName, "readiness_json");
        }
    }

    public sealed class OwnConstructionBlueprintsIxCols
    {
        public global::SpacetimeDB.IxCol<ConstructionBlueprintStatus, string> Id { get; }

        public OwnConstructionBlueprintsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ConstructionBlueprintStatus, string>(tableName, "id");
        }
    }
}
