// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnCarriedInventoryRevisionsHandle : RemoteTableHandle<EventContext, ScopedCarriedInventoryRevision>
        {
            public override string RemoteTableName => "own_carried_inventory_revisions";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ScopedCarriedInventoryRevision row) => row.Id;

                public IdUniqueIndex(OwnCarriedInventoryRevisionsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OwnCarriedInventoryRevisionsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ScopedCarriedInventoryRevision row) => row.Id;
        }

        public readonly OwnCarriedInventoryRevisionsHandle OwnCarriedInventoryRevisions;
    }

    public sealed class OwnCarriedInventoryRevisionsCols
    {
        public global::SpacetimeDB.Col<ScopedCarriedInventoryRevision, string> Id { get; }
        public global::SpacetimeDB.Col<ScopedCarriedInventoryRevision, string> Kind { get; }
        public global::SpacetimeDB.Col<ScopedCarriedInventoryRevision, ulong> Revision { get; }

        public OwnCarriedInventoryRevisionsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ScopedCarriedInventoryRevision, string>(tableName, "id");
            Kind = new global::SpacetimeDB.Col<ScopedCarriedInventoryRevision, string>(tableName, "kind");
            Revision = new global::SpacetimeDB.Col<ScopedCarriedInventoryRevision, ulong>(tableName, "revision");
        }
    }

    public sealed class OwnCarriedInventoryRevisionsIxCols
    {
        public global::SpacetimeDB.IxCol<ScopedCarriedInventoryRevision, string> Id { get; }

        public OwnCarriedInventoryRevisionsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ScopedCarriedInventoryRevision, string>(tableName, "id");
        }
    }
}
