// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnConstructionStairWalksHandle : RemoteTableHandle<EventContext, ConstructionStairWalkStatus>
        {
            public override string RemoteTableName => "own_construction_stair_walks";

            public sealed class CharacterIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ConstructionStairWalkStatus row) => row.CharacterId;

                public CharacterIdUniqueIndex(OwnConstructionStairWalksHandle table) : base(table) { }
            }

            public readonly CharacterIdUniqueIndex CharacterId;

            internal OwnConstructionStairWalksHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
            }

            protected override object GetPrimaryKey(ConstructionStairWalkStatus row) => row.CharacterId;
        }

        public readonly OwnConstructionStairWalksHandle OwnConstructionStairWalks;
    }

    public sealed class OwnConstructionStairWalksCols
    {
        public global::SpacetimeDB.Col<ConstructionStairWalkStatus, string> CharacterId { get; }
        public global::SpacetimeDB.Col<ConstructionStairWalkStatus, string> WalkId { get; }
        public global::SpacetimeDB.Col<ConstructionStairWalkStatus, string> InstanceId { get; }
        public global::SpacetimeDB.Col<ConstructionStairWalkStatus, string> StairId { get; }
        public global::SpacetimeDB.Col<ConstructionStairWalkStatus, string> SourceDeckId { get; }
        public global::SpacetimeDB.Col<ConstructionStairWalkStatus, string> VisitId { get; }
        public global::SpacetimeDB.Col<ConstructionStairWalkStatus, string> Phase { get; }
        public global::SpacetimeDB.Col<ConstructionStairWalkStatus, bool> EgressOnly { get; }
        public global::SpacetimeDB.Col<ConstructionStairWalkStatus, string> Interruption { get; }
        public global::SpacetimeDB.Col<ConstructionStairWalkStatus, ulong> Revision { get; }
        public global::SpacetimeDB.Col<ConstructionStairWalkStatus, double> X { get; }
        public global::SpacetimeDB.Col<ConstructionStairWalkStatus, double> Y { get; }
        public global::SpacetimeDB.Col<ConstructionStairWalkStatus, double> Z { get; }

        public OwnConstructionStairWalksCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.Col<ConstructionStairWalkStatus, string>(tableName, "character_id");
            WalkId = new global::SpacetimeDB.Col<ConstructionStairWalkStatus, string>(tableName, "walk_id");
            InstanceId = new global::SpacetimeDB.Col<ConstructionStairWalkStatus, string>(tableName, "instance_id");
            StairId = new global::SpacetimeDB.Col<ConstructionStairWalkStatus, string>(tableName, "stair_id");
            SourceDeckId = new global::SpacetimeDB.Col<ConstructionStairWalkStatus, string>(tableName, "source_deck_id");
            VisitId = new global::SpacetimeDB.Col<ConstructionStairWalkStatus, string>(tableName, "visit_id");
            Phase = new global::SpacetimeDB.Col<ConstructionStairWalkStatus, string>(tableName, "phase");
            EgressOnly = new global::SpacetimeDB.Col<ConstructionStairWalkStatus, bool>(tableName, "egress_only");
            Interruption = new global::SpacetimeDB.Col<ConstructionStairWalkStatus, string>(tableName, "interruption");
            Revision = new global::SpacetimeDB.Col<ConstructionStairWalkStatus, ulong>(tableName, "revision");
            X = new global::SpacetimeDB.Col<ConstructionStairWalkStatus, double>(tableName, "x");
            Y = new global::SpacetimeDB.Col<ConstructionStairWalkStatus, double>(tableName, "y");
            Z = new global::SpacetimeDB.Col<ConstructionStairWalkStatus, double>(tableName, "z");
        }
    }

    public sealed class OwnConstructionStairWalksIxCols
    {
        public global::SpacetimeDB.IxCol<ConstructionStairWalkStatus, string> CharacterId { get; }

        public OwnConstructionStairWalksIxCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.IxCol<ConstructionStairWalkStatus, string>(tableName, "character_id");
        }
    }
}
