// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnConstructionSeatHandle : RemoteTableHandle<EventContext, OwnConstructionSeatStatus>
        {
            public override string RemoteTableName => "own_construction_seat";

            public sealed class CharacterIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(OwnConstructionSeatStatus row) => row.CharacterId;

                public CharacterIdUniqueIndex(OwnConstructionSeatHandle table) : base(table) { }
            }

            public readonly CharacterIdUniqueIndex CharacterId;

            internal OwnConstructionSeatHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
            }

            protected override object GetPrimaryKey(OwnConstructionSeatStatus row) => row.CharacterId;
        }

        public readonly OwnConstructionSeatHandle OwnConstructionSeat;
    }

    public sealed class OwnConstructionSeatCols
    {
        public global::SpacetimeDB.Col<OwnConstructionSeatStatus, string> CharacterId { get; }
        public global::SpacetimeDB.Col<OwnConstructionSeatStatus, string> InstanceId { get; }
        public global::SpacetimeDB.Col<OwnConstructionSeatStatus, string> DeckId { get; }
        public global::SpacetimeDB.Col<OwnConstructionSeatStatus, string> ObjectId { get; }
        public global::SpacetimeDB.Col<OwnConstructionSeatStatus, double> LocalX { get; }
        public global::SpacetimeDB.Col<OwnConstructionSeatStatus, double> LocalY { get; }
        public global::SpacetimeDB.Col<OwnConstructionSeatStatus, double> StandingElevationM { get; }
        public global::SpacetimeDB.Col<OwnConstructionSeatStatus, bool> ReleasePending { get; }

        public OwnConstructionSeatCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.Col<OwnConstructionSeatStatus, string>(tableName, "character_id");
            InstanceId = new global::SpacetimeDB.Col<OwnConstructionSeatStatus, string>(tableName, "instance_id");
            DeckId = new global::SpacetimeDB.Col<OwnConstructionSeatStatus, string>(tableName, "deck_id");
            ObjectId = new global::SpacetimeDB.Col<OwnConstructionSeatStatus, string>(tableName, "object_id");
            LocalX = new global::SpacetimeDB.Col<OwnConstructionSeatStatus, double>(tableName, "local_x");
            LocalY = new global::SpacetimeDB.Col<OwnConstructionSeatStatus, double>(tableName, "local_y");
            StandingElevationM = new global::SpacetimeDB.Col<OwnConstructionSeatStatus, double>(tableName, "standing_elevation_m");
            ReleasePending = new global::SpacetimeDB.Col<OwnConstructionSeatStatus, bool>(tableName, "release_pending");
        }
    }

    public sealed class OwnConstructionSeatIxCols
    {
        public global::SpacetimeDB.IxCol<OwnConstructionSeatStatus, string> CharacterId { get; }

        public OwnConstructionSeatIxCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.IxCol<OwnConstructionSeatStatus, string>(tableName, "character_id");
        }
    }
}
