// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnConstructionTraversalLinksHandle : RemoteTableHandle<EventContext, ConstructionTraversalLinkIntent>
        {
            public override string RemoteTableName => "own_construction_traversal_links";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ConstructionTraversalLinkIntent row) => row.Id;

                public IdUniqueIndex(OwnConstructionTraversalLinksHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OwnConstructionTraversalLinksHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ConstructionTraversalLinkIntent row) => row.Id;
        }

        public readonly OwnConstructionTraversalLinksHandle OwnConstructionTraversalLinks;
    }

    public sealed class OwnConstructionTraversalLinksCols
    {
        public global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, string> Id { get; }
        public global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, string> CharacterId { get; }
        public global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, string> InstanceId { get; }
        public global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, string> LinkId { get; }
        public global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, string> VisitId { get; }
        public global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, string> SourceDeckId { get; }
        public global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, string> DestinationDeckId { get; }
        public global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, ulong> LocationRevision { get; }
        public global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, ulong> InstanceRevision { get; }
        public global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, ulong> LinkRevision { get; }
        public global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, bool> AtLanding { get; }
        public global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, double> X { get; }
        public global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, double> Y { get; }
        public global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, double> Z { get; }

        public OwnConstructionTraversalLinksCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, string>(tableName, "id");
            CharacterId = new global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, string>(tableName, "character_id");
            InstanceId = new global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, string>(tableName, "instance_id");
            LinkId = new global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, string>(tableName, "link_id");
            VisitId = new global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, string>(tableName, "visit_id");
            SourceDeckId = new global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, string>(tableName, "source_deck_id");
            DestinationDeckId = new global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, string>(tableName, "destination_deck_id");
            LocationRevision = new global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, ulong>(tableName, "location_revision");
            InstanceRevision = new global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, ulong>(tableName, "instance_revision");
            LinkRevision = new global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, ulong>(tableName, "link_revision");
            AtLanding = new global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, bool>(tableName, "at_landing");
            X = new global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, double>(tableName, "x");
            Y = new global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, double>(tableName, "y");
            Z = new global::SpacetimeDB.Col<ConstructionTraversalLinkIntent, double>(tableName, "z");
        }
    }

    public sealed class OwnConstructionTraversalLinksIxCols
    {
        public global::SpacetimeDB.IxCol<ConstructionTraversalLinkIntent, string> Id { get; }

        public OwnConstructionTraversalLinksIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ConstructionTraversalLinkIntent, string>(tableName, "id");
        }
    }
}
