// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnEditReceiptsHandle : RemoteTableHandle<EventContext, EditReceipt>
        {
            public override string RemoteTableName => "own_edit_receipts";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(EditReceipt row) => row.Id;

                public IdUniqueIndex(OwnEditReceiptsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OwnEditReceiptsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(EditReceipt row) => row.Id;
        }

        public readonly OwnEditReceiptsHandle OwnEditReceipts;
    }

    public sealed class OwnEditReceiptsCols
    {
        public global::SpacetimeDB.Col<EditReceipt, string> Id { get; }
        public global::SpacetimeDB.Col<EditReceipt, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<EditReceipt, string> ShipId { get; }
        public global::SpacetimeDB.Col<EditReceipt, ulong> Revision { get; }
        public global::SpacetimeDB.Col<EditReceipt, string> Name { get; }
        public global::SpacetimeDB.Col<EditReceipt, ulong> CreatedMicros { get; }

        public OwnEditReceiptsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<EditReceipt, string>(tableName, "id");
            Owner = new global::SpacetimeDB.Col<EditReceipt, SpacetimeDB.Identity>(tableName, "owner");
            ShipId = new global::SpacetimeDB.Col<EditReceipt, string>(tableName, "ship_id");
            Revision = new global::SpacetimeDB.Col<EditReceipt, ulong>(tableName, "revision");
            Name = new global::SpacetimeDB.Col<EditReceipt, string>(tableName, "name");
            CreatedMicros = new global::SpacetimeDB.Col<EditReceipt, ulong>(tableName, "created_micros");
        }
    }

    public sealed class OwnEditReceiptsIxCols
    {
        public global::SpacetimeDB.IxCol<EditReceipt, string> Id { get; }

        public OwnEditReceiptsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<EditReceipt, string>(tableName, "id");
        }
    }
}
