// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnEvaAirlockCycleHandle : RemoteTableHandle<EventContext, EvaAirlockCycleStatus>
        {
            public override string RemoteTableName => "own_eva_airlock_cycle";

            public sealed class CharacterIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(EvaAirlockCycleStatus row) => row.CharacterId;

                public CharacterIdUniqueIndex(OwnEvaAirlockCycleHandle table) : base(table) { }
            }

            public readonly CharacterIdUniqueIndex CharacterId;

            internal OwnEvaAirlockCycleHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
            }

            protected override object GetPrimaryKey(EvaAirlockCycleStatus row) => row.CharacterId;
        }

        public readonly OwnEvaAirlockCycleHandle OwnEvaAirlockCycle;
    }

    public sealed class OwnEvaAirlockCycleCols
    {
        public global::SpacetimeDB.Col<EvaAirlockCycleStatus, string> CharacterId { get; }
        public global::SpacetimeDB.Col<EvaAirlockCycleStatus, string> ShipId { get; }
        public global::SpacetimeDB.Col<EvaAirlockCycleStatus, string> AirlockId { get; }
        public global::SpacetimeDB.Col<EvaAirlockCycleStatus, string> Direction { get; }
        public global::SpacetimeDB.Col<EvaAirlockCycleStatus, ulong> StartedMicros { get; }
        public global::SpacetimeDB.Col<EvaAirlockCycleStatus, ulong> EndsMicros { get; }

        public OwnEvaAirlockCycleCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.Col<EvaAirlockCycleStatus, string>(tableName, "character_id");
            ShipId = new global::SpacetimeDB.Col<EvaAirlockCycleStatus, string>(tableName, "ship_id");
            AirlockId = new global::SpacetimeDB.Col<EvaAirlockCycleStatus, string>(tableName, "airlock_id");
            Direction = new global::SpacetimeDB.Col<EvaAirlockCycleStatus, string>(tableName, "direction");
            StartedMicros = new global::SpacetimeDB.Col<EvaAirlockCycleStatus, ulong>(tableName, "started_micros");
            EndsMicros = new global::SpacetimeDB.Col<EvaAirlockCycleStatus, ulong>(tableName, "ends_micros");
        }
    }

    public sealed class OwnEvaAirlockCycleIxCols
    {
        public global::SpacetimeDB.IxCol<EvaAirlockCycleStatus, string> CharacterId { get; }

        public OwnEvaAirlockCycleIxCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.IxCol<EvaAirlockCycleStatus, string>(tableName, "character_id");
        }
    }
}
