// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnEvaBodyHandle : RemoteTableHandle<EventContext, EvaBodyStatus>
        {
            public override string RemoteTableName => "own_eva_body";

            public sealed class CharacterIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(EvaBodyStatus row) => row.CharacterId;

                public CharacterIdUniqueIndex(OwnEvaBodyHandle table) : base(table) { }
            }

            public readonly CharacterIdUniqueIndex CharacterId;

            internal OwnEvaBodyHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
            }

            protected override object GetPrimaryKey(EvaBodyStatus row) => row.CharacterId;
        }

        public readonly OwnEvaBodyHandle OwnEvaBody;
    }

    public sealed class OwnEvaBodyCols
    {
        public global::SpacetimeDB.Col<EvaBodyStatus, string> CharacterId { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, string> SystemId { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, string> Phase { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, double> X { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, double> Y { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, double> Vx { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, double> Vy { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, double> Heading { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, string> AnchorShipId { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, double> LocalX { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, double> LocalY { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, double> LocalHeading { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, string> RefShipId { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, double> Forward { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, double> Strafe { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, double> Turn { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, bool> Walking { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, string> ExitShipId { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, string> VisitId { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, string> DeckId { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, ulong> ReturnEndsMicros { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, bool> Stranded { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, ulong> ServerTick { get; }
        public global::SpacetimeDB.Col<EvaBodyStatus, ulong> Revision { get; }

        public OwnEvaBodyCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.Col<EvaBodyStatus, string>(tableName, "character_id");
            SystemId = new global::SpacetimeDB.Col<EvaBodyStatus, string>(tableName, "system_id");
            Phase = new global::SpacetimeDB.Col<EvaBodyStatus, string>(tableName, "phase");
            X = new global::SpacetimeDB.Col<EvaBodyStatus, double>(tableName, "x");
            Y = new global::SpacetimeDB.Col<EvaBodyStatus, double>(tableName, "y");
            Vx = new global::SpacetimeDB.Col<EvaBodyStatus, double>(tableName, "vx");
            Vy = new global::SpacetimeDB.Col<EvaBodyStatus, double>(tableName, "vy");
            Heading = new global::SpacetimeDB.Col<EvaBodyStatus, double>(tableName, "heading");
            AnchorShipId = new global::SpacetimeDB.Col<EvaBodyStatus, string>(tableName, "anchor_ship_id");
            LocalX = new global::SpacetimeDB.Col<EvaBodyStatus, double>(tableName, "local_x");
            LocalY = new global::SpacetimeDB.Col<EvaBodyStatus, double>(tableName, "local_y");
            LocalHeading = new global::SpacetimeDB.Col<EvaBodyStatus, double>(tableName, "local_heading");
            RefShipId = new global::SpacetimeDB.Col<EvaBodyStatus, string>(tableName, "ref_ship_id");
            Forward = new global::SpacetimeDB.Col<EvaBodyStatus, double>(tableName, "forward");
            Strafe = new global::SpacetimeDB.Col<EvaBodyStatus, double>(tableName, "strafe");
            Turn = new global::SpacetimeDB.Col<EvaBodyStatus, double>(tableName, "turn");
            Walking = new global::SpacetimeDB.Col<EvaBodyStatus, bool>(tableName, "walking");
            ExitShipId = new global::SpacetimeDB.Col<EvaBodyStatus, string>(tableName, "exit_ship_id");
            VisitId = new global::SpacetimeDB.Col<EvaBodyStatus, string>(tableName, "visit_id");
            DeckId = new global::SpacetimeDB.Col<EvaBodyStatus, string>(tableName, "deck_id");
            ReturnEndsMicros = new global::SpacetimeDB.Col<EvaBodyStatus, ulong>(tableName, "return_ends_micros");
            Stranded = new global::SpacetimeDB.Col<EvaBodyStatus, bool>(tableName, "stranded");
            ServerTick = new global::SpacetimeDB.Col<EvaBodyStatus, ulong>(tableName, "server_tick");
            Revision = new global::SpacetimeDB.Col<EvaBodyStatus, ulong>(tableName, "revision");
        }
    }

    public sealed class OwnEvaBodyIxCols
    {
        public global::SpacetimeDB.IxCol<EvaBodyStatus, string> CharacterId { get; }

        public OwnEvaBodyIxCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.IxCol<EvaBodyStatus, string>(tableName, "character_id");
        }
    }
}
