// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnGroundItemsHandle : RemoteTableHandle<EventContext, VisibleGroundItem>
        {
            public override string RemoteTableName => "own_ground_items";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(VisibleGroundItem row) => row.Id;

                public IdUniqueIndex(OwnGroundItemsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OwnGroundItemsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(VisibleGroundItem row) => row.Id;
        }

        public readonly OwnGroundItemsHandle OwnGroundItems;
    }

    public sealed class OwnGroundItemsCols
    {
        public global::SpacetimeDB.Col<VisibleGroundItem, string> Id { get; }
        public global::SpacetimeDB.Col<VisibleGroundItem, string> DefinitionId { get; }
        public global::SpacetimeDB.Col<VisibleGroundItem, double> LocalX { get; }
        public global::SpacetimeDB.Col<VisibleGroundItem, double> LocalY { get; }
        public global::SpacetimeDB.Col<VisibleGroundItem, bool> Reachable { get; }
        public global::SpacetimeDB.Col<VisibleGroundItem, string> InstanceId { get; }
        public global::SpacetimeDB.Col<VisibleGroundItem, string> DeckId { get; }
        public global::SpacetimeDB.Col<VisibleGroundItem, double> ElevationM { get; }

        public OwnGroundItemsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<VisibleGroundItem, string>(tableName, "id");
            DefinitionId = new global::SpacetimeDB.Col<VisibleGroundItem, string>(tableName, "definition_id");
            LocalX = new global::SpacetimeDB.Col<VisibleGroundItem, double>(tableName, "local_x");
            LocalY = new global::SpacetimeDB.Col<VisibleGroundItem, double>(tableName, "local_y");
            Reachable = new global::SpacetimeDB.Col<VisibleGroundItem, bool>(tableName, "reachable");
            InstanceId = new global::SpacetimeDB.Col<VisibleGroundItem, string>(tableName, "instance_id");
            DeckId = new global::SpacetimeDB.Col<VisibleGroundItem, string>(tableName, "deck_id");
            ElevationM = new global::SpacetimeDB.Col<VisibleGroundItem, double>(tableName, "elevation_m");
        }
    }

    public sealed class OwnGroundItemsIxCols
    {
        public global::SpacetimeDB.IxCol<VisibleGroundItem, string> Id { get; }

        public OwnGroundItemsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<VisibleGroundItem, string>(tableName, "id");
        }
    }
}
