// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnGameShipAccessHandle : RemoteTableHandle<EventContext, GameShipAccessStatus>
        {
            public override string RemoteTableName => "own_game_ship_access";

            public sealed class ShipIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(GameShipAccessStatus row) => row.ShipId;

                public ShipIdUniqueIndex(OwnGameShipAccessHandle table) : base(table) { }
            }

            public readonly ShipIdUniqueIndex ShipId;

            internal OwnGameShipAccessHandle(DbConnection conn) : base(conn)
            {
                ShipId = new(this);
            }

            protected override object GetPrimaryKey(GameShipAccessStatus row) => row.ShipId;
        }

        public readonly OwnGameShipAccessHandle OwnGameShipAccess;
    }

    public sealed class OwnGameShipAccessCols
    {
        public global::SpacetimeDB.Col<GameShipAccessStatus, string> ShipId { get; }
        public global::SpacetimeDB.Col<GameShipAccessStatus, string> CharacterId { get; }
        public global::SpacetimeDB.Col<GameShipAccessStatus, string> InstanceId { get; }
        public global::SpacetimeDB.Col<GameShipAccessStatus, string> DeckId { get; }
        public global::SpacetimeDB.Col<GameShipAccessStatus, ulong> Revision { get; }
        public global::SpacetimeDB.Col<GameShipAccessStatus, string> TemplateSha256 { get; }

        public OwnGameShipAccessCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.Col<GameShipAccessStatus, string>(tableName, "ship_id");
            CharacterId = new global::SpacetimeDB.Col<GameShipAccessStatus, string>(tableName, "character_id");
            InstanceId = new global::SpacetimeDB.Col<GameShipAccessStatus, string>(tableName, "instance_id");
            DeckId = new global::SpacetimeDB.Col<GameShipAccessStatus, string>(tableName, "deck_id");
            Revision = new global::SpacetimeDB.Col<GameShipAccessStatus, ulong>(tableName, "revision");
            TemplateSha256 = new global::SpacetimeDB.Col<GameShipAccessStatus, string>(tableName, "template_sha_256");
        }
    }

    public sealed class OwnGameShipAccessIxCols
    {
        public global::SpacetimeDB.IxCol<GameShipAccessStatus, string> ShipId { get; }

        public OwnGameShipAccessIxCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.IxCol<GameShipAccessStatus, string>(tableName, "ship_id");
        }
    }
}
