// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnInventoryStateHandle : RemoteTableHandle<EventContext, InventoryStatus>
        {
            public override string RemoteTableName => "own_inventory_state";

            public sealed class PocketsIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(InventoryStatus row) => row.PocketsId;

                public PocketsIdUniqueIndex(OwnInventoryStateHandle table) : base(table) { }
            }

            public readonly PocketsIdUniqueIndex PocketsId;

            internal OwnInventoryStateHandle(DbConnection conn) : base(conn)
            {
                PocketsId = new(this);
            }

            protected override object GetPrimaryKey(InventoryStatus row) => row.PocketsId;
        }

        public readonly OwnInventoryStateHandle OwnInventoryState;
    }

    public sealed class OwnInventoryStateCols
    {
        public global::SpacetimeDB.Col<InventoryStatus, ulong> Revision { get; }
        public global::SpacetimeDB.Col<InventoryStatus, bool> KitGranted { get; }
        public global::SpacetimeDB.Col<InventoryStatus, string> PocketsId { get; }
        public global::SpacetimeDB.Col<InventoryStatus, double> CarriedMassKg { get; }
        public global::SpacetimeDB.Col<InventoryStatus, double> CarryLimitKg { get; }

        public OwnInventoryStateCols(string tableName)
        {
            Revision = new global::SpacetimeDB.Col<InventoryStatus, ulong>(tableName, "revision");
            KitGranted = new global::SpacetimeDB.Col<InventoryStatus, bool>(tableName, "kit_granted");
            PocketsId = new global::SpacetimeDB.Col<InventoryStatus, string>(tableName, "pockets_id");
            CarriedMassKg = new global::SpacetimeDB.Col<InventoryStatus, double>(tableName, "carried_mass_kg");
            CarryLimitKg = new global::SpacetimeDB.Col<InventoryStatus, double>(tableName, "carry_limit_kg");
        }
    }

    public sealed class OwnInventoryStateIxCols
    {
        public global::SpacetimeDB.IxCol<InventoryStatus, string> PocketsId { get; }

        public OwnInventoryStateIxCols(string tableName)
        {
            PocketsId = new global::SpacetimeDB.IxCol<InventoryStatus, string>(tableName, "pockets_id");
        }
    }
}
