// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnInventoryContainersHandle : RemoteTableHandle<EventContext, VisibleInventoryContainer>
        {
            public override string RemoteTableName => "own_inventory_containers";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(VisibleInventoryContainer row) => row.Id;

                public IdUniqueIndex(OwnInventoryContainersHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OwnInventoryContainersHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(VisibleInventoryContainer row) => row.Id;
        }

        public readonly OwnInventoryContainersHandle OwnInventoryContainers;
    }

    public sealed class OwnInventoryContainersCols
    {
        public global::SpacetimeDB.Col<VisibleInventoryContainer, string> PlacementId { get; }
        public global::SpacetimeDB.Col<VisibleInventoryContainer, string> Id { get; }
        public global::SpacetimeDB.Col<VisibleInventoryContainer, string> ParentItemId { get; }
        public global::SpacetimeDB.Col<VisibleInventoryContainer, string> Kind { get; }
        public global::SpacetimeDB.Col<VisibleInventoryContainer, string> Name { get; }
        public global::SpacetimeDB.Col<VisibleInventoryContainer, uint> Width { get; }
        public global::SpacetimeDB.Col<VisibleInventoryContainer, uint> Height { get; }
        public global::SpacetimeDB.Col<VisibleInventoryContainer, double> MaxMassKg { get; }
        public global::SpacetimeDB.Col<VisibleInventoryContainer, double> CapacityLitres { get; }
        public global::SpacetimeDB.Col<VisibleInventoryContainer, double> AmountLitres { get; }
        public global::SpacetimeDB.Col<VisibleInventoryContainer, string> LiquidType { get; }
        public global::SpacetimeDB.Col<VisibleInventoryContainer, bool> Carried { get; }

        public OwnInventoryContainersCols(string tableName)
        {
            PlacementId = new global::SpacetimeDB.Col<VisibleInventoryContainer, string>(tableName, "placement_id");
            Id = new global::SpacetimeDB.Col<VisibleInventoryContainer, string>(tableName, "id");
            ParentItemId = new global::SpacetimeDB.Col<VisibleInventoryContainer, string>(tableName, "parent_item_id");
            Kind = new global::SpacetimeDB.Col<VisibleInventoryContainer, string>(tableName, "kind");
            Name = new global::SpacetimeDB.Col<VisibleInventoryContainer, string>(tableName, "name");
            Width = new global::SpacetimeDB.Col<VisibleInventoryContainer, uint>(tableName, "width");
            Height = new global::SpacetimeDB.Col<VisibleInventoryContainer, uint>(tableName, "height");
            MaxMassKg = new global::SpacetimeDB.Col<VisibleInventoryContainer, double>(tableName, "max_mass_kg");
            CapacityLitres = new global::SpacetimeDB.Col<VisibleInventoryContainer, double>(tableName, "capacity_litres");
            AmountLitres = new global::SpacetimeDB.Col<VisibleInventoryContainer, double>(tableName, "amount_litres");
            LiquidType = new global::SpacetimeDB.Col<VisibleInventoryContainer, string>(tableName, "liquid_type");
            Carried = new global::SpacetimeDB.Col<VisibleInventoryContainer, bool>(tableName, "carried");
        }
    }

    public sealed class OwnInventoryContainersIxCols
    {
        public global::SpacetimeDB.IxCol<VisibleInventoryContainer, string> Id { get; }

        public OwnInventoryContainersIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<VisibleInventoryContainer, string>(tableName, "id");
        }
    }
}
