// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnInventoryHotbarHandle : RemoteTableHandle<EventContext, VisibleInventoryHotbar>
        {
            public override string RemoteTableName => "own_inventory_hotbar";

            public sealed class SlotUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(VisibleInventoryHotbar row) => row.Slot;

                public SlotUniqueIndex(OwnInventoryHotbarHandle table) : base(table) { }
            }

            public readonly SlotUniqueIndex Slot;

            internal OwnInventoryHotbarHandle(DbConnection conn) : base(conn)
            {
                Slot = new(this);
            }

            protected override object GetPrimaryKey(VisibleInventoryHotbar row) => row.Slot;
        }

        public readonly OwnInventoryHotbarHandle OwnInventoryHotbar;
    }

    public sealed class OwnInventoryHotbarCols
    {
        public global::SpacetimeDB.Col<VisibleInventoryHotbar, byte> Slot { get; }
        public global::SpacetimeDB.Col<VisibleInventoryHotbar, string> ItemId { get; }

        public OwnInventoryHotbarCols(string tableName)
        {
            Slot = new global::SpacetimeDB.Col<VisibleInventoryHotbar, byte>(tableName, "slot");
            ItemId = new global::SpacetimeDB.Col<VisibleInventoryHotbar, string>(tableName, "item_id");
        }
    }

    public sealed class OwnInventoryHotbarIxCols
    {
        public global::SpacetimeDB.IxCol<VisibleInventoryHotbar, byte> Slot { get; }

        public OwnInventoryHotbarIxCols(string tableName)
        {
            Slot = new global::SpacetimeDB.IxCol<VisibleInventoryHotbar, byte>(tableName, "slot");
        }
    }
}
