// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnInventoryItemsHandle : RemoteTableHandle<EventContext, VisibleInventoryItem>
        {
            public override string RemoteTableName => "own_inventory_items";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(VisibleInventoryItem row) => row.Id;

                public IdUniqueIndex(OwnInventoryItemsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OwnInventoryItemsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(VisibleInventoryItem row) => row.Id;
        }

        public readonly OwnInventoryItemsHandle OwnInventoryItems;
    }

    public sealed class OwnInventoryItemsCols
    {
        public global::SpacetimeDB.Col<VisibleInventoryItem, string> Id { get; }
        public global::SpacetimeDB.Col<VisibleInventoryItem, string> DefinitionId { get; }
        public global::SpacetimeDB.Col<VisibleInventoryItem, string> ContainerId { get; }
        public global::SpacetimeDB.Col<VisibleInventoryItem, string> EquipmentSlot { get; }
        public global::SpacetimeDB.Col<VisibleInventoryItem, int> X { get; }
        public global::SpacetimeDB.Col<VisibleInventoryItem, int> Y { get; }
        public global::SpacetimeDB.Col<VisibleInventoryItem, bool> Rotated { get; }

        public OwnInventoryItemsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<VisibleInventoryItem, string>(tableName, "id");
            DefinitionId = new global::SpacetimeDB.Col<VisibleInventoryItem, string>(tableName, "definition_id");
            ContainerId = new global::SpacetimeDB.Col<VisibleInventoryItem, string>(tableName, "container_id");
            EquipmentSlot = new global::SpacetimeDB.Col<VisibleInventoryItem, string>(tableName, "equipment_slot");
            X = new global::SpacetimeDB.Col<VisibleInventoryItem, int>(tableName, "x");
            Y = new global::SpacetimeDB.Col<VisibleInventoryItem, int>(tableName, "y");
            Rotated = new global::SpacetimeDB.Col<VisibleInventoryItem, bool>(tableName, "rotated");
        }
    }

    public sealed class OwnInventoryItemsIxCols
    {
        public global::SpacetimeDB.IxCol<VisibleInventoryItem, string> Id { get; }

        public OwnInventoryItemsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<VisibleInventoryItem, string>(tableName, "id");
        }
    }
}
