// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnNativeAirlocksHandle : RemoteTableHandle<EventContext, NativeAirlockStatus>
        {
            public override string RemoteTableName => "own_native_airlocks";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(NativeAirlockStatus row) => row.Id;

                public IdUniqueIndex(OwnNativeAirlocksHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OwnNativeAirlocksHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(NativeAirlockStatus row) => row.Id;
        }

        public readonly OwnNativeAirlocksHandle OwnNativeAirlocks;
    }

    public sealed class OwnNativeAirlocksCols
    {
        public global::SpacetimeDB.Col<NativeAirlockStatus, string> Id { get; }
        public global::SpacetimeDB.Col<NativeAirlockStatus, string> DeckId { get; }
        public global::SpacetimeDB.Col<NativeAirlockStatus, string> InnerDoorId { get; }
        public global::SpacetimeDB.Col<NativeAirlockStatus, string> OuterDoorId { get; }
        public global::SpacetimeDB.Col<NativeAirlockStatus, double> InnerFraction { get; }
        public global::SpacetimeDB.Col<NativeAirlockStatus, double> OuterFraction { get; }
        public global::SpacetimeDB.Col<NativeAirlockStatus, double> InnerSealRetraction { get; }
        public global::SpacetimeDB.Col<NativeAirlockStatus, double> OuterSealRetraction { get; }
        public global::SpacetimeDB.Col<NativeAirlockStatus, double> InteriorPressurePa { get; }
        public global::SpacetimeDB.Col<NativeAirlockStatus, double> ChamberPressurePa { get; }
        public global::SpacetimeDB.Col<NativeAirlockStatus, double> OuterPressurePa { get; }
        public global::SpacetimeDB.Col<NativeAirlockStatus, bool> ManualServiceActive { get; }
        public global::SpacetimeDB.Col<NativeAirlockStatus, bool> InnerCanService { get; }
        public global::SpacetimeDB.Col<NativeAirlockStatus, bool> OuterCanService { get; }
        public global::SpacetimeDB.Col<NativeAirlockStatus, ulong> Revision { get; }

        public OwnNativeAirlocksCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<NativeAirlockStatus, string>(tableName, "id");
            DeckId = new global::SpacetimeDB.Col<NativeAirlockStatus, string>(tableName, "deck_id");
            InnerDoorId = new global::SpacetimeDB.Col<NativeAirlockStatus, string>(tableName, "inner_door_id");
            OuterDoorId = new global::SpacetimeDB.Col<NativeAirlockStatus, string>(tableName, "outer_door_id");
            InnerFraction = new global::SpacetimeDB.Col<NativeAirlockStatus, double>(tableName, "inner_fraction");
            OuterFraction = new global::SpacetimeDB.Col<NativeAirlockStatus, double>(tableName, "outer_fraction");
            InnerSealRetraction = new global::SpacetimeDB.Col<NativeAirlockStatus, double>(tableName, "inner_seal_retraction");
            OuterSealRetraction = new global::SpacetimeDB.Col<NativeAirlockStatus, double>(tableName, "outer_seal_retraction");
            InteriorPressurePa = new global::SpacetimeDB.Col<NativeAirlockStatus, double>(tableName, "interior_pressure_pa");
            ChamberPressurePa = new global::SpacetimeDB.Col<NativeAirlockStatus, double>(tableName, "chamber_pressure_pa");
            OuterPressurePa = new global::SpacetimeDB.Col<NativeAirlockStatus, double>(tableName, "outer_pressure_pa");
            ManualServiceActive = new global::SpacetimeDB.Col<NativeAirlockStatus, bool>(tableName, "manual_service_active");
            InnerCanService = new global::SpacetimeDB.Col<NativeAirlockStatus, bool>(tableName, "inner_can_service");
            OuterCanService = new global::SpacetimeDB.Col<NativeAirlockStatus, bool>(tableName, "outer_can_service");
            Revision = new global::SpacetimeDB.Col<NativeAirlockStatus, ulong>(tableName, "revision");
        }
    }

    public sealed class OwnNativeAirlocksIxCols
    {
        public global::SpacetimeDB.IxCol<NativeAirlockStatus, string> Id { get; }

        public OwnNativeAirlocksIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<NativeAirlockStatus, string>(tableName, "id");
        }
    }
}
