// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnPassengerVisitHandle : RemoteTableHandle<EventContext, PassengerVisitStatus>
        {
            public override string RemoteTableName => "own_passenger_visit";

            public sealed class CharacterIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(PassengerVisitStatus row) => row.CharacterId;

                public CharacterIdUniqueIndex(OwnPassengerVisitHandle table) : base(table) { }
            }

            public readonly CharacterIdUniqueIndex CharacterId;

            internal OwnPassengerVisitHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
            }

            protected override object GetPrimaryKey(PassengerVisitStatus row) => row.CharacterId;
        }

        public readonly OwnPassengerVisitHandle OwnPassengerVisit;
    }

    public sealed class OwnPassengerVisitCols
    {
        public global::SpacetimeDB.Col<PassengerVisitStatus, string> CharacterId { get; }
        public global::SpacetimeDB.Col<PassengerVisitStatus, string> ShipId { get; }
        public global::SpacetimeDB.Col<PassengerVisitStatus, string> DeckId { get; }
        public global::SpacetimeDB.Col<PassengerVisitStatus, string> VisitId { get; }
        public global::SpacetimeDB.Col<PassengerVisitStatus, string> GrantId { get; }
        public global::SpacetimeDB.Col<PassengerVisitStatus, ulong> Revision { get; }
        public global::SpacetimeDB.Col<PassengerVisitStatus, bool> Admitted { get; }
        public global::SpacetimeDB.Col<PassengerVisitStatus, string> RecoveryReason { get; }

        public OwnPassengerVisitCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.Col<PassengerVisitStatus, string>(tableName, "character_id");
            ShipId = new global::SpacetimeDB.Col<PassengerVisitStatus, string>(tableName, "ship_id");
            DeckId = new global::SpacetimeDB.Col<PassengerVisitStatus, string>(tableName, "deck_id");
            VisitId = new global::SpacetimeDB.Col<PassengerVisitStatus, string>(tableName, "visit_id");
            GrantId = new global::SpacetimeDB.Col<PassengerVisitStatus, string>(tableName, "grant_id");
            Revision = new global::SpacetimeDB.Col<PassengerVisitStatus, ulong>(tableName, "revision");
            Admitted = new global::SpacetimeDB.Col<PassengerVisitStatus, bool>(tableName, "admitted");
            RecoveryReason = new global::SpacetimeDB.Col<PassengerVisitStatus, string>(tableName, "recovery_reason");
        }
    }

    public sealed class OwnPassengerVisitIxCols
    {
        public global::SpacetimeDB.IxCol<PassengerVisitStatus, string> CharacterId { get; }

        public OwnPassengerVisitIxCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.IxCol<PassengerVisitStatus, string>(tableName, "character_id");
        }
    }
}
