// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnPassengerGrantsHandle : RemoteTableHandle<EventContext, PassengerAdmission>
        {
            public override string RemoteTableName => "own_passenger_grants";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(PassengerAdmission row) => row.Id;

                public IdUniqueIndex(OwnPassengerGrantsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OwnPassengerGrantsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(PassengerAdmission row) => row.Id;
        }

        public readonly OwnPassengerGrantsHandle OwnPassengerGrants;
    }

    public sealed class OwnPassengerGrantsCols
    {
        public global::SpacetimeDB.Col<PassengerAdmission, string> Id { get; }
        public global::SpacetimeDB.Col<PassengerAdmission, string> ShipId { get; }
        public global::SpacetimeDB.Col<PassengerAdmission, string> GranteeId { get; }
        public global::SpacetimeDB.Col<PassengerAdmission, string> DeckId { get; }
        public global::SpacetimeDB.Col<PassengerAdmission, ulong> InstanceRevision { get; }
        public global::SpacetimeDB.Col<PassengerAdmission, ulong> ExpiresMicros { get; }
        public global::SpacetimeDB.Col<PassengerAdmission, ulong> Revision { get; }
        public global::SpacetimeDB.Col<PassengerAdmission, bool> IssuedByYou { get; }

        public OwnPassengerGrantsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<PassengerAdmission, string>(tableName, "id");
            ShipId = new global::SpacetimeDB.Col<PassengerAdmission, string>(tableName, "ship_id");
            GranteeId = new global::SpacetimeDB.Col<PassengerAdmission, string>(tableName, "grantee_id");
            DeckId = new global::SpacetimeDB.Col<PassengerAdmission, string>(tableName, "deck_id");
            InstanceRevision = new global::SpacetimeDB.Col<PassengerAdmission, ulong>(tableName, "instance_revision");
            ExpiresMicros = new global::SpacetimeDB.Col<PassengerAdmission, ulong>(tableName, "expires_micros");
            Revision = new global::SpacetimeDB.Col<PassengerAdmission, ulong>(tableName, "revision");
            IssuedByYou = new global::SpacetimeDB.Col<PassengerAdmission, bool>(tableName, "issued_by_you");
        }
    }

    public sealed class OwnPassengerGrantsIxCols
    {
        public global::SpacetimeDB.IxCol<PassengerAdmission, string> Id { get; }

        public OwnPassengerGrantsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<PassengerAdmission, string>(tableName, "id");
        }
    }
}
