// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnReachableCargoItemsHandle : RemoteTableHandle<EventContext, ScopedCargoItemStatus>
        {
            public override string RemoteTableName => "own_reachable_cargo_items";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ScopedCargoItemStatus row) => row.Id;

                public IdUniqueIndex(OwnReachableCargoItemsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OwnReachableCargoItemsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ScopedCargoItemStatus row) => row.Id;
        }

        public readonly OwnReachableCargoItemsHandle OwnReachableCargoItems;
    }

    public sealed class OwnReachableCargoItemsCols
    {
        public global::SpacetimeDB.Col<ScopedCargoItemStatus, string> Id { get; }
        public global::SpacetimeDB.Col<ScopedCargoItemStatus, string> DefinitionId { get; }
        public global::SpacetimeDB.Col<ScopedCargoItemStatus, string> ContainerId { get; }
        public global::SpacetimeDB.Col<ScopedCargoItemStatus, int> X { get; }
        public global::SpacetimeDB.Col<ScopedCargoItemStatus, int> Y { get; }
        public global::SpacetimeDB.Col<ScopedCargoItemStatus, bool> Rotated { get; }
        public global::SpacetimeDB.Col<ScopedCargoItemStatus, ulong> Revision { get; }

        public OwnReachableCargoItemsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ScopedCargoItemStatus, string>(tableName, "id");
            DefinitionId = new global::SpacetimeDB.Col<ScopedCargoItemStatus, string>(tableName, "definition_id");
            ContainerId = new global::SpacetimeDB.Col<ScopedCargoItemStatus, string>(tableName, "container_id");
            X = new global::SpacetimeDB.Col<ScopedCargoItemStatus, int>(tableName, "x");
            Y = new global::SpacetimeDB.Col<ScopedCargoItemStatus, int>(tableName, "y");
            Rotated = new global::SpacetimeDB.Col<ScopedCargoItemStatus, bool>(tableName, "rotated");
            Revision = new global::SpacetimeDB.Col<ScopedCargoItemStatus, ulong>(tableName, "revision");
        }
    }

    public sealed class OwnReachableCargoItemsIxCols
    {
        public global::SpacetimeDB.IxCol<ScopedCargoItemStatus, string> Id { get; }

        public OwnReachableCargoItemsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ScopedCargoItemStatus, string>(tableName, "id");
        }
    }
}
