// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnShipSystemsReportHandle : RemoteTableHandle<EventContext, ShipSystemsReportRow>
        {
            public override string RemoteTableName => "own_ship_systems_report";

            public sealed class ShipIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ShipSystemsReportRow row) => row.ShipId;

                public ShipIdUniqueIndex(OwnShipSystemsReportHandle table) : base(table) { }
            }

            public readonly ShipIdUniqueIndex ShipId;

            internal OwnShipSystemsReportHandle(DbConnection conn) : base(conn)
            {
                ShipId = new(this);
            }

            protected override object GetPrimaryKey(ShipSystemsReportRow row) => row.ShipId;
        }

        public readonly OwnShipSystemsReportHandle OwnShipSystemsReport;
    }

    public sealed class OwnShipSystemsReportCols
    {
        public global::SpacetimeDB.Col<ShipSystemsReportRow, string> ShipId { get; }
        public global::SpacetimeDB.Col<ShipSystemsReportRow, ulong> CompileRevision { get; }
        public global::SpacetimeDB.Col<ShipSystemsReportRow, ulong> InstanceRevision { get; }
        public global::SpacetimeDB.Col<ShipSystemsReportRow, string> Catalog { get; }
        public global::SpacetimeDB.Col<ShipSystemsReportRow, string> PrefabId { get; }
        public global::SpacetimeDB.Col<ShipSystemsReportRow, uint> PrefabRevision { get; }
        public global::SpacetimeDB.Col<ShipSystemsReportRow, string> ReportJson { get; }

        public OwnShipSystemsReportCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.Col<ShipSystemsReportRow, string>(tableName, "ship_id");
            CompileRevision = new global::SpacetimeDB.Col<ShipSystemsReportRow, ulong>(tableName, "compile_revision");
            InstanceRevision = new global::SpacetimeDB.Col<ShipSystemsReportRow, ulong>(tableName, "instance_revision");
            Catalog = new global::SpacetimeDB.Col<ShipSystemsReportRow, string>(tableName, "catalog");
            PrefabId = new global::SpacetimeDB.Col<ShipSystemsReportRow, string>(tableName, "prefab_id");
            PrefabRevision = new global::SpacetimeDB.Col<ShipSystemsReportRow, uint>(tableName, "prefab_revision");
            ReportJson = new global::SpacetimeDB.Col<ShipSystemsReportRow, string>(tableName, "report_json");
        }
    }

    public sealed class OwnShipSystemsReportIxCols
    {
        public global::SpacetimeDB.IxCol<ShipSystemsReportRow, string> ShipId { get; }

        public OwnShipSystemsReportIxCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.IxCol<ShipSystemsReportRow, string>(tableName, "ship_id");
        }
    }
}
