// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnShipPowerDevicesHandle : RemoteTableHandle<EventContext, ShipPowerDeviceStatus>
        {
            public override string RemoteTableName => "own_ship_power_devices";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ShipPowerDeviceStatus row) => row.Id;

                public IdUniqueIndex(OwnShipPowerDevicesHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OwnShipPowerDevicesHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ShipPowerDeviceStatus row) => row.Id;
        }

        public readonly OwnShipPowerDevicesHandle OwnShipPowerDevices;
    }

    public sealed class OwnShipPowerDevicesCols
    {
        public global::SpacetimeDB.Col<ShipPowerDeviceStatus, string> Id { get; }
        public global::SpacetimeDB.Col<ShipPowerDeviceStatus, string> ShipId { get; }
        public global::SpacetimeDB.Col<ShipPowerDeviceStatus, string> MountId { get; }
        public global::SpacetimeDB.Col<ShipPowerDeviceStatus, string> Definition { get; }
        public global::SpacetimeDB.Col<ShipPowerDeviceStatus, double> EnergyJ { get; }
        public global::SpacetimeDB.Col<ShipPowerDeviceStatus, bool> Running { get; }

        public OwnShipPowerDevicesCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ShipPowerDeviceStatus, string>(tableName, "id");
            ShipId = new global::SpacetimeDB.Col<ShipPowerDeviceStatus, string>(tableName, "ship_id");
            MountId = new global::SpacetimeDB.Col<ShipPowerDeviceStatus, string>(tableName, "mount_id");
            Definition = new global::SpacetimeDB.Col<ShipPowerDeviceStatus, string>(tableName, "definition");
            EnergyJ = new global::SpacetimeDB.Col<ShipPowerDeviceStatus, double>(tableName, "energy_j");
            Running = new global::SpacetimeDB.Col<ShipPowerDeviceStatus, bool>(tableName, "running");
        }
    }

    public sealed class OwnShipPowerDevicesIxCols
    {
        public global::SpacetimeDB.IxCol<ShipPowerDeviceStatus, string> Id { get; }

        public OwnShipPowerDevicesIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ShipPowerDeviceStatus, string>(tableName, "id");
        }
    }
}
