// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class OwnWorldAdmissionHandle : RemoteTableHandle<EventContext, SharedAdmissionProjection>
        {
            public override string RemoteTableName => "own_world_admission";

            public sealed class CharacterIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(SharedAdmissionProjection row) => row.CharacterId;

                public CharacterIdUniqueIndex(OwnWorldAdmissionHandle table) : base(table) { }
            }

            public readonly CharacterIdUniqueIndex CharacterId;

            internal OwnWorldAdmissionHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
            }

            protected override object GetPrimaryKey(SharedAdmissionProjection row) => row.CharacterId;
        }

        public readonly OwnWorldAdmissionHandle OwnWorldAdmission;
    }

    public sealed class OwnWorldAdmissionCols
    {
        public global::SpacetimeDB.Col<SharedAdmissionProjection, string> CharacterId { get; }
        public global::SpacetimeDB.Col<SharedAdmissionProjection, string> ShipId { get; }
        public global::SpacetimeDB.Col<SharedAdmissionProjection, string> SystemId { get; }
        public global::SpacetimeDB.Col<SharedAdmissionProjection, ulong> Revision { get; }

        public OwnWorldAdmissionCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.Col<SharedAdmissionProjection, string>(tableName, "character_id");
            ShipId = new global::SpacetimeDB.Col<SharedAdmissionProjection, string>(tableName, "ship_id");
            SystemId = new global::SpacetimeDB.Col<SharedAdmissionProjection, string>(tableName, "system_id");
            Revision = new global::SpacetimeDB.Col<SharedAdmissionProjection, ulong>(tableName, "revision");
        }
    }

    public sealed class OwnWorldAdmissionIxCols
    {
        public global::SpacetimeDB.IxCol<SharedAdmissionProjection, string> CharacterId { get; }

        public OwnWorldAdmissionIxCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.IxCol<SharedAdmissionProjection, string>(tableName, "character_id");
        }
    }
}
