// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class PublishedItemDefinitionsHandle : RemoteTableHandle<EventContext, PublishedItemDefinition>
        {
            public override string RemoteTableName => "published_item_definitions";

            public sealed class DefinitionRefUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(PublishedItemDefinition row) => row.DefinitionRef;

                public DefinitionRefUniqueIndex(PublishedItemDefinitionsHandle table) : base(table) { }
            }

            public readonly DefinitionRefUniqueIndex DefinitionRef;

            internal PublishedItemDefinitionsHandle(DbConnection conn) : base(conn)
            {
                DefinitionRef = new(this);
            }

            protected override object GetPrimaryKey(PublishedItemDefinition row) => row.DefinitionRef;
        }

        public readonly PublishedItemDefinitionsHandle PublishedItemDefinitions;
    }

    public sealed class PublishedItemDefinitionsCols
    {
        public global::SpacetimeDB.Col<PublishedItemDefinition, string> DefinitionRef { get; }
        public global::SpacetimeDB.Col<PublishedItemDefinition, string> Kind { get; }
        public global::SpacetimeDB.Col<PublishedItemDefinition, string> DefinitionId { get; }
        public global::SpacetimeDB.Col<PublishedItemDefinition, ulong> Revision { get; }
        public global::SpacetimeDB.Col<PublishedItemDefinition, string> Status { get; }
        public global::SpacetimeDB.Col<PublishedItemDefinition, string> PayloadJson { get; }
        public global::SpacetimeDB.Col<PublishedItemDefinition, string> Sha256 { get; }

        public PublishedItemDefinitionsCols(string tableName)
        {
            DefinitionRef = new global::SpacetimeDB.Col<PublishedItemDefinition, string>(tableName, "definition_ref");
            Kind = new global::SpacetimeDB.Col<PublishedItemDefinition, string>(tableName, "kind");
            DefinitionId = new global::SpacetimeDB.Col<PublishedItemDefinition, string>(tableName, "definition_id");
            Revision = new global::SpacetimeDB.Col<PublishedItemDefinition, ulong>(tableName, "revision");
            Status = new global::SpacetimeDB.Col<PublishedItemDefinition, string>(tableName, "status");
            PayloadJson = new global::SpacetimeDB.Col<PublishedItemDefinition, string>(tableName, "payload_json");
            Sha256 = new global::SpacetimeDB.Col<PublishedItemDefinition, string>(tableName, "sha_256");
        }
    }

    public sealed class PublishedItemDefinitionsIxCols
    {
        public global::SpacetimeDB.IxCol<PublishedItemDefinition, string> DefinitionRef { get; }

        public PublishedItemDefinitionsIxCols(string tableName)
        {
            DefinitionRef = new global::SpacetimeDB.IxCol<PublishedItemDefinition, string>(tableName, "definition_ref");
        }
    }
}
