// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class VisibleShipSystemEffectsHandle : RemoteTableHandle<EventContext, ShipSystemEffects>
        {
            public override string RemoteTableName => "visible_ship_system_effects";

            public sealed class ShipIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ShipSystemEffects row) => row.ShipId;

                public ShipIdUniqueIndex(VisibleShipSystemEffectsHandle table) : base(table) { }
            }

            public readonly ShipIdUniqueIndex ShipId;

            internal VisibleShipSystemEffectsHandle(DbConnection conn) : base(conn)
            {
                ShipId = new(this);
            }

            protected override object GetPrimaryKey(ShipSystemEffects row) => row.ShipId;
        }

        public readonly VisibleShipSystemEffectsHandle VisibleShipSystemEffects;
    }

    public sealed class VisibleShipSystemEffectsCols
    {
        public global::SpacetimeDB.Col<ShipSystemEffects, string> ShipId { get; }
        public global::SpacetimeDB.Col<ShipSystemEffects, string> Power { get; }

        public VisibleShipSystemEffectsCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.Col<ShipSystemEffects, string>(tableName, "ship_id");
            Power = new global::SpacetimeDB.Col<ShipSystemEffects, string>(tableName, "power");
        }
    }

    public sealed class VisibleShipSystemEffectsIxCols
    {
        public global::SpacetimeDB.IxCol<ShipSystemEffects, string> ShipId { get; }

        public VisibleShipSystemEffectsIxCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.IxCol<ShipSystemEffects, string>(tableName, "ship_id");
        }
    }
}
