// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class VisibleCrewPresentationHandle : RemoteTableHandle<EventContext, CrewPresentation>
        {
            public override string RemoteTableName => "visible_crew_presentation";

            public sealed class CharacterIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(CrewPresentation row) => row.CharacterId;

                public CharacterIdUniqueIndex(VisibleCrewPresentationHandle table) : base(table) { }
            }

            public readonly CharacterIdUniqueIndex CharacterId;

            internal VisibleCrewPresentationHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
            }

            protected override object GetPrimaryKey(CrewPresentation row) => row.CharacterId;
        }

        public readonly VisibleCrewPresentationHandle VisibleCrewPresentation;
    }

    public sealed class VisibleCrewPresentationCols
    {
        public global::SpacetimeDB.Col<CrewPresentation, string> CharacterId { get; }
        public global::SpacetimeDB.Col<CrewPresentation, string> ShipId { get; }
        public global::SpacetimeDB.Col<CrewPresentation, string> DeckId { get; }
        public global::SpacetimeDB.Col<CrewPresentation, string> AppearanceJson { get; }
        public global::SpacetimeDB.Col<CrewPresentation, string> EquipmentJson { get; }
        public global::SpacetimeDB.Col<CrewPresentation, bool> Dead { get; }
        public global::SpacetimeDB.Col<CrewPresentation, bool> Seated { get; }
        public global::SpacetimeDB.Col<CrewPresentation, bool> AimActive { get; }
        public global::SpacetimeDB.Col<CrewPresentation, double> AimAngle { get; }
        public global::SpacetimeDB.Col<CrewPresentation, ulong> ShotSequence { get; }
        public global::SpacetimeDB.Col<CrewPresentation, double> ShotX { get; }
        public global::SpacetimeDB.Col<CrewPresentation, double> ShotY { get; }
        public global::SpacetimeDB.Col<CrewPresentation, bool> ShotStruck { get; }

        public VisibleCrewPresentationCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.Col<CrewPresentation, string>(tableName, "character_id");
            ShipId = new global::SpacetimeDB.Col<CrewPresentation, string>(tableName, "ship_id");
            DeckId = new global::SpacetimeDB.Col<CrewPresentation, string>(tableName, "deck_id");
            AppearanceJson = new global::SpacetimeDB.Col<CrewPresentation, string>(tableName, "appearance_json");
            EquipmentJson = new global::SpacetimeDB.Col<CrewPresentation, string>(tableName, "equipment_json");
            Dead = new global::SpacetimeDB.Col<CrewPresentation, bool>(tableName, "dead");
            Seated = new global::SpacetimeDB.Col<CrewPresentation, bool>(tableName, "seated");
            AimActive = new global::SpacetimeDB.Col<CrewPresentation, bool>(tableName, "aim_active");
            AimAngle = new global::SpacetimeDB.Col<CrewPresentation, double>(tableName, "aim_angle");
            ShotSequence = new global::SpacetimeDB.Col<CrewPresentation, ulong>(tableName, "shot_sequence");
            ShotX = new global::SpacetimeDB.Col<CrewPresentation, double>(tableName, "shot_x");
            ShotY = new global::SpacetimeDB.Col<CrewPresentation, double>(tableName, "shot_y");
            ShotStruck = new global::SpacetimeDB.Col<CrewPresentation, bool>(tableName, "shot_struck");
        }
    }

    public sealed class VisibleCrewPresentationIxCols
    {
        public global::SpacetimeDB.IxCol<CrewPresentation, string> CharacterId { get; }

        public VisibleCrewPresentationIxCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.IxCol<CrewPresentation, string>(tableName, "character_id");
        }
    }
}
