// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class VisibleShipDescriptionsHandle : RemoteTableHandle<EventContext, SharedShipDescriptionProjection>
        {
            public override string RemoteTableName => "visible_ship_descriptions";

            public sealed class ShipIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(SharedShipDescriptionProjection row) => row.ShipId;

                public ShipIdUniqueIndex(VisibleShipDescriptionsHandle table) : base(table) { }
            }

            public readonly ShipIdUniqueIndex ShipId;

            internal VisibleShipDescriptionsHandle(DbConnection conn) : base(conn)
            {
                ShipId = new(this);
            }

            protected override object GetPrimaryKey(SharedShipDescriptionProjection row) => row.ShipId;
        }

        public readonly VisibleShipDescriptionsHandle VisibleShipDescriptions;
    }

    public sealed class VisibleShipDescriptionsCols
    {
        public global::SpacetimeDB.Col<SharedShipDescriptionProjection, string> ShipId { get; }
        public global::SpacetimeDB.Col<SharedShipDescriptionProjection, string> PublishedExteriorAssetId { get; }
        public global::SpacetimeDB.Col<SharedShipDescriptionProjection, ulong> AppearanceRevision { get; }
        public global::SpacetimeDB.Col<SharedShipDescriptionProjection, string> DisplayName { get; }

        public VisibleShipDescriptionsCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.Col<SharedShipDescriptionProjection, string>(tableName, "ship_id");
            PublishedExteriorAssetId = new global::SpacetimeDB.Col<SharedShipDescriptionProjection, string>(tableName, "published_exterior_asset_id");
            AppearanceRevision = new global::SpacetimeDB.Col<SharedShipDescriptionProjection, ulong>(tableName, "appearance_revision");
            DisplayName = new global::SpacetimeDB.Col<SharedShipDescriptionProjection, string>(tableName, "display_name");
        }
    }

    public sealed class VisibleShipDescriptionsIxCols
    {
        public global::SpacetimeDB.IxCol<SharedShipDescriptionProjection, string> ShipId { get; }

        public VisibleShipDescriptionsIxCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.IxCol<SharedShipDescriptionProjection, string>(tableName, "ship_id");
        }
    }
}
