// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class VisibleBodyDescriptionsHandle : RemoteTableHandle<EventContext, SharedBodyDescriptionProjection>
        {
            public override string RemoteTableName => "visible_body_descriptions";

            public sealed class BodyIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(SharedBodyDescriptionProjection row) => row.BodyId;

                public BodyIdUniqueIndex(VisibleBodyDescriptionsHandle table) : base(table) { }
            }

            public readonly BodyIdUniqueIndex BodyId;

            internal VisibleBodyDescriptionsHandle(DbConnection conn) : base(conn)
            {
                BodyId = new(this);
            }

            protected override object GetPrimaryKey(SharedBodyDescriptionProjection row) => row.BodyId;
        }

        public readonly VisibleBodyDescriptionsHandle VisibleBodyDescriptions;
    }

    public sealed class VisibleBodyDescriptionsCols
    {
        public global::SpacetimeDB.Col<SharedBodyDescriptionProjection, string> BodyId { get; }
        public global::SpacetimeDB.Col<SharedBodyDescriptionProjection, string> Kind { get; }
        public global::SpacetimeDB.Col<SharedBodyDescriptionProjection, string> Appearance { get; }
        public global::SpacetimeDB.Col<SharedBodyDescriptionProjection, uint> Seed { get; }
        public global::SpacetimeDB.Col<SharedBodyDescriptionProjection, double> Radius { get; }
        public global::SpacetimeDB.Col<SharedBodyDescriptionProjection, double> Height { get; }

        public VisibleBodyDescriptionsCols(string tableName)
        {
            BodyId = new global::SpacetimeDB.Col<SharedBodyDescriptionProjection, string>(tableName, "body_id");
            Kind = new global::SpacetimeDB.Col<SharedBodyDescriptionProjection, string>(tableName, "kind");
            Appearance = new global::SpacetimeDB.Col<SharedBodyDescriptionProjection, string>(tableName, "appearance");
            Seed = new global::SpacetimeDB.Col<SharedBodyDescriptionProjection, uint>(tableName, "seed");
            Radius = new global::SpacetimeDB.Col<SharedBodyDescriptionProjection, double>(tableName, "radius");
            Height = new global::SpacetimeDB.Col<SharedBodyDescriptionProjection, double>(tableName, "height");
        }
    }

    public sealed class VisibleBodyDescriptionsIxCols
    {
        public global::SpacetimeDB.IxCol<SharedBodyDescriptionProjection, string> BodyId { get; }

        public VisibleBodyDescriptionsIxCols(string tableName)
        {
            BodyId = new global::SpacetimeDB.IxCol<SharedBodyDescriptionProjection, string>(tableName, "body_id");
        }
    }
}
