// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class VisibleShipLogicHandle : RemoteTableHandle<EventContext, ShipLogicDeviceStatus>
        {
            public override string RemoteTableName => "visible_ship_logic";

            public sealed class KeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ShipLogicDeviceStatus row) => row.Key;

                public KeyUniqueIndex(VisibleShipLogicHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            internal VisibleShipLogicHandle(DbConnection conn) : base(conn)
            {
                Key = new(this);
            }

            protected override object GetPrimaryKey(ShipLogicDeviceStatus row) => row.Key;
        }

        public readonly VisibleShipLogicHandle VisibleShipLogic;
    }

    public sealed class VisibleShipLogicCols
    {
        public global::SpacetimeDB.Col<ShipLogicDeviceStatus, string> Key { get; }
        public global::SpacetimeDB.Col<ShipLogicDeviceStatus, string> ShipId { get; }
        public global::SpacetimeDB.Col<ShipLogicDeviceStatus, string> DeviceId { get; }
        public global::SpacetimeDB.Col<ShipLogicDeviceStatus, string> Kind { get; }
        public global::SpacetimeDB.Col<ShipLogicDeviceStatus, string> State { get; }
        public global::SpacetimeDB.Col<ShipLogicDeviceStatus, string> Light { get; }
        public global::SpacetimeDB.Col<ShipLogicDeviceStatus, bool> Open { get; }
        public global::SpacetimeDB.Col<ShipLogicDeviceStatus, ulong> EndsMicros { get; }
        public global::SpacetimeDB.Col<ShipLogicDeviceStatus, ulong> PressedMicros { get; }

        public VisibleShipLogicCols(string tableName)
        {
            Key = new global::SpacetimeDB.Col<ShipLogicDeviceStatus, string>(tableName, "key");
            ShipId = new global::SpacetimeDB.Col<ShipLogicDeviceStatus, string>(tableName, "ship_id");
            DeviceId = new global::SpacetimeDB.Col<ShipLogicDeviceStatus, string>(tableName, "device_id");
            Kind = new global::SpacetimeDB.Col<ShipLogicDeviceStatus, string>(tableName, "kind");
            State = new global::SpacetimeDB.Col<ShipLogicDeviceStatus, string>(tableName, "state");
            Light = new global::SpacetimeDB.Col<ShipLogicDeviceStatus, string>(tableName, "light");
            Open = new global::SpacetimeDB.Col<ShipLogicDeviceStatus, bool>(tableName, "open");
            EndsMicros = new global::SpacetimeDB.Col<ShipLogicDeviceStatus, ulong>(tableName, "ends_micros");
            PressedMicros = new global::SpacetimeDB.Col<ShipLogicDeviceStatus, ulong>(tableName, "pressed_micros");
        }
    }

    public sealed class VisibleShipLogicIxCols
    {
        public global::SpacetimeDB.IxCol<ShipLogicDeviceStatus, string> Key { get; }

        public VisibleShipLogicIxCols(string tableName)
        {
            Key = new global::SpacetimeDB.IxCol<ShipLogicDeviceStatus, string>(tableName, "key");
        }
    }
}
