// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Sidereal.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class VisibleCombatActionsHandle : RemoteTableHandle<EventContext, CombatActionStatus>
        {
            public override string RemoteTableName => "visible_combat_actions";

            public sealed class CharacterIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(CombatActionStatus row) => row.CharacterId;

                public CharacterIdUniqueIndex(VisibleCombatActionsHandle table) : base(table) { }
            }

            public readonly CharacterIdUniqueIndex CharacterId;

            internal VisibleCombatActionsHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
            }

            protected override object GetPrimaryKey(CombatActionStatus row) => row.CharacterId;
        }

        public readonly VisibleCombatActionsHandle VisibleCombatActions;
    }

    public sealed class VisibleCombatActionsCols
    {
        public global::SpacetimeDB.Col<CombatActionStatus, string> CharacterId { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, string> ShipId { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, string> DeckId { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, string> DefinitionId { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, string> Mode { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, ulong> ShotSequence { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, ulong> ShotMicros { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, double> OriginX { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, double> OriginY { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, string> PointsJson { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, double> LandX { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, double> LandY { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, ulong> DetonateMicros { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, bool> Detonated { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, double> BlastRadiusM { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, ulong> ReloadSequence { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, ulong> ReloadUntilMicros { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, ulong> StunnedUntilMicros { get; }
        public global::SpacetimeDB.Col<CombatActionStatus, ulong> StunSequence { get; }

        public VisibleCombatActionsCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.Col<CombatActionStatus, string>(tableName, "character_id");
            ShipId = new global::SpacetimeDB.Col<CombatActionStatus, string>(tableName, "ship_id");
            DeckId = new global::SpacetimeDB.Col<CombatActionStatus, string>(tableName, "deck_id");
            DefinitionId = new global::SpacetimeDB.Col<CombatActionStatus, string>(tableName, "definition_id");
            Mode = new global::SpacetimeDB.Col<CombatActionStatus, string>(tableName, "mode");
            ShotSequence = new global::SpacetimeDB.Col<CombatActionStatus, ulong>(tableName, "shot_sequence");
            ShotMicros = new global::SpacetimeDB.Col<CombatActionStatus, ulong>(tableName, "shot_micros");
            OriginX = new global::SpacetimeDB.Col<CombatActionStatus, double>(tableName, "origin_x");
            OriginY = new global::SpacetimeDB.Col<CombatActionStatus, double>(tableName, "origin_y");
            PointsJson = new global::SpacetimeDB.Col<CombatActionStatus, string>(tableName, "points_json");
            LandX = new global::SpacetimeDB.Col<CombatActionStatus, double>(tableName, "land_x");
            LandY = new global::SpacetimeDB.Col<CombatActionStatus, double>(tableName, "land_y");
            DetonateMicros = new global::SpacetimeDB.Col<CombatActionStatus, ulong>(tableName, "detonate_micros");
            Detonated = new global::SpacetimeDB.Col<CombatActionStatus, bool>(tableName, "detonated");
            BlastRadiusM = new global::SpacetimeDB.Col<CombatActionStatus, double>(tableName, "blast_radius_m");
            ReloadSequence = new global::SpacetimeDB.Col<CombatActionStatus, ulong>(tableName, "reload_sequence");
            ReloadUntilMicros = new global::SpacetimeDB.Col<CombatActionStatus, ulong>(tableName, "reload_until_micros");
            StunnedUntilMicros = new global::SpacetimeDB.Col<CombatActionStatus, ulong>(tableName, "stunned_until_micros");
            StunSequence = new global::SpacetimeDB.Col<CombatActionStatus, ulong>(tableName, "stun_sequence");
        }
    }

    public sealed class VisibleCombatActionsIxCols
    {
        public global::SpacetimeDB.IxCol<CombatActionStatus, string> CharacterId { get; }

        public VisibleCombatActionsIxCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.IxCol<CombatActionStatus, string>(tableName, "character_id");
        }
    }
}
